### ISSUE TITLE
关于数据集中单个example的长度

### ISSUE THREAD

**Issue by li-aolong** [hiyouga/ChatGLM-Efficient-Tuning#1]
数据集是多轮对话的，一个example的history可能比较长，是最好要限制在2048个token以内吗？

**Comment by hiyouga** [comment]
ChatGLM在预训练时，设置的最大长度即为2048，尽管理论上可以支持更长的句子，但是模型性能会显著下降[1]。同时，过长的sequence也会影响训练效率。

[1]https://github.com/THUDM/ChatGLM-6B#%E6%A8%A1%E5%9E%8B%E9%87%8F%E5%8C%96
