### ISSUE TITLE
accelerate. ChildFailedError. failed (exitcode: -7) local_rank: 0

### ISSUE THREAD

**Issue by kxleee** [hiyouga/ChatGLM-Efficient-Tuning#102]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/133563081/5fe7c499-6988-4f11-be0f-b6190358b900)

**Comment by hiyouga** [comment]
分布式训练的报错信息比较复杂，目前的文档不足以支持解惑，可以尝试使用 deepspeed 训练。
