### ISSUE TITLE
AttributeError: 'DistributedDataParallel' object has no attribute 'generate'

### ISSUE THREAD

**Issue by Aurora-6** [hiyouga/ChatGLM-Efficient-Tuning#103]
请问step3 ppo rlhf这步目前支持accelerate吗？尝试训练了一下，单卡ok，用accelerate就报错AttributeError: 'DistributedDataParallel' object has no attribute 'generate'。有什么解决办法吗？

**Comment by hiyouga** [comment]
使用 accelerate 了吗？

**Comment by hiyouga** [comment]
使用的是本项目的最新版本代码吗？发一下完整报错信息截图。

**Comment by Aurora-6** [comment]
看了下log，本项目版本用的是5.11这版。
commit 4b367e75a31a8b5634aa4686201d82ab252f62e8 (HEAD -> main, origin/main, origin/HEAD)
Author: hiyouga <hiyouga@buaa.edu.cn>
Date:   Thu May 11 23:11:04 2023 +0800
    tiny fix

报错信息：
`Traceback (most recent call last):
  File "train_ppo.py", line 124, in <module>
    main()
  File "train_ppo.py", line 88, in main
    response = unwrapped_model.generate(
  File "/root/miniconda3/envs/glm/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 79, in __getattr__
    return getattr(self._orig_mod, name)
  File "/root/miniconda3/envs/glm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    responses_with_queries = ppo_trainer.generate(queries, length_sampler=output_length_sampler, **gen_kwargs)
  File "ChatGLM-Efficient-Tuning/ppo_src/utils/ppo.py", line 164, in generate
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'generate'
    response = unwrapped_model.generate(
  File "/root/miniconda3/envs/glm/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 79, in __getattr__
    return getattr(self._orig_mod, name)
  File "/root/miniconda3/envs/glm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DistributedDataParallel' object has no attribute 'generate'
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 91482 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 91483) of binary: /root/miniconda3/envs/glm/bin/python`

**Comment by Aurora-6** [comment]
刚看到新出的更新commit ecf576075b8f3257bb8663f711c0d88547281123，是不是修复这个问题呢？

**Comment by Aurora-6** [comment]
accelerate==0.17.1

**Comment by hiyouga** [comment]
用新版代码试一下。

**Comment by hiyouga** [comment]
试试在 Accelerate 中不要启用 dynamo。

**Comment by hiyouga** [comment]
问了群里的用户，在 Accelerate config 中的 dynamo backend 要选择 inductor。

**Comment by Aurora-6** [comment]
原本用的dynamo backend=‘EAGER’。我试了下不用dynamo就可以正常跑通，但是不是训练会降速呢...如果dynamo backend选用inductor也是会报同样错误AttributeError: 'DistributedDataParallel' object has no attribute 'generate'。

请问这个commit ecf576075b8f3257bb8663f711c0d88547281123 主要修正的是什么呢？

**Comment by hiyouga** [comment]
上述 commit 修复的主要是分布式训练导致 position ids 中出现的 padding 问题。

**Comment by Aurora-6** [comment]
> 上述 commit 修复的主要是分布式训练导致 position ids 中出现的 padding 问题。

好的，感谢～
