### ISSUE TITLE
想用pycharm进行debug但是找不到数据目录

### ISSUE THREAD

**Issue by CCzzzzzzz** [hiyouga/ChatGLM-Efficient-Tuning#107]
如图，终端可以正常运行，但是直接run就不行，参数已经全部设置
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/99600203/91b28df8-3f91-4d22-80ec-77221f681c77)

**Comment by hiyouga** [comment]
可能是相对路径的寻址出现了问题，我没有使用 PyCharm，不太了解这个问题。

**Comment by intothephone** [comment]
设置一下Working Directory就行
