### ISSUE TITLE
对输入文本的截断可能会丢掉用户query

### ISSUE THREAD

**Issue by jet-yangqs** [hiyouga/ChatGLM-Efficient-Tuning#108]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/30697975/88655b19-57d2-4419-9e3d-bdca4a751ed9)
用户query放在输入的结尾，此处：https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/0d5d1bf029a7b6ffd5f1aaf219bb2caab41e5d09/src/utils/common.py#LL401C74-L401C74
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/30697975/2070e0b3-ed40-40b8-a48b-e0839239aedb)

当输入超出指定的最大输入长度时，保留前面的字符串，可能丢掉用户query。是否应该改为：source_ids = source_ids[-(data_args.max_source_length +2):]

**Comment by hiyouga** [comment]
感谢建议，我们将输入序列的截断方式从右侧改为了左侧：
```python
source_ids = source_ids[:data_args.max_source_length - 2] # old
source_ids = source_ids[-data_args.max_source_length + 2:] # new
```

**Comment by AttentionAllUNeed** [comment]
你好，改为左侧是不是会有问题呢。
1. 我现在尝试使用长文本摘要数据集在摘要任务上微调。我发现按照这样更改会截断content内容中倒数512 token 导致input丢失content头部内容的信息（摘要任务一般文章头部的信息会比较重要）同时构造的Instruct（source_prefix）也会被截断。这样模型会不会都不知道任务是什么？

2. 我发现跑ChatGLM源码中给入模型的content为什么会在最后concat summary，这个部分可以更改嘛。我觉得只应该给模型content并且把summary当成label
