### ISSUE TITLE
关于reward_model的性能测试问题

### ISSUE THREAD

**Issue by authurlord** [hiyouga/ChatGLM-Efficient-Tuning#109]
1. 我注意到comparison_alpaca_en的格式与alpaca-gpt4-en的格式不同，instruction是"Below xxx\n\n###Instruction: %s \n\n ###Input: %s"，input为空，output为一个list，instruction/input的格式与train_sft的格式不同，如果我自己准备训练reward_model的comparison data，instruction需要保持和comparison_alpaca_en完全相同的格式吗？

2. 如果执行全部在英文文本的任务，reward model建议在comparison_alpaca_en上训练后，再加载这个lora checkpoint之后继续在自己的comparison dataset上training吗？还是直接在ChatGLM-6b上training?

3. 如何进行reward_model性能的测试？仍然是python src/train_sft.py --do-predict --checkpoint_dir=reward_model_path吗？

4. 在实验中，我们使用了Instruction与output格式固定的一个领域垂直的comparison data，但是在reward model training后，发现reward model输出的结果似乎还是ChatGLM输出的结果，虽然loss收敛但是comparison data并没有对reward model起到指导作用，导致最后的PPO模型精度大幅度下降（可能是reward model指导错误），反而不如sft model，这可能是train_rm的问题还是数据准备的问题？应该如何有效测试reward_model的性能？

多谢回答，如有需要我可以放上细节

**Comment by hiyouga** [comment]
1. comparison data 是为了用于 reward model 的训练，它与另外两个阶段的数据集的区别在于 output 是一个长度为 2 的 list。也就是说，训练 reward model 只能用有多个 output 的数据进行训练，其中 output 由从好到坏进行排序。而 instruction 和 input 列与其他数据集并无区别，它们的格式不重要。如果要自己准备训练 reward model 的数据，只需要遵循 output 的格式。
2. 如果有自己的 comparison dataset，可以在训练时候使用 `train_rm.py --dataset dataset1,dataset2` 同时训练多个数据集，增加训练样本的数量有助于提升训练效果。
3. 不能使用 SFT 阶段的目标测试 reward model，它们的训练目标有很大区别。应当使用 `train_rm.py --do_eval` 来测试 reward model 的性能，之后我们可能会加入 Accurary 指标进行评测。
4. 使用 reward model 做文本生成是一个错误的行为，因为它的训练目标并不是提高生成能力，而是结合 valuehead 对文本进行评分，我们推荐使用 eval_loss 来评价 reward model 的性能。PPO 模型的精度可能和 PPO 的训练超参数有关，建议使用较小的学习率，每训练 500 step 保存一次模型，及时观察 loss 和 reward 值的变化。

**Comment by authurlord** [comment]
多谢回复，但是在src/utils/common.py:228行，提示：

**Comment by hiyouga** [comment]
其实 RM 是可以的，我忘记删除那一行了。
