### ISSUE TITLE
更新后的输入文本的截断是否会导致其它问题？

### ISSUE THREAD

**Issue by AttentionAllUNeed** [hiyouga/ChatGLM-Efficient-Tuning#115]
原问题 #108 

@hiyouga  你好，感谢这项工作，想讨论一下看看改为左侧是不是会有问题呢。

1. 我现在尝试使用长文本摘要数据集在摘要任务上微调。我发现按照这样更改会截断content内容中倒数512 token 导致input丢失content头部内容的信息（摘要任务一般文章头部的信息会比较重要）同时构造的Instruct（source_prefix）也会被截断。这样模型会不会都不知道任务是什么？

2. 我发现跑ChatGLM源码中给入模型的content为什么会在最后concat summary，这个部分可以更改嘛。我觉得只应该给模型content并且把summary当成label

**Comment by hiyouga** [comment]
1. 从左侧截取确实会导致 source prefix 被截断的问题，我打算还是还原成从右侧截取的方式。
2. 在监督微调时候的确应该这么做，并不会导致模型预测 label 时候提前看到 label 信息的问题。

**Comment by AttentionAllUNeed** [comment]
1. 对的，尝试以后从右侧截取效果较好
2. 谢谢回复，之前对GLM原理没太深入，确认以后Auto-regressive模型确实是这样
