### ISSUE TITLE
ValueError: Responses are too short. Make sure they are at least 4 tokens long.

### ISSUE THREAD

**Issue by MAJIN123** [hiyouga/ChatGLM-Efficient-Tuning#116]
请问这是什么原因啊。在ppo阶段出的问题

**Comment by MAJIN123** [comment]
<img width="1245" alt="image" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/18400039/039e300c-399c-419e-9454-1440e6e2bd55">

**Comment by hiyouga** [comment]
PPO 阶段加载的 SFT 模型能正常生成句子吗？

**Comment by hiyouga** [comment]
已记录，之后尝试修复。

**Comment by MAJIN123** [comment]
请问目前这个我有办法可以解决嘛，好奇怪，用提供的数据跑一遍是没有问题的 @hiyouga

**Comment by hiyouga** [comment]
你用的代码是最新版本吗？看起来似乎不是，请用 `git pull` 更新一下。
