### ISSUE TITLE
能否支持在模型推理时使用bnb量化

### ISSUE THREAD

**Issue by T-Atlas** [hiyouga/ChatGLM-Efficient-Tuning#117]
现在在inference的时候使用cpm，我看bitsandbytes库里也有相关8位推理的更新，不知道是否支持

**Comment by hiyouga** [comment]
cpm 的兼容性目前要比 bnb 更好，bnb 的推理量化需要高版本依赖库的支持，为了兼容性考虑我们还是保持使用 cpm。

**Comment by T-Atlas** [comment]
> cpm 的兼容性目前要比 bnb 更好，bnb 的推理量化需要高版本依赖库的支持，为了兼容性考虑我们还是保持使用 cpm。

明白了
