### ISSUE TITLE
作者大大，想问下，如果完全按照你们的数据，代码，脚本参数，可以复现出和你们一样的效果吗～

### ISSUE THREAD

**Issue by hangzeli08** [hiyouga/ChatGLM-Efficient-Tuning#12]

**Comment by hiyouga** [comment]
请问你指的是复现ChatGLM模型还是复现ChatGLM的微调结果？

**Comment by hangzeli08** [comment]
复现基于ChatGLM微调后的结果，能达到差不多的微调效果 和得到差不多的 BLEU 和中文 ROUGE 分数吗～

**Comment by hiyouga** [comment]
> 复现基于ChatGLM微调后的结果，能达到差不多的微调效果 和得到差不多的 BLEU 和中文 ROUGE 分数吗～

是的，微调结果是可复现的。
