### ISSUE TITLE
ppo阶段quantization_bit=8，为什么训练时可支持的max_source_length没有增大呢？

### ISSUE THREAD

**Issue by Aurora-6** [hiyouga/ChatGLM-Efficient-Tuning#124]
quantization_bit=8相比None，可支持的max_source_length没有显著增大。想请教下是什么原因呢？

**Comment by Aurora-6** [comment]
12%|█▏        | 8/69 [27:29<3:21:34, 198.27s/it]

**Comment by hiyouga** [comment]
量化后的模型的确会损失训练速度，但训练模型使用的显存理论上会减小，同时支持的 max_source_length 会增大。你通过具体的实验验证过了吗？
