### ISSUE TITLE
如何给模型灌输概念领域知识

### ISSUE THREAD

**Issue by starphantom666** [hiyouga/ChatGLM-Efficient-Tuning#125]
比如现在有一个物理学概念，百科对他的相关解释定义较长，我希望模型可以全部学会这块知识，但是每次模型微调的输入是有限制的，我应该怎么做，才能把这样的概念认知告诉模型

**Comment by hiyouga** [comment]
这种情况最好做二次预训练，仅通过微调较难实现。可以关注我们的二次预训练框架：https://github.com/hiyouga/LLaMA-Efficient-Tuning。
