### ISSUE TITLE
pyarrow.lib.ArrowNotImplementedError: Not implemented type for Arrow list to pandas: halffloat

### ISSUE THREAD

**Issue by yuguo-Jack** [hiyouga/ChatGLM-Efficient-Tuning#127]
在ppo训练脚本执行时，在开始训练后开始读dataloader数据时候出现该错误：
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/29474149/26114967-2af5-425f-9b74-0c89ab0333ef)
你们有遇到过吗

**Comment by hiyouga** [comment]
是不是数据集中包含了 pandas 不支持的数据类型？

**Comment by yuguo-Jack** [comment]
这个原因查到了，ppo中self.step时传入的rewards是fp16类型，这个fp16 rewards是由于fp16的reward model输出而来的，导致在trl/trainer/ppo_trainer.py中又将这些数据封装成minidataset供ppo epoch使用，因此将minidataset中的fp16数据转成fp32解决。但是理论上你们sft，rm阶段的保存的模型都是fp16，ppo阶段又会把rm的输出（应该是有fp16类型的）封成dataset，而datasets包中pyarrow是处理不了halffloat类型的to_numpy的，然后就报错，但是你们怎么会从来没遇到过呢，很奇怪，这个bug应该很容易遇到才对。

**Comment by hiyouga** [comment]
检查一下 pandas 版本？我用的是 1.5.3。

**Comment by hiyouga** [comment]
我在最新版本的代码中修改了 rewards 的数据类型，目前应该不会出现问题了。
