### ISSUE TITLE
为什么训练保存的checkpoint里没有finetuning_args.json文件？

### ISSUE THREAD

**Issue by king21guns** [hiyouga/ChatGLM-Efficient-Tuning#131]
在加载finetune后的模型，会报错ValueError: Missing fine-tuning arguments in the provided dictionary.

**Comment by hiyouga** [comment]
你加载的模型是通过本项目微调的模型吗？

**Comment by king21guns** [comment]
> 你加载的模型是通过本项目微调的模型吗？

原始模型是ChatGLM-6B，https://huggingface.co/THUDM/chatglm-6b/tree/main。
finetune是用的

**Comment by hiyouga** [comment]
更新一下代码，我修改了这部分逻辑。
