### ISSUE TITLE
finetune后保存的模型，即output_dir，怎么导出成可以加载用来预测的模型？

### ISSUE THREAD

**Issue by Congcong-Song** [hiyouga/ChatGLM-Efficient-Tuning#132]

**Comment by Congcong-Song** [comment]
如图，是我lora后保存的文件，但是不能直接加载用来预测：
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/78061552/995e358c-6c8c-4e60-99df-2cd6c33efc21)

**Comment by hiyouga** [comment]
导出模型可以使用 export_model.py。
加载测试时候可以使用 cli_demo.py 等，请详细查看 readme。

**Comment by Congcong-Song** [comment]
这个问题已经解决啦！checkpoint_dir就是训练后lora的权重，但是训练和推理时用的gpu数量要相同。

**Comment by LebronJames0423** [comment]
> 这个问题已经解决啦！checkpoint_dir就是训练后lora的权重，但是训练和推理时用的gpu数量要相同。

@hiyouga 请问下，训练时用了两张卡，推理是不能只用一张卡吗？

**Comment by hiyouga** [comment]
@LebronJames0423 可以使用任意数量的卡，ta的说法不正确。
