### ISSUE TITLE
readme中Hardware Requirements有一些疑问。

### ISSUE THREAD

**Issue by panxb833** [hiyouga/ChatGLM-Efficient-Tuning#133]
RLHF method中，max_source_length和max_target_length是默认的512吗？因为我这边跑了一下ppo，per_device_train_batch_size=1，max_source_length=512，max_target_length=128就显存不够了，我的gpu是24g的。

**Comment by panxb833** [comment]
如果用accelerate多卡配置，能把max_source_length调大吗

**Comment by hiyouga** [comment]
accelerate 本质是 DDP，而不是 model parallel，所以不能调大 max source length。

**Comment by panxb833** [comment]
大佬，看你新增了qlora功能，想问一下，ppo阶段，使用qlora的话，max_source_length最多能调成多大呀？之前说是256，现在能调成512或者768吗？24g的gpu。

**Comment by hiyouga** [comment]
@panxb833 可以自由尝试下，我没有实验数据。
