### ISSUE TITLE
bug: `load_pretrained` 位置参数顺序出错

### ISSUE THREAD

**Issue by beidongjiedeguang** [hiyouga/ChatGLM-Efficient-Tuning#134]
https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/d22550dda379c863c41b1de94c26d02d1094594b/src/train_sft.py#L25  

https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/d22550dda379c863c41b1de94c26d02d1094594b/src/utils/common.py#L130-L135

位置参数 `training_args, finetuning_args,`  顺序不匹配

**Comment by hiyouga** [comment]
目前已经修复，感谢建议。
