### ISSUE TITLE
是否支持融合多个lora训练出的checkpoint融，并且输出一个为chenckpoint或者model

### ISSUE THREAD

**Issue by BXHQu** [hiyouga/ChatGLM-Efficient-Tuning#135]
例子：
需要单独训练N个训练集：N>=16
训练集1 --->  lora-训练集1-LR/checkpoint1
训练集2 --->  lora-训练集1-LR/checkpoint2
训练集3 --->  lora-训练集1-LR/checkpoint3
......
训练集n --->  lora-训练集1-LR/checkpointnN

N个chenckpoin融合成一个checkpoints
checkpoint_new = (checkpoint1+checkpoint2..._checkpointN)
2.N个chenckpoin融合成一个model
export_model.py checkpoin_dir checkpoint1,checkpoint2,.... ,checkpointN

**Comment by hiyouga** [comment]
我们所有的脚本均支持 LoRA 融合。

**Comment by BXHQu** [comment]
> 我们所有的脚本均支持 LoRA 融合。
谢谢了，老师
