### ISSUE TITLE
lora微调后的chatglm回答问题偶尔会出现无限回复直到占满token

### ISSUE THREAD

**Issue by starphantom666** [hiyouga/ChatGLM-Efficient-Tuning#139]
目前没有找到原因，会一直回复最后出现的几句话

**Comment by starphantom666** [comment]
现在我是比较暴力在解决，我发现截断只用原来字符串len-1或者更多截断能一定程度缓解，但这种解决办法是比较治标不治本的

**Comment by hiyouga** [comment]
可能是数据集质量比较差导致的问题，或者是训练没有收敛。

**Comment by starphantom666** [comment]
> 可能是数据集质量比较差导致的问题，或者是训练没有收敛。

我只有100条数据。。。。对于微调数据量这块，如果质量都比较高的话，多少条是比较理想的性价比选择

**Comment by hiyouga** [comment]
至少需要 1000 条以上的数据。

**Comment by shaonianyr** [comment]
如果是新的 instruction，最好 5w+

**Comment by starphantom666** [comment]
> 如果是新的 instruction，最好 5w+

好的好的，谢谢

**Comment by starphantom666** [comment]
> 至少需要 1000 条以上的数据。

ok，谢谢大佬
