### ISSUE TITLE
eval alpaca_gpt4_zh数据集的BLEU-4分数与README中的差距很大，请问是什么原因？

### ISSUE THREAD

**Issue by happyNLP** [hiyouga/ChatGLM-Efficient-Tuning#144]
命令，参数：
CUDA_VISIBLE_DEVICES=1 WANDB_DISABLED=true python src/train_sft.py \
    --do_eval \
    --dataset alpaca_gpt4_zh \
    --output_dir eval_result \
    --per_device_eval_batch_size 2 \
    --max_samples 100 \
    --predict_with_generate

评估结果：
![未命名图片](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/96564722/8e1efd62-b4ff-4abf-9d95-22b3022001dc)

README中BLEU-4为15.75：
![微信截图_20230607114634](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/96564722/6234c0a4-f212-4b82-a649-84b49a63d674)
请问是什么原因？

**Comment by hiyouga** [comment]
BLEU 在中文数据集上不是很有参考性。
