### ISSUE TITLE
模型评估：原始模型和微调后的模型所需时长相差很多

### ISSUE THREAD

**Issue by happyNLP** [hiyouga/ChatGLM-Efficient-Tuning#146]
评估数据量1835个样本，batchsize = 2
lora微调后的模型评估时间为25分钟：
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/96564722/fd714022-a31d-4fc9-9cf3-8146118ae46b)
而原始模型评估时间要3个小时：
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/96564722/a42b4942-178d-467b-8832-949916ac9add)
请问是什么导致的差异？

**Comment by hiyouga** [comment]
这个 LoRA 模型可以正常生成句子吗？评估时间和模型的句子输出长度有关。
