### ISSUE TITLE
找不到arguments模块

### ISSUE THREAD

**Issue by cutelitchi** [hiyouga/ChatGLM-Efficient-Tuning#15]
CUDA_VISIBLE_DEVICES=0 python3 infer.py --checkpoint_dir ../output/checkpoint-2000
 执行后，提示如下错误：
 ModuleNotFoundError: No module named 'arguments'
请问一下，这个arguments是PIP3库里的arguments吗？还是本地的

**Comment by hiyouga** [comment]
十分抱歉，因为今天我们更新了代码逻辑，导致旧版本训练的checkpoint文件无法正常加载，请使用最新代码重新训练或者选择将代码回滚到以下版本来解决报错：
https://github.com/hiyouga/ChatGLM-Efficient-Tuning/tree/39aef767c853003e88888cb5832495d6653a95e0
