### ISSUE TITLE
二次微调

### ISSUE THREAD

**Issue by testmurk** [hiyouga/ChatGLM-Efficient-Tuning#150]
请问如何在第一次lora微调的基础上再进行微调训练，此类方法是否会因为两次微调的数据集不相干而导致的灾难性遗忘问题。

**Comment by hiyouga** [comment]
你可以通过 `--checkpoint_dir` 参数加载前一个（或多个） LoRA 权重继续训练，并且可以通过 `--resume_lora_training` 参数控制在本次训练中是创建新的 LoRA 权重还是基于上次的 LoRA 权重进一步训练。

**Comment by testmurk** [comment]
那可以把1m的训练数据切分成10k*100次迭代训练吗，训练效果和1m一次训练会不会有区别。

**Comment by hiyouga** [comment]
理论上两者是不一样的，因为学习率会在训练时候不断变化，但是两者效果哪个比较更好我也不太确定。

**Comment by testmurk** [comment]
好的，那我自己测试一下

**Comment by Karenlyw** [comment]
> 好的，那我自己测试一下

hi 请问你找到解决灾难性遗忘的方案了吗？

**Comment by testmurk** [comment]
> > 好的，那我自己测试一下
> 
> hi 请问你找到解决灾难性遗忘的方案了吗？

调整学习率和batch_size，构建数据集的时候一个答案换不同的问题重复几遍
