### ISSUE TITLE
while training rlhf, it occurs some problem

### ISSUE THREAD

**Issue by OceannTwT** [hiyouga/ChatGLM-Efficient-Tuning#153]
06/08/2023 07:52:29 - INFO - utils.common - Loading dataset train_rlhf_100000_format.json...
06/08/2023 07:52:29 - WARNING - utils.common - Checksum failed: missing SHA-1 hash value in dataset_info.json.
06/08/2023 07:52:29 - WARNING - utils.common - `ddp_find_unused_parameters` needs to be set as False in DDP training.
06/08/2023 07:52:29 - INFO - utils.common - Process rank: 2, device: cuda:2, n_gpu: 1
  distributed training: True, 16-bits training: True
06/08/2023 07:52:29 - INFO - utils.common - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=1,
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_pin_memory=True,
ddp_backend=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=False,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=True,
eval_accumulation_steps=None,
eval_delay=0,
eval_steps=None,
evaluation_strategy=no,
fp16=True,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'fsdp_min_num_params': 0, 'xla': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_config=None,
generation_max_length=None,
generation_num_beams=None,
gradient_accumulation_steps=4,
gradient_checkpointing=False,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=every_save,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_inputs_for_metrics=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=2e-05,
length_column_name=length,
load_best_model_at_end=False,
local_rank=2,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=path_to_ppo_checkpoint/runs/Jun08_07-52-27_bolt-xedcy8rnsc-twsryqr2iw,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=10,
logging_strategy=steps,
lr_scheduler_type=cosine,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
no_cuda=False,
num_train_epochs=1.0,
optim=adamw_torch,
optim_args=None,
output_dir=path_to_ppo_checkpoint,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=2,
predict_with_generate=False,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
resume_from_checkpoint=None,
run_name=path_to_ppo_checkpoint,
save_on_each_node=False,
save_safetensors=False,
save_steps=1000,
save_strategy=steps,
save_total_limit=None,
seed=42,
sharded_ddp=[],
skip_memory_metrics=True,
sortish_sampler=False,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
xpu_backend=None,
)
06/08/2023 07:52:29 - INFO - utils.common - Loading dataset train_rlhf_100000_format.json...
06/08/2023 07:52:29 - WARNING - utils.common - Checksum failed: missing SHA-1 hash value in dataset_info.json.
06/08/2023 07:52:29 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 447.68it/s]
06/08/2023 07:52:29 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 458.04it/s]
06/08/2023 07:52:29 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
  0%|                                                                                                | 0/1 [00:00<?, ?it/s]06/08/2023 07:52:29 - INFO - datasets.builder - Using custom data configuration default-84c7cba99465322d
06/08/2023 07:52:29 - INFO - datasets.info - Loading Dataset Infos from /mnt/miniconda/envs/py310/lib/python3.10/site-packages/datasets/packaged_modules/json
06/08/2023 07:52:29 - INFO - datasets.builder - Overwrite dataset info from restored data version if exists.
06/08/2023 07:52:29 - INFO - datasets.info - Loading Dataset info from /root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4
100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 446.68it/s]
06/08/2023 07:52:29 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
06/08/2023 07:52:29 - INFO - datasets.info - Loading Dataset info from /root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4
100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 480.83it/s]
06/08/2023 07:52:29 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 444.64it/s]
06/08/2023 07:52:29 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 441.37it/s]
06/08/2023 07:52:29 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 435.41it/s]
06/08/2023 07:52:29 - WARNING - datasets.builder - Found cached dataset json (/root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4)
100%|███████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 439.52it/s]
[INFO|tokenization_utils_base.py:1810] 2023-06-08 07:52:29,617 >> loading file ice_text.model from cache at /root/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/a8ede826cf1b62bd3c78bdfb3625c7c5d2048fbd/ice_text.model
[INFO|tokenization_utils_base.py:1810] 2023-06-08 07:52:29,617 >> loading file added_tokens.json from cache at None
[INFO|tokenization_utils_base.py:1810] 2023-06-08 07:52:29,617 >> loading file special_tokens_map.json from cache at None
[INFO|tokenization_utils_base.py:1810] 2023-06-08 07:52:29,617 >> loading file tokenizer_config.json from cache at /root/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/a8ede826cf1b62bd3c78bdfb3625c7c5d2048fbd/tokenizer_config.json
[INFO|configuration_utils.py:669] 2023-06-08 07:52:29,895 >> loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/a8ede826cf1b62bd3c78bdfb3625c7c5d2048fbd/config.json
[INFO|configuration_utils.py:669] 2023-06-08 07:52:29,896 >> loading configuration file config.json from cache at /root/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/a8ede826cf1b62bd3c78bdfb3625c7c5d2048fbd/config.json
[INFO|configuration_utils.py:725] 2023-06-08 07:52:29,897 >> Model config ChatGLMConfig {
  "_name_or_path": "THUDM/chatglm-6b",
  "architectures": [
    "ChatGLMModel"
  ],
  "auto_map": {
    "AutoConfig": "THUDM/chatglm-6b--configuration_chatglm.ChatGLMConfig",
    "AutoModel": "THUDM/chatglm-6b--modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "THUDM/chatglm-6b--modeling_chatglm.ChatGLMForConditionalGeneration"
  },
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "gmask_token_id": 130001,
  "hidden_size": 4096,
  "inner_hidden_size": 16384,
  "layernorm_epsilon": 1e-05,
  "mask_token_id": 130000,
  "max_sequence_length": 2048,
  "model_type": "chatglm",
  "num_attention_heads": 32,
  "num_layers": 28,
  "pad_token_id": 3,
  "position_encoding_2d": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "quantization_bit": 0,
  "torch_dtype": "float16",
  "transformers_version": "4.30.0.dev0",
  "use_cache": true,
  "vocab_size": 130528
}

Downloading shards: 100%|██████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 8184.01it/s]
Downloading shards: 100%|██████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 7893.30it/s]
Downloading shards: 100%|██████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 8065.97it/s]
Downloading shards: 100%|██████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 8490.49it/s]
Downloading shards: 100%|██████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 8670.40it/s]
[INFO|modeling_utils.py:2535] 2023-06-08 07:52:30,126 >> loading weights file pytorch_model.bin from cache at /root/.cache/huggingface/hub/models--THUDM--chatglm-6b/snapshots/a8ede826cf1b62bd3c78bdfb3625c7c5d2048fbd/pytorch_model.bin.index.json
Downloading shards: 100%|██████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 8338.58it/s]
Downloading shards: 100%|██████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 4690.96it/s]
[INFO|configuration_utils.py:577] 2023-06-08 07:52:30,129 >> Generate config GenerationConfig {
  "_from_model_config": true,
  "bos_token_id": 130004,
  "eos_token_id": 130005,
  "pad_token_id": 3,
  "transformers_version": "4.30.0.dev0"
}

Downloading shards: 100%|██████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 8959.79it/s]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 8/8 [00:17<00:00,  2.24s/it]
Loading checkpoint shards:  88%|█████████████████████████████████████████████████████▍       | 7/8 [00:18<00:02,  2.36s/it]06/08/2023 07:52:48 - INFO - utils.common - Fine-tuning method: LoRA
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 8/8 [00:18<00:00,  2.32s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 8/8 [00:18<00:00,  2.36s/it]
06/08/2023 07:52:49 - INFO - utils.common - Fine-tuning method: LoRA
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 8/8 [00:19<00:00,  2.39s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 8/8 [00:19<00:00,  2.40s/it]
06/08/2023 07:52:49 - INFO - utils.common - Fine-tuning method: LoRA
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 8/8 [00:19<00:00,  2.41s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 8/8 [00:19<00:00,  2.41s/it]
[INFO|modeling_utils.py:3242] 2023-06-08 07:52:49,569 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[INFO|modeling_utils.py:3250] 2023-06-08 07:52:49,569 >> All the weights of ChatGLMForConditionalGeneration were initialized from the model checkpoint at THUDM/chatglm-6b.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ChatGLMForConditionalGeneration for predictions without further training.
06/08/2023 07:52:49 - INFO - utils.common - Fine-tuning method: LoRA
06/08/2023 07:52:49 - INFO - utils.common - Fine-tuning method: LoRA
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 8/8 [00:19<00:00,  2.44s/it]
06/08/2023 07:52:49 - INFO - utils.common - Fine-tuning method: LoRA
[INFO|modeling_utils.py:2878] 2023-06-08 07:52:49,884 >> Generation config file not found, using a generation config created from the model config.
06/08/2023 07:52:49 - INFO - utils.common - Fine-tuning method: LoRA
06/08/2023 07:52:50 - INFO - utils.common - Fine-tuning method: LoRA
06/08/2023 07:53:08 - INFO - utils.common - Loaded fine-tuned model from checkpoint(s): path_to_sft_checkpoint
06/08/2023 07:53:08 - INFO - utils.common - Load reward model from path_to_rm_checkpoint
trainable params: 3674113 || all params: 6180630529 || trainable%: 0.0594
06/08/2023 07:53:08 - INFO - utils.common - Loaded fine-tuned model from checkpoint(s): path_to_sft_checkpoint
06/08/2023 07:53:08 - INFO - utils.common - Load reward model from path_to_rm_checkpoint
06/08/2023 07:53:08 - INFO - utils.common - Loaded fine-tuned model from checkpoint(s): path_to_sft_checkpoint
06/08/2023 07:53:08 - INFO - utils.common - Load reward model from path_to_rm_checkpoint
trainable params: 3674113 || all params: 6180630529 || trainable%: 0.0594
trainable params: 3674113 || all params: 6180630529 || trainable%: 0.0594
06/08/2023 07:53:09 - INFO - utils.common - Loaded fine-tuned model from checkpoint(s): path_to_sft_checkpoint
06/08/2023 07:53:09 - INFO - utils.common - Load reward model from path_to_rm_checkpoint
trainable params: 3674113 || all params: 6180630529 || trainable%: 0.0594
06/08/2023 07:53:09 - INFO - utils.common - Loaded fine-tuned model from checkpoint(s): path_to_sft_checkpoint
06/08/2023 07:53:09 - INFO - utils.common - Load reward model from path_to_rm_checkpoint
06/08/2023 07:53:09 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-73aaa2660ba091ef.arrow
input_ids:
[1303, 12, 184, 8486, 1303, 6, 184, 274, 7573, 1766, 6, 184, 4724, 3804, 27, 50810, 12, 5, 67488, 67488, 130001, 130004]
inputs:
context: no legacy context, no system dialog act, no executed tasks; utterance: 瓜瓜
trainable params: 3674113 || all params: 6180630529 || trainable%: 0.0594
06/08/2023 07:53:09 - INFO - utils.common - Loaded fine-tuned model from checkpoint(s): path_to_sft_checkpoint
06/08/2023 07:53:09 - INFO - utils.common - Load reward model from path_to_rm_checkpoint
06/08/2023 07:53:09 - INFO - utils.common - Loaded fine-tuned model from checkpoint(s): path_to_sft_checkpoint
06/08/2023 07:53:09 - INFO - utils.common - Load reward model from path_to_rm_checkpoint
06/08/2023 07:53:09 - INFO - utils.common - Loaded fine-tuned model from checkpoint(s): path_to_sft_checkpoint
06/08/2023 07:53:09 - INFO - utils.common - Load reward model from path_to_rm_checkpoint
trainable params: 3674113 || all params: 6180630529 || trainable%: 0.0594
trainable params: 3674113 || all params: 6180630529 || trainable%: 0.0594
trainable params: 3674113 || all params: 6180630529 || trainable%: 0.0594
06/08/2023 07:53:10 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-73aaa2660ba091ef.arrow
input_ids:
[1303, 12, 184, 8486, 1303, 6, 184, 274, 7573, 1766, 6, 184, 4724, 3804, 27, 50810, 12, 5, 67488, 67488, 130001, 130004]
06/08/2023 07:53:10 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-73aaa2660ba091ef.arrow
inputs:
context: no legacy context, no system dialog act, no executed tasks; utterance: 瓜瓜
input_ids:
[1303, 12, 184, 8486, 1303, 6, 184, 274, 7573, 1766, 6, 184, 4724, 3804, 27, 50810, 12, 5, 67488, 67488, 130001, 130004]
inputs:
context: no legacy context, no system dialog act, no executed tasks; utterance: 瓜瓜
06/08/2023 07:53:10 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-73aaa2660ba091ef.arrow
06/08/2023 07:53:10 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-73aaa2660ba091ef.arrow
input_ids:
[1303, 12, 184, 8486, 1303, 6, 184, 274, 7573, 1766, 6, 184, 4724, 3804, 27, 50810, 12, 5, 67488, 67488, 130001, 130004]
input_ids:
[1303, 12, 184, 8486, 1303, 6, 184, 274, 7573, 1766, 6, 184, 4724, 3804, 27, 50810, 12, 5, 67488, 67488, 130001, 130004]
inputs:
context: no legacy context, no system dialog act, no executed tasks; utterance: 瓜瓜
inputs:
context: no legacy context, no system dialog act, no executed tasks; utterance: 瓜瓜
06/08/2023 07:53:10 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-73aaa2660ba091ef.arrow
06/08/2023 07:53:10 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-73aaa2660ba091ef.arrow
06/08/2023 07:53:10 - WARNING - datasets.arrow_dataset - Loading cached processed dataset at /root/.cache/huggingface/datasets/json/default-84c7cba99465322d/0.0.0/e347ab1c932092252e717ff3f949105a4dd28b27e842dd53157d2f72e276c2e4/cache-73aaa2660ba091ef.arrow
input_ids:
[1303, 12, 184, 8486, 1303, 6, 184, 274, 7573, 1766, 6, 184, 4724, 3804, 27, 50810, 12, 5, 67488, 67488, 130001, 130004]input_ids:
[1303, 12, 184, 8486, 1303, 6, 184, 274, 7573, 1766, 6, 184, 4724, 3804, 27, 50810, 12, 5, 67488, 67488, 130001, 130004]
input_ids:
[1303, 12, 184, 8486, 1303, 6, 184, 274, 7573, 1766, 6, 184, 4724, 3804, 27, 50810, 12, 5, 67488, 67488, 130001, 130004]

inputs:
context: no legacy context, no system dialog act, no executed tasks; utterance: 瓜瓜
inputs:
context: no legacy context, no system dialog act, no executed tasks; utterance: 瓜瓜
inputs:
context: no legacy context, no system dialog act, no executed tasks; utterance: 瓜瓜
Traceback (most recent call last):
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 82, in <module>
    main()
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 55, in main
    ppo_trainer = PPOTrainerForChatGLM(
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/utils/ppo.py", line 73, in __init__
    PPOTrainer.__init__(self, **kwargs)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 308, in __init__
    self.ref_model = self.accelerator.prepare(self.ref_model)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/accelerator.py", line 1201, in prepare
    setattr(item, "_is_accelerate_prepared", True)
AttributeError: 'NoneType' object has no attribute '_is_accelerate_prepared'
Traceback (most recent call last):
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 82, in <module>
Traceback (most recent call last):
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 82, in <module>
Traceback (most recent call last):
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 82, in <module>
    main()
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 55, in main
    ppo_trainer = PPOTrainerForChatGLM(
main()  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/utils/ppo.py", line 73, in __init__

  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 55, in main
    main()
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 55, in main
    PPOTrainer.__init__(self, **kwargs)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 308, in __init__
    ppo_trainer = PPOTrainerForChatGLM(
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/utils/ppo.py", line 73, in __init__
    ppo_trainer = PPOTrainerForChatGLM(
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/utils/ppo.py", line 73, in __init__
    PPOTrainer.__init__(self, **kwargs)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 308, in __init__
        PPOTrainer.__init__(self, **kwargs)self.ref_model = self.accelerator.prepare(self.ref_model)

  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 308, in __init__
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/accelerator.py", line 1201, in prepare
Traceback (most recent call last):
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 82, in <module>
    self.ref_model = self.accelerator.prepare(self.ref_model)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/accelerator.py", line 1201, in prepare
    self.ref_model = self.accelerator.prepare(self.ref_model)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/accelerator.py", line 1201, in prepare
Traceback (most recent call last):
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 82, in <module>
    setattr(item, "_is_accelerate_prepared", True)
AttributeError: 'NoneType' object has no attribute '_is_accelerate_prepared'
    main()
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 55, in main
            setattr(item, "_is_accelerate_prepared", True)ppo_trainer = PPOTrainerForChatGLM(setattr(item, "_is_accelerate_prepared", True)

  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/utils/ppo.py", line 73, in __init__
AttributeErrorAttributeError: : 'NoneType' object has no attribute '_is_accelerate_prepared''NoneType' object has no attribute '_is_accelerate_prepared'

    PPOTrainer.__init__(self, **kwargs)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 308, in __init__
        main()self.ref_model = self.accelerator.prepare(self.ref_model)

  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/accelerator.py", line 1201, in prepare
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 55, in main
    ppo_trainer = PPOTrainerForChatGLM(
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/utils/ppo.py", line 73, in __init__
    PPOTrainer.__init__(self, **kwargs)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 308, in __init__
    setattr(item, "_is_accelerate_prepared", True)
    self.ref_model = self.accelerator.prepare(self.ref_model)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/accelerator.py", line 1201, in prepare
AttributeError: 'NoneType' object has no attribute '_is_accelerate_prepared'
    setattr(item, "_is_accelerate_prepared", True)
AttributeError: 'NoneType' object has no attribute '_is_accelerate_prepared'
Traceback (most recent call last):
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 82, in <module>
    main()
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 55, in main
    ppo_trainer = PPOTrainerForChatGLM(
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/utils/ppo.py", line 73, in __init__
    PPOTrainer.__init__(self, **kwargs)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 308, in __init__
    self.ref_model = self.accelerator.prepare(self.ref_model)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/accelerator.py", line 1201, in prepare
    setattr(item, "_is_accelerate_prepared", True)
AttributeError: 'NoneType' object has no attribute '_is_accelerate_prepared'
Traceback (most recent call last):
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 82, in <module>
    main()
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 55, in main
    ppo_trainer = PPOTrainerForChatGLM(
  File "/mnt/task_runtime/ChatGLM-Efficient-Tuning/src/utils/ppo.py", line 73, in __init__
    PPOTrainer.__init__(self, **kwargs)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/trl/trainer/ppo_trainer.py", line 308, in __init__
    self.ref_model = self.accelerator.prepare(self.ref_model)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/accelerator.py", line 1201, in prepare
    setattr(item, "_is_accelerate_prepared", True)
AttributeError: 'NoneType' object has no attribute '_is_accelerate_prepared'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 38529) of binary: /mnt/miniconda/envs/py310/bin/python
Traceback (most recent call last):
  File "/mnt/miniconda/envs/py310/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/commands/launch.py", line 932, in launch_command
    multi_gpu_launcher(args)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/accelerate/commands/launch.py", line 627, in multi_gpu_launcher
    distrib_run.run(args)
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/mnt/miniconda/envs/py310/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by hiyouga** [comment]
PPO 训练不支持 deepspeed，请使用 accelerate 实现分布式训练。
