### ISSUE TITLE
关于评估单独RM的建议

### ISSUE THREAD

**Issue by Ch4osMy7h** [hiyouga/ChatGLM-Efficient-Tuning#156]
发现如果在train_rm代码中不训练单独evaluate数据的话，目前不会加载已经训练完的value_head的checkpoint，导致evaluate效果错误，能否补上相关的加载逻辑。

**Comment by panxb833** [comment]
可以根据train_rm自己写一个eval_rm，然后手动加载value_head

**Comment by hiyouga** [comment]
目前已经支持 reward model 的正确加载，并且提供了 accuracy 指标。
