### ISSUE TITLE
自己内部的知识库数据，必须整成问答集吗？

### ISSUE THREAD

**Issue by huangxd-** [hiyouga/ChatGLM-Efficient-Tuning#16]
求教
有没有直接用纯文本微调的方法？
或者方便从文本自动生成QA的方法？

**Comment by hiyouga** [comment]
您好，感谢提问。我从 [CLONE_DK](https://github.com/wdkwdkwdk/CLONE_DK/blob/main/blog_handle_readme.md) 项目中发现了一个很实用的方法，就是使用 ChatGPT 将纯文本转换成问答对的形式，可以参考该项目并设计合适的prompt来构建数据集。
