### ISSUE TITLE
在模型测试运行时，总是显示CUDA out of Memory

### ISSUE THREAD

**Issue by 1605wzf** [hiyouga/ChatGLM-Efficient-Tuning#161]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/42125933/d1e4dab1-4c39-4ad7-b308-eedb78ffd927)
本机配置：
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/42125933/332fbb0b-4ebc-461f-a973-dde98c8c7b72)

**Comment by hiyouga** [comment]
好像是随机的 bug，https://github.com/THUDM/ChatGLM-6B/issues/790
尝试用 CUDA_VISIBLE_DEVICES=1 重新运行一下

**Comment by 1605wzf** [comment]
> 好像是随机的 bug，[THUDM/ChatGLM-6B#790](https://github.com/THUDM/ChatGLM-6B/issues/790) 尝试用 CUDA_VISIBLE_DEVICES=1 重新运行一下

谢谢，已成功解决。
