### ISSUE TITLE
QLoRA SFT后 融合权重问题

### ISSUE THREAD

**Issue by AttentionAllUNeed** [hiyouga/ChatGLM-Efficient-Tuning#162]
请问使用QLoRA后也是按照 #26  中的方式 通过export_model.py 将adapter权重融合到ChatGLM里面嘛，融合以后可以用huggingface直接加载并推理嘛？

**Comment by hiyouga** [comment]
理论上是没问题的，都可以融合。

**Comment by AttentionAllUNeed** [comment]
@hiyouga 请问大佬有尝试过嘛，我初步发现是不是还需要官方的那几个文件（modeling_chatglm.py , tokenization_chatglm.py）等等cp到新的exported模型文件夹里啊 

import os
import torch
from transformers import AutoConfig, AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("lora_exported", trust_remote_code=True)
config = AutoConfig.from_pretrained("lora_exported", trust_remote_code=True)
model = AutoModel.from_pretrained("lora_exported", config=config, trust_remote_code=True)
model = model.eval()

我按照上面提到的将提示缺少的py文件重新cp了过去 inference结果时 response, history = model.chat(tokenizer, edited_input, history)
最后 报了这样的错误RuntimeError: mixed dtype (CPU): expect input to have scalar type of BFloat16
请问这个是什么导致的呢 有办法解决吗

**Comment by hiyouga** [comment]
你在 eval 时候没有把模型放到 cuda 上。
model = model.cuda()
