### ISSUE TITLE
deepspeed 进行full tuning时 NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error

### ISSUE THREAD

**Issue by sameul-yuan** [hiyouga/ChatGLM-Efficient-Tuning#164]
8张V100, 官方deespeed.config 

> {
> 
>   "fp16": {
>     "enabled": "auto",
>     "loss_scale": 0,
>     "initial_scale_power": 16,
>     "loss_scale_window": 1000,
>     "hysteresis": 2,
>     "min_loss_scale": 1
>   },
>   "zero_optimization": {
>     "stage": 2,
>     "allgather_partitions": true,
>     "allgather_bucket_size": 2e8, 
>     "overlap_comm": false,
>     "reduce_scatter": true,
>     "reduce_bucket_size": 2e8,
>     "contiguous_gradients" : true
>   },
> 
>   "train_micro_batch_size_per_gpu": "auto",
>   "zero_allow_untested_optimizer": true
> 
> }

启动脚本如下：

> deepspeed --num_gpus=${num_gpus} --master_port $MASTER_PORT ${proj_path}/src/train_sft.py \
>     --deepspeed ${proj_path}/examples/deepspeed.json \
>     --do_train \
>     --model_name_or_path ${path_to_chatglm6b_model} \
>     --dataset ${dataset} \
>     --dataset_dir ${proj_path}/data \
>     --finetuning_type ${finetuning_type}  \
>     --output_dir ${output_dir} \
>     --overwrite_cache \
>     --per_device_train_batch_size 4 \
>     --gradient_accumulation_steps 4 \
>     --lr_scheduler_type cosine \
>     --logging_steps 100 \
>     --save_steps 1000 \
>     --learning_rate 5e-5 \
>     --num_train_epochs 1.0 \
>     --dev_ratio 0.1 \
>     --eval_steps 500 \
>     --evaluation_strategy steps \
>     --max_target_length 8 \
>     --plot_loss \
>     --fp16 

报错信息：

> with training_args.main_process_first(desc=""dataset map pre-processing""):"
> File ""/opt/conda/lib/python3.10/contextlib.py"", line 135, in __enter__"
> with training_args.main_process_first(desc=""dataset map pre-processing""):"
> File ""/opt/conda/lib/python3.10/contextlib.py"", line 135, in __enter__"
> eturn next(self.gen)
> File ""/opt/conda/lib/python3.10/site-packages/transformers-4.31.0.dev0-py3.10.egg/transformers/training_args.py"", line 1954, in main_process_first"
> eturn next(self.gen)
> File ""/opt/conda/lib/python3.10/site-packages/transformers-4.31.0.dev0-py3.10.egg/transformers/training_args.py"", line 1954, in main_process_first"
> orch.distributed.barrier()
> File ""/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py"", line 3328, in barrier"
> ork = default_pg.barrier(opts=opts)
> RuntimeError: [7] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer. This may indicate a possible application crash on rank 0 or a network set up issue."
> orch.distributed.barrier()
> File ""/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py"", line 3328, in barrier"
> ork = default_pg.barrier(opts=opts)
> RuntimeError: [5] is setting up NCCL communicator and retrieving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Connection reset by peer. This may indicate a possible application crash on rank 0 or a network set up issue."
> [2023-06-15 09:21:48,758] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 681"
> [2023-06-15 09:21:48,761] [INFO] [launch.py:314:sigkill_handler] Killing subprocess 682"
> raceback (most recent call last):

相同的配置 lora和p-tuning没有这个问题，大概什么原因导致的呢

**Comment by hiyouga** [comment]
我这边最近也遇到了相同的问题，使用 LoRA 微调，前几天还没有类似报错。

**Comment by hiyouga** [comment]
我这边重启机器后就恢复正常了。

**Comment by sameul-yuan** [comment]
> 我这边重启机器后就恢复正常了。

我在云环境跑的，通过增大CPU内存目前也没问题了
