### ISSUE TITLE
全参数微调 predict 时 adapt_model.bin里面没东西

### ISSUE THREAD

**Issue by JoyDajunSpaceCraft** [hiyouga/ChatGLM-Efficient-Tuning#165]
全参数微调 predict 时 adapt_model.bin里面无法加载weight 
  raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ChatGLMForConditionalGeneration:
        size mismatch for transformer.word_embeddings.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([130528, 4096]).

**Comment by hiyouga** [comment]
微调时候没有保存这部分参数？试试手动删除 state_dict 里面的 word_embeddings 权重。

**Comment by JoyDajunSpaceCraft** [comment]
如果你的 生成的checkpoint 里面有 zero3转换的文件 你可以尝试将现有的 checkpoint 转换 为 pytorch_model.bin 在加载weight的时候换成这个

**Comment by hiyouga** [comment]
@sameul-yuan 应该是 lm_head 和 transformer 中的 embedding 参数一致，所以他没有保存，可以手动添加一个 lm_head 参数，值为 embedding 的值。
