### ISSUE TITLE
SFT后推理可以通过调整参数让每次生成结果相同嘛

### ISSUE THREAD

**Issue by AttentionAllUNeed** [hiyouga/ChatGLM-Efficient-Tuning#166]
大佬好，我现在通过SFT推理结果，发现每次推理的结果都会有差异，是否可以通过调整什么参数在inference的时候让模型每次都输出相同的内容？

**Comment by hiyouga** [comment]
降低 top_p 和 temperature 参数，设置 do_sample=False

**Comment by AttentionAllUNeed** [comment]
谢谢大佬
