### ISSUE TITLE
大佬帮忙看下，finetuning_type freeze模式报错

### ISSUE THREAD

**Issue by spf1983** [hiyouga/ChatGLM-Efficient-Tuning#167]
日志如下：
Traceback (most recent call last):
  File "/data/ChatGLM-Efficient-Tuning/zspace-freeze/../src/train_sft.py", line 100, in <module>
    main()
  File "/data/ChatGLM-Efficient-Tuning/zspace-freeze/../src/train_sft.py", line 25, in main
    model, tokenizer = load_pretrained(model_args, finetuning_args, training_args.do_train, stage="sft")
  File "/data/ChatGLM-Efficient-Tuning/src/utils/common.py", line 173, in load_pretrained
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/ubuntu/anaconda3/envs/ChatGLM-Efficient-Tuning/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 721, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.THUDM.chatglm-6b.1d240ba371910e9282298d4592532d7f0f3e9f3e.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer.
Model type should be one of AlbertConfig, AlignConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, CodeGenConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroupViTConfig, HubertConfig, IBertConfig, JukeboxConfig, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MobileBertConfig, MPNetConfig, MT5Config, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, Pix2StructConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, RagConfig, RealmConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, ViltConfig, VisualBertConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.

执行脚本如下：
CUDA_VISIBLE_DEVICES=0 python ../src/train_sft.py \
    --do_train \
    --dataset zs_1415 \
    --dataset_dir ../data \
    --finetuning_type freeze \
    --output_dir sft_freeze_3 \
    --num_layer_trainable 3 \
    --name_module_trainable mlp \
    --max_source_length 512 \
    --max_target_length 2048 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 20 \
    --save_steps 500 \
    --learning_rate 3e-4 \
    --num_train_epochs 10.0 \
    --plot_loss \
    --fp16

备注：lora的执行是没问题的，但是改成freeze模式后，就无法执行了

**Comment by hiyouga** [comment]
可能只是网络没连接到 huggingface，用本地模型试试。
