### ISSUE TITLE
未支持chatglm ptuning-v2微调？

### ISSUE THREAD

**Issue by zhaochs1995** [hiyouga/ChatGLM-Efficient-Tuning#169]
采用垂域的数据集进行ptuning微调后，模型没有学习到垂域的知识。lora是正常的，请问是暂未支持ptuning训练吗
  if finetuning_args.finetuning_type == "p_tuning":
      logger.info("Fine-tuning method: P-Tuning v2") # nothing to do

**Comment by hiyouga** [comment]
P-Tuning v2 是支持的，这个方法不太适合注入垂域知识，只能学习到一些风格。

**Comment by AttentionAllUNeed** [comment]
我在垂域上两个都试过，目前来说Lora好于p-tuning-v2 且Lora没有出现严重的灾难性遗忘现象
