### ISSUE TITLE
Ryb

### ISSUE THREAD

**Issue by michaeloo0** [hiyouga/ChatGLM-Efficient-Tuning#17]

**Comment by michaeloo0** [comment]
Run funtune.py in Colab env caused ValueError: Undefined dataset data in dataset_info.json 
please help me how to resolve it  thanks

**Comment by hiyouga** [comment]
Hi! Thank for your question.
If you want to use the default dataset, please provide correct `--dataset` argument using keys defined in [dataset_info.json](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/data/dataset_info.json).
If you want to use your custom dataset, please follow the instruction here: [About data preparation](https://github.com/hiyouga/ChatGLM-Efficient-Tuning#data-preparation-optional).

**Comment by michaeloo0** [comment]
i have fixed this issu

**Comment by michaeloo0** [comment]
> Hi! Thank for your question. If you want to use the default dataset, please provide correct `--dataset` argument using keys defined in [dataset_info.json](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/data/dataset_info.json). If you want to use your custom dataset, please follow the instruction here: [About data preparation](https://github.com/hiyouga/ChatGLM-Efficient-Tuning#data-preparation-optional).

Thanks, fixed!
