### ISSUE TITLE
进行量化微调时出错

### ISSUE THREAD

**Issue by gugupig** [hiyouga/ChatGLM-Efficient-Tuning#173]
在使用量化微调--quantization_bit 8的时候，如果加载已经量化好的模型THUDM/chatglm-6b-int8,会出现RuntimeError: Only Tensors of floating point and complex dtype can require gradients错误，如果加载原模型就不会有问题,请问量化微调是直接在原模型上进行的吗？

补充信息: 如果将量化模型的quantization.py中self.weight = Parameter(self.weight.to(kwargs["device"]), requires_grad=False)
这一行修改为self.weight = Parameter(self.weight.float().to(kwargs["device"]), requires_grad=False)
就不会报错，但是训练时loss会一直为0

**Comment by gugupig** [comment]
感谢解答
还有几个后续问题:
精调好的CP也是直接加载到fp16的原模型上而不是量化好的模型上了？或者说加载的时候应该加上.quantize(8)
比如这样: model = AutoModel.from_pretrained("THUDM/chatglm-6b", trust_remote_code=True).quantize(8).half().cuda()
另外在导出微调模型时，导出的是量化后的模型还是原精度的模型呢？

**Comment by is** [comment]
> 精调好的CP也是直接加载到fp16的原模型上而不是量化好的模型上了？或者说加载的时候应该加上.quantize(8)

ChatGLM.quantize(8)之后中间部分结构会替换成QuantizedLinear，输出的int8，貌似就不能和lora float16的合并到一起了.
