### ISSUE TITLE
单卡评价时候出错  

### ISSUE THREAD

**Issue by LiZhangMing** [hiyouga/ChatGLM-Efficient-Tuning#176]
CUDA_VISIBLE_DEVICES=0 python src/train_sft.py   --do_eval  --dataset example  --checkpoint_dir path_to_checkpoint  --output_dir path_to_eval_result  --per_device_eval_batch_size 8  --max_samples 50   --predict_with_generate

报错为：
06/25/2023 09:10:02 - INFO - utils.common - Fine-tuning method: LoRA
Traceback (most recent call last):
  File "/home/lizhangming/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/home/lizhangming/anaconda3/envs/chatglm_etuning/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/path_to_checkpoint/resolve/main/adapter_config.json

**Comment by hiyouga** [comment]
检查一下保存 lora 权重文件夹的路径是否正确提供到 --checkpoint_dir 参数

**Comment by LiZhangMing** [comment]
谢谢您，  还有个小问题哈，就是执行完这个的时候   python src/cli_demo.py  --checkpoint_dir path_to_checkpoint

**Comment by LiZhangMing** [comment]
谢谢您， 还有个小问题哈，就是执行完这个的时候 python src/cli_demo.py --checkpoint_dir path_to_checkpoint
用户输入能不能长一点，我发现他会把我的一些内容截断。

**Comment by LiZhangMing** [comment]
> 检查一下保存 lora 权重文件夹的路径是否正确提供到 --checkpoint_dir 参数
谢谢您， 还有个小问题哈，就是执行完这个的时候 python src/cli_demo.py --checkpoint_dir path_to_checkpoint
在终端测试的时候，用户输入能不能长一点，我发现他会把我的一些内容截断。
