### ISSUE TITLE
请问这些训练超参数的值是怎么确定的？

### ISSUE THREAD

**Issue by monkeyshichi** [hiyouga/ChatGLM-Efficient-Tuning#177]
请问如下这些训练超参数的值是怎么确定的？
CUDA_VISIBLE_DEVICES=0 python src/train_pt.py \
    --model_name_or_path path_to_your_model \
    --do_train \
    --dataset wiki_demo \
    --finetuning_type lora \
    --output_dir path_to_pt_checkpoint \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --plot_loss \
    --fp16

**Comment by hiyouga** [comment]
超参数说明请查看 https://github.com/hiyouga/ChatGLM-Efficient-Tuning/wiki
具体的值是经验值。

**Comment by monkeyshichi** [comment]
谢谢大佬，这么晚还这么快回复
