### ISSUE TITLE
chatglmv2推理错误

### ISSUE THREAD

**Issue by azoth07** [hiyouga/ChatGLM-Efficient-Tuning#179]
https://huggingface.co/THUDM/chatglm2-6b
官网的模型
!cd ./ChatGLM-Efficient-Tuning && python src/web_demo.py \
    --model_name_or_path /content/drive/MyDrive/chatglm/chatglm2-6b \
    --use_v2
你好

the past master, they will be a great many, but only one of the many.
在句子中，它们只有可能是一个。
因此，答案是：它们只有可能是一个。

什么是月球？

'I'stm sorry, 1

**Comment by hiyouga** [comment]
已修复，请更新代码。
