### ISSUE TITLE
ChatGLM2训练后推理不正确

### ISSUE THREAD

**Issue by greatzane** [hiyouga/ChatGLM-Efficient-Tuning#180]
训练使用的命令行：
python src/train_sft.py     --do_train     --dataset test     --finetuning_type lora     --output_dir test_lora     --per_device_train_batch_size 4     --gradient_accumulation_steps 4     --lr_scheduler_type cosine     --logging_steps 10     --save_steps 100     --learning_rate 5e-5     --num_train_epochs 3.0     --fp16 --use_v2 --model_name_or_path THUDM/chatglm2-6b
推理使用命令行：
python src/web_demo.py --model_name_or_path THUDM/chatglm2-6b --checkpoint_dir ./test_lora/ --use_v2

推理时出现明显的错误和大量的重复。

**Comment by hiyouga** [comment]
描述具体一点

**Comment by hiyouga** [comment]
已经修复，请更新代码。

**Comment by greatzane** [comment]
更新后推理貌似训练的部分没有体现出来，加上--checkpoint_dir和不加的回答是基本一样的。

**Comment by AlphaINF** [comment]
我也出现了严重的复读现象，我采用的是认知数据集进行测试，出现了非常严重的复读。
但是，loss的下降是正常的，怀疑是训练时开头和结尾的控制token依然存在问题。

**Comment by testmurk** [comment]
+1 出现了复读现象和训练数据以外的句子。比如 训练的时候数据只有代码，但推理的时候除了输出了代码还输出了代码解释（fake info）

**Comment by AlphaINF** [comment]
我用修改自我认知的数据lora进行微调ChatGLM2时，尚未发现模型复读的现象。
但是用freeze就出现了。

**Comment by xinchunl** [comment]
> 我用修改自我认知的数据lora进行微调ChatGLM2时，尚未发现模型复读的现象。 但是用freeze就出现了。

请问下 你是怎么修改的数据？
