### ISSUE TITLE
各位大佬问下哈，在chatglm-6m上sft微调后，大家的效果怎么样（和chatglm-6b相比）？通用问题和垂直领域效果均有提升吗？我lora微调了多次，效果都不如原始6b

### ISSUE THREAD

**Issue by sun1092469590** [hiyouga/ChatGLM-Efficient-Tuning#183]

**Comment by ljch2018** [comment]
+1

**Comment by sun1092469590** [comment]
> +1

你的微调数据有多少？我这边是用了20万垂直数据和5万通用数据俩微调的，不知道是不是数据太少了

**Comment by ljch2018** [comment]
我的是100条；达到万级别，量已经非常多了。

**Comment by sun1092469590** [comment]
> 我的是100条；达到万级别，量已经非常多了。

嗯嗯，不知道咋回事，看其他项目用几万垂直数据训练的，开源出来的微调模型效果也不太好，通用领域不如6b原版，垂直领域也没有看出来效果更好。
@hiyouga  想请教一下作者大大，您这边自己有sft微调垂直领域模型模型吗，通用领域和垂直领域效果和6b相比怎么样？

**Comment by hiyouga** [comment]
@sun1092469590 我垂域微调选用的是 LLaMA 模型

**Comment by sun1092469590** [comment]
> @sun1092469590 我垂域微调选用的是 LLaMA 模型

哦哦，好的好的，谢谢大大回复。 再问下哈，您这边LLaMA训练时什么样的方式？有进一步预训练吗还是直接sft微调的？

**Comment by hiyouga** [comment]
@sun1092469590 继续预训练+微调

**Comment by sun1092469590** [comment]
> @sun1092469590 继续预训练+微调

好的好的，继续预训练用的是垂直领域数据+通用领域数据结合的方式？数据量大概是啥级别呢？（或者6b、7b这样的模型继续预训练需要怎么样的数据量效果比较好）
