### ISSUE TITLE
自己构建类似example数据集的时候，多轮对话的history是不是从空的数组，一直增加到最后类似你给的例子。还是说多轮对话只需要将最后对话之前的对话都放到history中呢。类似下面的两种方式选择哪个呢

### ISSUE THREAD

**Issue by LiZhangMing** [hiyouga/ChatGLM-Efficient-Tuning#190]
**### 下面两种多轮对话的方式，我自己构建的数据集应该选择哪种呢？**
**方式一**
`[
  {
    "instruction": "你好，你能帮我解答一个问题吗？",
    "input": "",
    "output": "当然，请问有什么问题？",
    "history": [
        []
    ]
  },
 {
    "instruction": "我想了解人工智能的未来发展方向，你有什么想法吗？",
    "input": "",
    "output": "人工智能在未来的发展方向可能包括更强大的机器学习算法，更先进的自然语言处理技术，以及更加智能的机器人。",
    "history": [
      ["你好，你能帮我解答一个问题吗？", "当然，请问有什么问题？"],
    ]
  },
  {
    "instruction": "听起来很不错。人工智能可能在哪些方面面临挑战呢？",
    "input": "",
    "output": "人工智能面临的挑战包括数据隐私、安全和道德方面的问题，以及影响就业机会的自动化等问题。",
    "history": [
      ["你好，你能帮我解答一个问题吗？", "当然，请问有什么问题？"],
      ["我想了解人工智能的未来发展方向，你有什么想法吗？", "人工智能在未来的发展方向可能包括更强大的机器学习算法，更先进的自然语言处理技术，以及更加智能的机器人。"]
    ]
  }
]`

**方式二**
`[
  {
    "instruction": "听起来很不错。人工智能可能在哪些方面面临挑战呢？",
    "input": "",
    "output": "人工智能面临的挑战包括数据隐私、安全和道德方面的问题，以及影响就业机会的自动化等问题。",
    "history": [
      ["你好，你能帮我解答一个问题吗？", "当然，请问有什么问题？"],
      ["我想了解人工智能的未来发展方向，你有什么想法吗？", "人工智能在未来的发展方向可能包括更强大的机器学习算法，更先进的自然语言处理技术，以及更加智能的机器人。"]
    ]
  }
]`

**Comment by hiyouga** [comment]
目前来说应该选择方式一，因为该项目每次只训练最后一轮。
如果想使用方式二，请移步 https://github.com/hiyouga/LLaMA-Efficient-Tuning 项目。

**Comment by heheda166** [comment]
{
    "instruction": " Human:你好，你能帮我解答一个问题吗？\nAssistant:当然，请问有什么问题？Human:我想了解人工智能的未来发展方向，你有什么想法吗？\nAssistant:人工智能在未来的发展方向可能包括更强大的机器学习算法，更先进的自然语言处理技术，以及更加智能的机器人。\nHuman:听起来很不错。人工智能可能在哪些方面面临挑战呢？\nAssistant:",
    "input": "",
    "output": "人工智能面临的挑战包括数据隐私、安全和道德方面的问题，以及影响就业机会的自动化等问题。"
}

这样构造合适吗？看到范例里面是这种形式

**Comment by hiyouga** [comment]
理论上这样也可以训练
