### ISSUE TITLE
关于多卡训练报错问题

### ISSUE THREAD

**Issue by GXKIM** [hiyouga/ChatGLM-Efficient-Tuning#195]
服务器上目前是有五张显卡，只想使用gpu0和1两张，显卡： A6000显卡
accelerate/default_config.yaml 如下
compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues

bin .local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
.local/lib/python3.8/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /root/miniconda3/envs/ChatGLM did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so.11.0
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /ai/user/lvdh/.local/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
06/28/2023 08:25:10 - INFO - torch.distributed.distributed_c10d - Added key: store_based_barrier_key:1 to store for rank: 1
06/28/2023 08:25:10 - INFO - torch.distributed.distributed_c10d - Added key: store_based_barrier_key:1 to store for rank: 0
06/28/2023 08:25:10 - INFO - torch.distributed.distributed_c10d - Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
06/28/2023 08:25:10 - INFO - torch.distributed.distributed_c10d - Rank 1: Completed store-based barrier for key:store_based_barrier_key:1 with 2 nodes.
				Traceback (most recent call last)
│ /data/ChatGLM2-6B-main/ChatGLM-Efficient-Tuning/src/train_sft.py:105 in  │
│ <module>                                                                                         │
│                                                                                                  │
│   102                                                                                            │
│   103                                                                                            │
│   104 if __name__ == "__main__":                                                                 │
│ ❱ 105 │   main()                                                                                 │
│   106                                                                                            │
│                                                                                                  │
│ /data/ChatGLM2-6B-main/ChatGLM-Efficient-Tuning/src/train_sft.py:23 in   │
│ main                                                                                             │
│                                                                                                  │
│    20 def main():                                                                                │
│    21 │                                                                                          │
│    22 │   # Prepare pretrained model and dataset                                                 │
│ ❱  23 │   model_args, data_args, training_args, finetuning_args = prepare_args(stage="sft")      │
│    24 │   dataset = prepare_data(model_args, data_args)                                          │
│    25 │   model, tokenizer = load_pretrained(model_args, finetuning_args, training_args.do_tra   │
│    26 │   dataset = preprocess_data(dataset, tokenizer, data_args, training_args, stage="sft")   │
│                                                                                                  │
│ /data/ChatGLM2-6B-main/ChatGLM-Efficient-Tuning/src/utils/common.py:287  │
│ in prepare_args                                                                                  │
│                                                                                                  │
│   284 │   if len(sys.argv) == 2 and sys.argv[1].endswith(".json"): # Provide arguments with a    │
│   285 │   │   model_args, data_args, training_args, finetuning_args = parser.parse_json_file(j   │
│   286 │   else:                                                                                  │
│ ❱ 287 │   │   model_args, data_args, training_args, finetuning_args = parser.parse_args_into_d   │
│   288 │                                                                                          │
│   289 │   # Setup logging                                                                        │
│   290 │   if training_args.should_log:                                                           │
│                                                                                                  │
│ /.local/lib/python3.8/site-packages/transformers/hf_argparser.py:355 in             │
│ parse_args_into_dataclasses                                                                      │
│                                                                                                  │
│   352 │   │   │   return (*outputs, remaining_args)                                              │
│   353 │   │   else:                                                                              │
│   354 │   │   │   if remaining_args:                                                             │
│ ❱ 355 │   │   │   │   raise ValueError(f"Some specified arguments are not used by the HfArgume   │
│   356 │   │   │                                                                                  │
│   357 │   │   │   return (*outputs,)                                                             │
│   358                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Some specified arguments are not used by the HfArgumentParser: ['src/train_sft.py']
			Traceback (most recent call last)
│ /data/ChatGLM2-6B-main/ChatGLM-Efficient-Tuning/src/train_sft.py:105 in  │
│ <module>                                                                                         │
│                                                                                                  │
│   102                                                                                            │
│   103                                                                                            │
│   104 if __name__ == "__main__":                                                                 │
│ ❱ 105 │   main()                                                                                 │
│   106                                                                                            │
│                                                                                                  │
│ /data/ChatGLM2-6B-main/ChatGLM-Efficient-Tuning/src/train_sft.py:23 in   │
│ main                                                                                             │
│                                                                                                  │
│    20 def main():                                                                                │
│    21 │                                                                                          │
│    22 │   # Prepare pretrained model and dataset                                                 │
│ ❱  23 │   model_args, data_args, training_args, finetuning_args = prepare_args(stage="sft")      │
│    24 │   dataset = prepare_data(model_args, data_args)                                          │
│    25 │   model, tokenizer = load_pretrained(model_args, finetuning_args, training_args.do_tra   │
│    26 │   dataset = preprocess_data(dataset, tokenizer, data_args, training_args, stage="sft")   │
│                                                                                                  │
│ /data/ChatGLM2-6B-main/ChatGLM-Efficient-Tuning/src/utils/common.py:287  │
│ in prepare_args                                                                                  │
│                                                                                                  │
│   284 │   if len(sys.argv) == 2 and sys.argv[1].endswith(".json"): # Provide arguments with a    │
│   285 │   │   model_args, data_args, training_args, finetuning_args = parser.parse_json_file(j   │
│   286 │   else:                                                                                  │
│ ❱ 287 │   │   model_args, data_args, training_args, finetuning_args = parser.parse_args_into_d   │
│   288 │                                                                                          │
│   289 │   # Setup logging                                                                        │
│   290 │   if training_args.should_log:                                                           │
│                                                                                                  │
│ .local/lib/python3.8/site-packages/transformers/hf_argparser.py:355 in             │
│ parse_args_into_dataclasses                                                                      │
│                                                                                                  │
│   352 │   │   │   return (*outputs, remaining_args)                                              │
│   353 │   │   else:                                                                              │
│   354 │   │   │   if remaining_args:                                                             │
│ ❱ 355 │   │   │   │   raise ValueError(f"Some specified arguments are not used by the HfArgume   │
│   356 │   │   │                                                                                  │
│   357 │   │   │   return (*outputs,)                                                             │
│   358                                                                                            │

ValueError: Some specified arguments are not used by the HfArgumentParser: ['src/train_sft.py']
[08:25:11] WARNING  Sending process 29520 closing signal SIGTERM                                                                                     api.py:699
           ERROR    failed (exitcode: 1) local_rank: 0 (pid: 29519) of binary: /root/miniconda3/envs/ChatGLM/bin/python3.8                           api.py:673

│ /root/miniconda3/envs/ChatGLM/bin/accelerate:8 in <module>                                       │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ .local/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py:45 in     │
│ main                                                                                             │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ .local/lib/python3.8/site-packages/accelerate/commands/launch.py:932 in            │
│ launch_command                                                                                   │
│                                                                                                  │
│   929 │   elif args.use_megatron_lm and not args.cpu:                                            │
│   930 │   │   multi_gpu_launcher(args)                                                           │
│   931 │   elif args.multi_gpu and not args.cpu:                                                  │
│ ❱ 932 │   │   multi_gpu_launcher(args)                                                           │
│   933 │   elif args.tpu and not args.cpu:                                                        │
│   934 │   │   if args.tpu_use_cluster:                                                           │
│   935 │   │   │   tpu_pod_launcher(args)                                                         │
│                                                                                                  │
│ .local/lib/python3.8/site-packages/accelerate/commands/launch.py:627 in            │
│ multi_gpu_launcher                                                                               │
│                                                                                                  │
│   624 │   )                                                                                      │
│   625 │   with patch_environment(**current_env):                                                 │
│   626 │   │   try:                                                                               │
│ ❱ 627 │   │   │   distrib_run.run(args)                                                          │
│   628 │   │   except Exception:                                                                  │
│   629 │   │   │   if is_rich_available() and debug:                                              │
│   630 │   │   │   │   console = get_console()                                                    │
│                                                                                                  │
│ .local/lib/python3.8/site-packages/torch/distributed/run.py:753 in run             │
│                                                                                                  │
│   750 │   │   )                                                                                  │
│   751 │                                                                                          │
│   752 │   config, cmd, cmd_args = config_from_args(args)                                         │
│ ❱ 753 │   elastic_launch(                                                                        │
│   754 │   │   config=config,                                                                     │
│   755 │   │   entrypoint=cmd,                                                                    │
│   756 │   )(*cmd_args)                                                                           │
│                                                                                                  │
│ .local/lib/python3.8/site-packages/torch/distributed/launcher/api.py:132 in        │
│ __call__                                                                                         │
│                                                                                                  │
│   129 │   │   self._entrypoint = entrypoint                                                      │
│   130 │                                                                                          │
│   131 │   def __call__(self, *args):                                                             │
│ ❱ 132 │   │   return launch_agent(self._config, self._entrypoint, list(args))                    │
│   133                                                                                            │
│   134                                                                                            │
│   135 def _get_entrypoint_name(                                                                  │
│                                                                                                  │
│ .local/lib/python3.8/site-packages/torch/distributed/launcher/api.py:246 in        │
│ launch_agent                                                                                     │
│                                                                                                  │
│   243 │   │   │   # if the error files for the failed children exist                             │
│   244 │   │   │   # @record will copy the first error (root cause)                               │
│   245 │   │   │   # to the error file of the launcher process.                                   │
│ ❱ 246 │   │   │   raise ChildFailedError(                                                        │
│   247 │   │   │   │   name=entrypoint_name,                                                      │
│   248 │   │   │   │   failures=result.failures,                                                  │
│   249 │   │   │   )                                                                              │

ChildFailedError: 
src/train_sft.py FAILED
Failures:
  <NO_OTHER_FAILURES>
Root Cause (first observed failure):
[0]:
  time      : 2023-06-28_08:25:11
  host      : dev-ai-fusioncloud-fc-k8s-worker11
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 29519)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by hiyouga** [comment]
ValueError: Some specified arguments are not used by the HfArgumentParser: ['src/train_sft.py']
命令行参数有误

**Comment by GXKIM** [comment]
> ValueError: Some specified arguments are not used by the HfArgumentParser: ['src/train_sft.py'] 命令行参数有误



> ValueError: Some specified arguments are not used by the HfArgumentParser: ['src/train_sft.py'] 命令行参数有误

哈哈哈可以了，不报错了
