### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'nonzero'

### ISSUE THREAD

**Issue by zhaoying9105** [hiyouga/ChatGLM-Efficient-Tuning#196]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /projs/AE/zhaoying/projects/ChatGLM-Efficient-Tuning/src/train_sft.py:105 in <module>            │
│                                                                                                  │
│   102                                                                                            │
│   103                                                                                            │
│   104 if __name__ == "__main__":                                                                 │
│ ❱ 105 │   main()                                                                                 │
│   106                                                                                            │
│                                                                                                  │
│ /projs/AE/zhaoying/projects/ChatGLM-Efficient-Tuning/src/train_sft.py:73 in main                 │
│                                                                                                  │
│    70 │                                                                                          │
│    71 │   # Training                                                                             │
│    72 │   if training_args.do_train:                                                             │
│ ❱  73 │   │   train_result = trainer.train()                                                     │
│    74 │   │   trainer.log_metrics("train", train_result.metrics)                                 │
│    75 │   │   trainer.save_metrics("train", train_result.metrics)                                │
│    76 │   │   trainer.save_state()                                                               │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/transformers/trainer.py:1645 in train                     │
│                                                                                                  │
│   1642 │   │   inner_training_loop = find_executable_batch_size(                                 │
│   1643 │   │   │   self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size  │
│   1644 │   │   )                                                                                 │
│ ❱ 1645 │   │   return inner_training_loop(                                                       │
│   1646 │   │   │   args=args,                                                                    │
│   1647 │   │   │   resume_from_checkpoint=resume_from_checkpoint,                                │
│   1648 │   │   │   trial=trial,                                                                  │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/transformers/trainer.py:1916 in _inner_training_loop      │
│                                                                                                  │
│   1913 │   │   │   │   rng_to_sync = True                                                        │
│   1914 │   │   │                                                                                 │
│   1915 │   │   │   step = -1                                                                     │
│ ❱ 1916 │   │   │   for step, inputs in enumerate(epoch_iterator):                                │
│   1917 │   │   │   │   total_batched_samples += 1                                                │
│   1918 │   │   │   │   if rng_to_sync:                                                           │
│   1919 │   │   │   │   │   self._load_rng_state(resume_from_checkpoint)                          │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py:652 in __next__            │
│                                                                                                  │
│    649 │   │   │   if self._sampler_iter is None:                                                │
│    650 │   │   │   │   # TODO(https://github.com/pytorch/pytorch/issues/76750)                   │
│    651 │   │   │   │   self._reset()  # type: ignore[call-arg]                                   │
│ ❱  652 │   │   │   data = self._next_data()                                                      │
│    653 │   │   │   self._num_yielded += 1                                                        │
│    654 │   │   │   if self._dataset_kind == _DatasetKind.Iterable and \                          │
│    655 │   │   │   │   │   self._IterableDataset_len_called is not None and \                    │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py:692 in _next_data          │
│                                                                                                  │
│    689 │                                                                                         │
│    690 │   def _next_data(self):                                                                 │
│    691 │   │   index = self._next_index()  # may raise StopIteration                             │
│ ❱  692 │   │   data = self._dataset_fetcher.fetch(index)  # may raise StopIteration              │
│    693 │   │   if self._pin_memory:                                                              │
│    694 │   │   │   data = _utils.pin_memory.pin_memory(data, self._pin_memory_device)            │
│    695 │   │   return data                                                                       │
│                                                                                                  │
│ /opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py:52 in fetch              │
│                                                                                                  │
│   49 │   │   │   data = [self.dataset[idx] for idx in possibly_batched_index]                    │
│   50 │   │   else:                                                                               │
│   51 │   │   │   data = self.dataset[possibly_batched_index]                                     │
│ ❱ 52 │   │   return self.collate_fn(data)                                                        │
│   53                                                                                             │
│                                                                                                  │
│ /projs/AE/zhaoying/projects/ChatGLM-Efficient-Tuning/src/utils/data_collator.py:123 in __call__  │
│                                                                                                  │
│   120 │   │   │   batch["labels"] = labels                                                       │
│   121 │   │                                                                                      │
│   122 │   │   batch["input_ids"] = input_ids                                                     │
│ ❱ 123 │   │   batch["attention_mask"] = self.get_attention_masks(input_ids, device=input_ids.d   │
│   124 │   │   batch["position_ids"] = self.get_position_ids(input_ids, device=input_ids.device   │
│   125 │   │                                                                                      │
│   126 │   │   return BatchEncoding(batch)                                                        │
│                                                                                                  │
│ /projs/AE/zhaoying/projects/ChatGLM-Efficient-Tuning/src/utils/data_collator.py:45 in            │
│ get_attention_masks_v1                                                                           │
│                                                                                                  │
│    42 │   │   attention_mask = torch.ones((batch_size, seq_length, seq_length), device=device)   │
│    43 │   │   attention_mask.tril_()                                                             │
│    44 │   │   for i, seq in enumerate(input_ids):                                                │
│ ❱  45 │   │   │   attention_mask[i, :, :(seq == self.tokenizer.bos_token_id).nonzero()[0].item   │
│    46 │   │   │   attention_mask[i, :, :(seq != self.tokenizer.pad_token_id).nonzero()[0].item   │
│    47 │   │   attention_mask.unsqueeze_(1)                                                       │
│    48 │   │   attention_mask = (attention_mask < 0.5).bool()                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by hiyouga** [comment]
更新 torch 版本

**Comment by zhaoying9105** [comment]
@hiyouga 感谢回复，我自己检查发现是没有指定 --use_v2
