### ISSUE TITLE
3090 训练大概150多步的时候，遇到：RuntimeError: Expected is_sm80 to be true, but got false，有大佬遇到过没有

### ISSUE THREAD

**Issue by camposs1979** [hiyouga/ChatGLM-Efficient-Tuning#200]

**Comment by camposs1979** [comment]
重新换了A40遇到同样的错误：
RuntimeError: Expected is_sm80 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
  3%|███▊                                                                                                                     | 157/4998 [01:59<1:01:17,  1.32it/s]

**Comment by hiyouga** [comment]
试试 pip install --force-reinstall --pre torch --index-url https://download.pytorch.org/whl/nightly/cu117

**Comment by camposs1979** [comment]
已经解决了，大神果然牛逼，一出手就解决了。感谢
