### ISSUE TITLE
训练chatglm2-int4模型报错，是命令书写有问题吗，请教大佬检查一下

### ISSUE THREAD

**Issue by shipengcheng1** [hiyouga/ChatGLM-Efficient-Tuning#201]
CUDA_VISIBLE_DEVICES=1 python src/train_sft.py  --do_train --dataset alpaca_gpt4_zh --finetuning_type lora --output_dir path_to_sft_checkpoint --per_device_train_batch_size 3 --gradient_accumulation_steps 4 --lr_scheduler_type cosine --logging_steps 10 --save_steps 1000 --learning_rate 5e-5 --num_train_epochs 3.0 --fp16 --use_v2 --model_name_or_path "/home/spc/openChat/ChatGLM-6B-main/chatglm2-6b-int4/" --quantization_bit 4

报错如下：
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/train_sft.py:105 in <module>                │
│                                                                                                  │
│   102                                                                                            │
│   103                                                                                            │
│   104 if __name__ == "__main__":                                                                 │
│ ❱ 105 │   main()                                                                                 │
│   106                                                                                            │
│                                                                                                  │
│ /home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/train_sft.py:25 in main                     │
│                                                                                                  │
│    22 │   # Prepare pretrained model and dataset                                                 │
│    23 │   model_args, data_args, training_args, finetuning_args = prepare_args(stage="sft")      │
│    24 │   dataset = prepare_data(model_args, data_args)                                          │
│ ❱  25 │   model, tokenizer = load_pretrained(model_args, finetuning_args, training_args.do_tra   │
│    26 │   dataset = preprocess_data(dataset, tokenizer, data_args, training_args, stage="sft")   │
│    27 │   data_collator = DataCollatorForChatGLM(                                                │
│    28 │   │   tokenizer=tokenizer,                                                               │
│                                                                                                  │
│ /home/spc/openChat/ChatGLM-Efficient-Tuning-main/src/utils/common.py:228 in load_pretrained      │
│                                                                                                  │
│   225 │   │   model_to_load = model_args.model_name_or_path                                      │
│   226 │                                                                                          │
│   227 │   # Load and prepare pretrained models (without valuehead).                              │
│ ❱ 228 │   model = AutoModel.from_pretrained(model_to_load, config=config, **config_kwargs)       │
│   229 │                                                                                          │
│   230 │   if model_args.use_v2:                                                                  │
│   231 │   │   def get_input_embeddings(self):                                                    │
│                                                                                                  │
│ /opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py │
│ :479 in from_pretrained                                                                          │
│                                                                                                  │
│   476 │   │   │   │   class_ref, pretrained_model_name_or_path, **hub_kwargs, **kwargs           │
│   477 │   │   │   )                                                                              │
│   478 │   │   │   _ = hub_kwargs.pop("code_revision", None)                                      │
│ ❱ 479 │   │   │   return model_class.from_pretrained(                                            │
│   480 │   │   │   │   pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs,   │
│   481 │   │   │   )                                                                              │
│   482 │   │   elif type(config) in cls._model_mapping.keys():                                    │
│                                                                                                  │
│ /opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/transformers/modeling_utils.py:2675 in   │
│ from_pretrained                                                                                  │
│                                                                                                  │
│   2672 │   │   │   init_contexts.append(init_empty_weights())                                    │
│   2673 │   │                                                                                     │
│   2674 │   │   with ContextManagers(init_contexts):                                              │
│ ❱ 2675 │   │   │   model = cls(config, *model_args, **model_kwargs)                              │
│   2676 │   │                                                                                     │
│   2677 │   │   # Check first if we are `from_pt`                                                 │
│   2678 │   │   if use_keep_in_fp32_modules:                                                      │
│                                                                                                  │
│ /root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py:772 in __init__        │
│                                                                                                  │
│    769 │   │   self.quantized = False                                                            │
│    770 │   │                                                                                     │
│    771 │   │   if self.config.quantization_bit:                                                  │
│ ❱  772 │   │   │   self.quantize(self.config.quantization_bit, empty_init=True)                  │
│    773 │                                                                                         │
│    774 │   def _update_model_kwargs_for_generation(                                              │
│    775 │   │   │   self,                                                                         │
│                                                                                                  │
│ /root/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py:1105 in quantize       │
│                                                                                                  │
│   1102 │   │                                                                                     │
│   1103 │   │   self.config.quantization_bit = bits                                               │
│   1104 │   │                                                                                     │
│ ❱ 1105 │   │   self.transformer.encoder = quantize(self.transformer.encoder, bits, empty_init=e  │
│   1106 │   │   │   │   │   │   │   │   │   │   │   **kwargs)                                     │
│   1107 │   │   return self                                                                       │
│   1108                                                                                           │
│                                                                                                  │
│ /root/.cache/huggingface/modules/transformers_modules/quantization.py:155 in quantize            │
│                                                                                                  │
│   152 def quantize(model, weight_bit_width, empty_init=False, device=None):                      │
│   153 │   """Replace fp16 linear with quantized linear"""                                        │
│   154 │   for layer in model.layers:                                                             │
│ ❱ 155 │   │   layer.self_attention.query_key_value = QuantizedLinear(                            │
│   156 │   │   │   weight_bit_width=weight_bit_width,                                             │
│   157 │   │   │   weight=layer.self_attention.query_key_value.weight.to(torch.cuda.current_dev   │
│   158 │   │   │   bias=layer.self_attention.query_key_value.bias,                                │
│                                                                                                  │
│ /root/.cache/huggingface/modules/transformers_modules/quantization.py:141 in __init__            │
│                                                                                                  │
│   138 │   │   │   if weight_bit_width == 4:                                                      │
│   139 │   │   │   │   self.weight = compress_int4_weight(self.weight)                            │
│   140 │   │                                                                                      │
│ ❱ 141 │   │   self.weight = Parameter(self.weight.to(device), requires_grad=False)               │
│   142 │   │   self.weight_scale = Parameter(self.weight_scale.to(device), requires_grad=False)   │
│   143 │   │   self.bias = Parameter(bias.to(device), requires_grad=False) if bias is not None    │
│   144                                                                                            │
│                                                                                                  │
│ /opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/torch/nn/modules/module.py:1632 in       │
│ __setattr__                                                                                      │
│                                                                                                  │
│   1629 │   │   │   │   raise AttributeError(                                                     │
│   1630 │   │   │   │   │   "cannot assign parameters before Module.__init__() call")             │
│   1631 │   │   │   remove_from(self.__dict__, self._buffers, self._modules, self._non_persisten  │
│ ❱ 1632 │   │   │   self.register_parameter(name, value)                                          │
│   1633 │   │   elif params is not None and name in params:                                       │
│   1634 │   │   │   if value is not None:                                                         │
│   1635 │   │   │   │   raise TypeError("cannot assign '{}' as parameter '{}' "                   │
│                                                                                                  │
│ /opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/accelerate/big_modeling.py:108 in        │
│ register_empty_parameter                                                                         │
│                                                                                                  │
│   105 │   │   if param is not None:                                                              │
│   106 │   │   │   param_cls = type(module._parameters[name])                                     │
│   107 │   │   │   kwargs = module._parameters[name].__dict__                                     │
│ ❱ 108 │   │   │   module._parameters[name] = param_cls(module._parameters[name].to(device), **   │
│   109 │                                                                                          │
│   110 │   def register_empty_buffer(module, name, buffer, persistent=True):                      │
│   111 │   │   old_register_buffer(module, name, buffer, persistent=persistent)                   │
│                                                                                                  │
│ /opt/anaconda3/envs/chatglm/lib/python3.8/site-packages/torch/nn/parameter.py:36 in __new__      │
│                                                                                                  │
│    33 │   │   if type(data) is torch.Tensor or type(data) is Parameter:                          │
│    34 │   │   │   # For ease of BC maintenance, keep this path for standard Tensor.              │
│    35 │   │   │   # Eventually (tm), we should change the behavior for standard Tensor to matc   │
│ ❱  36 │   │   │   return torch.Tensor._make_subclass(cls, data, requires_grad)                   │
│    37 │   │                                                                                      │
│    38 │   │   # Path for custom tensors: set a flag on the instance to indicate parameter-ness   │
│    39 │   │   t = data.detach().requires_grad_(requires_grad)                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Only Tensors of floating point and complex dtype can require gradients

**Comment by hiyouga** [comment]
不能直接加载 int4 模型训练，要先加载 fp16 原模型再使用量化参数
