### ISSUE TITLE
使用LORA微调 数据量为147条专业的对话，但是微调过后发现和没有微调前的表现一样，没有学会呢

### ISSUE THREAD

**Issue by LiZhangMing** [hiyouga/ChatGLM-Efficient-Tuning#203]

**Comment by hiyouga** [comment]
数据量太少了

**Comment by LiZhangMing** [comment]
> 数据量太少了    最少需要多少呢

不过看训练的时候 loss下降的很快到0.01了  但是验证集上loss是一直从0.41上升到0.51了。

**Comment by hiyouga** [comment]
微调后加载 checkpoint 了吗？

**Comment by LiZhangMing** [comment]
> 

加载了

**Comment by LiZhangMing** [comment]
<img width="259" alt="image" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/13574341/744b1d19-d71e-4145-9db2-c948a4578b6a">

**Comment by hiyouga** [comment]
更新到最新代码，并且试试训练集的问题是否能正确回答。

**Comment by LiZhangMing** [comment]
> 更新到最新代码，并且试试训练集的问题是否能正确回答。

今天下午6点更新的代码 还是没学到，我直接用的是训练集数据。

**Comment by hiyouga** [comment]
用 checkpoint-900 文件夹的权重试试

**Comment by LiZhangMing** [comment]
> 

好的  不过数据量 最少是多少呢  调整lora等模型

**Comment by hiyouga** [comment]
至少也要几千条

**Comment by LiZhangMing** [comment]
> 至少也要几千条

对了  我的是英文的训练集， 这个没关系吧，他会自动转token吧

**Comment by hiyouga** [comment]
和语言无关
