### ISSUE TITLE
微调前和微调后效果一样，没有学到训练数据

### ISSUE THREAD

**Issue by LiZhangMing** [hiyouga/ChatGLM-Efficient-Tuning#205]
1，使用LORA微调 数据量为147条专业的对话，但是微调过后发现和没有微调前的表现一样，没有学会呢 
2，微调后加载 checkpoint 了

训练与测试过程
1，先进行了训练微调   如下所示
CUDA_VISIBLE_DEVICES=4,5  accelerate launch  train_sft.py   --model_name_or_path "THUDM/chatglm2-6b"  --use_v2   --do_train  --dataset electric  --dataset_dir ../data   --finetuning_type lora  --output_dir path_to_sft_checkpoint   --overwrite_cache   --per_device_train_batch_size 1     --gradient_accumulation_steps 4  --per_device_eval_batch_size 1 --evaluation_strategy steps   --lr_scheduler_type cosine    --logging_steps 10   --save_strategy steps   --eval_steps 100   --save_steps 100   --warmup_steps 0  --learning_rate  0.0006    --num_train_epochs 60.0   --dev_ratio 0.1   --load_best_model_at_end   --plot_loss   --fp16

2， 然后是 测试 python src/cli_demo.py   --checkpoint_dir src/path_to_sft_checkpoint

<img width="259" alt="image" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/13574341/744b1d19-d71e-4145-9db2-c948a4578b6a">

**Comment by hiyouga** [comment]
https://github.com/hiyouga/ChatGLM-Efficient-Tuning/issues/203

**Comment by fslongjin** [comment]
这个我也遇到了，数据量少的话，增大rank以及epoch可以解决
