### ISSUE TITLE
应该是cli_demo.py有点问题

### ISSUE THREAD

**Issue by LiZhangMing** [hiyouga/ChatGLM-Efficient-Tuning#206]
### 现象描述
我的训练集现在只是有一条数据，就是who are you。我将它训练了120轮，并且在执行预测的时候表现如下
<img width="979" alt="image" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/13574341/e13108ad-5916-406d-a723-6dff28d7223a">

### 然后执行   python src/cli_demo.py  --checkpoint_dir   examples/new_path_one/checkpoint-80/   这个代码
<img width="996" alt="image" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/13574341/7a7fece5-15c1-4639-adb1-a4ee1b909148">
然后他的回答和预测的时候完全不一样。

这个是终端的回答
<img width="1000" alt="image" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/13574341/4d0e52e6-3cf3-45d2-8244-5b8c9595d798">

这个是他的预测
<img width="882" alt="image" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/13574341/a61aa1eb-67bb-4de1-a165-ff8426367fba">

**Comment by hiyouga** [comment]
我在本地复现了修改自我认知的实验，在 ChatGLM-6B 和 ChatGLM2-6B 上均通过了验证，请参考本项目提供的案例。

**Comment by LiZhangMing** [comment]
> 我在本地复现了修改自我认知的实验，在 ChatGLM-6B 和 ChatGLM2-6B 上均通过了验证，请参考本项目提供的案例。


### 我是按照您给的案例操作的，将example_dataset拷贝了一份出来，然后改了下。结果就是我上面发现的问题
<img width="1352" alt="image" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/13574341/d7be7916-22c6-424e-92b9-b42d201908d0">

**Comment by hiyouga** [comment]
cli 预测可能有随机性，多试几次
