### ISSUE TITLE
多卡微调打开evaluation报错

### ISSUE THREAD

**Issue by yifan-chen-2020** [hiyouga/ChatGLM-Efficient-Tuning#213]
尝试了#163 里的解决方案，train()时候加入autocast，loss不会下降，一直在2.x。

如果不加入则多卡不能跑evaluation，会报和这个issue一样的错？

好奇作者的多卡测试是怎么跑通的，硬件环境a100，参数和这个issue提到的一致（除了数据集的地址）
```
# loss一直在2.x无法下降
with torch.autocast("cuda"):        
        train_result = trainer.train()
        trainer.log_metrics("train", train_result.metrics)
        trainer.save_metrics("train", train_result.metrics)
        trainer.save_state()
        trainer.save_model()
        if trainer.is_world_process_zero() and model_args.plot_loss:
            plot_loss(training_args.output_dir, keys=["loss", "eval_loss"])
```

**Comment by hiyouga** [comment]
多卡时候打开 evaluation 确实会报错。
你可以尝试一下这个解决方案：
https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/4c5717cb2c511a34a46e6ea6514d07c4c3cfe60c/src/utils/common.py#L248
1. 在 _init_adapater 前面加一句 model = model.half()
2. 然后训练时不添加 fp16 参数

**Comment by yifan-chen-2020** [comment]
> 多卡时候打开 evaluation 确实会报错。 你可以去掉之前的 autocast，尝试一下这个解决方案：
> 
> https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/4c5717cb2c511a34a46e6ea6514d07c4c3cfe60c/src/utils/common.py#L248
> 
> 1. 在 _init_adapater 前面加一句 model = model.half()
> 2. 然后训练时不添加 fp16 参数

试了下确实跑起来没有error，但看起来指标不太对，我先检查问题在哪...和我之前用另一个开源repo调的结果差距很大

**Comment by yifan-chen-2020** [comment]
这个issue先close吧，看起来改了后指标和单卡能对上，应该解决了这个问题本身，只是可能存在其他数据处理的问题导致我的指标低
