### ISSUE TITLE
微调chatglm2-6b报错

### ISSUE THREAD

**Issue by yichuan1998** [hiyouga/ChatGLM-Efficient-Tuning#216]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/91551667/3e1a600a-0ed5-41da-a4e5-facd8c52eda2)
sh：
CUDA_VISIBLE_DEVICES=0 python src/train_sft.py \
    --do_train \
    --dataset alpaca_gpt4_en \
    --finetuning_type lora \
    --output_dir /data/jupyter/LLM/models/chatglm2-6b \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --fp16
python3.10，cuda12，torch2.0
没搞懂，trl没有大于0.4.1的版本啊，求助
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/91551667/8dcfe726-4990-4a5a-9ea9-1653c719c97d)

**Comment by hiyouga** [comment]
用阿里的镜像源

**Comment by yichuan1998** [comment]
> 用阿里的镜像源

已解决

**Comment by chenkejin** [comment]
怎么解决的
