### ISSUE TITLE
段错误 吐核

### ISSUE THREAD

**Issue by chenxw321** [hiyouga/ChatGLM-Efficient-Tuning#217]

**Comment by chenxw321** [comment]
.sh
CUDA_VISIBLE_DEVICES=0 python3 train_sft.py \
    --do_train \
    --dataset train,dev \
    --dataset_dir data/car \
    --finetuning_type lora \
    --output_dir car/sft \
    --overwrite_cache \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 8 \
    --max_source_length 128 \
    --max_target_length 512 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 100 \
    --eval_steps 100 \
    --learning_rate 5e-5 \
    --num_train_epochs 10.0 \
    --dev_ratio 0.085 \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --plot_loss \
    --fp16

**Comment by chenxw321** [comment]
<img width="605" alt="企业微信截图_e88cdfa4-a1bd-4c15-9c8d-36da6fbd5f9f" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/125811027/1a4f7804-9f81-4e2e-b322-c5c18f7f449e">

**Comment by hiyouga** [comment]
没听懂。

**Comment by chenxw321** [comment]
执行bash train_sft.sh 报错 
<img width="745" alt="企业微信截图_30e35838-4fe0-4571-a5ed-a3f9944f05ed" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/125811027/3579c39f-91b2-4a00-a201-6c9a88e8600d">
