### ISSUE TITLE
莫名的出错

### ISSUE THREAD

**Issue by chenxw321** [hiyouga/ChatGLM-Efficient-Tuning#218]
执行bash train_sft.sh 报错 
<img width="745" alt="企业微信截图_30e35838-4fe0-4571-a5ed-a3f9944f05ed" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/125811027/3579c39f-91b2-4a00-a201-6c9a88e8600d">

_Originally posted by @chenxw321 in https://github.com/hiyouga/ChatGLM-Efficient-Tuning/issues/217#issuecomment-1612911197_

**Comment by chenxw321** [comment]
train_sft.sh
CUDA_VISIBLE_DEVICES=0 python3 train_sft.py
--do_train
--dataset train,dev
--dataset_dir data/car
--finetuning_type lora
--output_dir car/sft
--overwrite_cache
--per_device_train_batch_size 4
--per_device_eval_batch_size 4
--gradient_accumulation_steps 8
--max_source_length 128
--max_target_length 512
--lr_scheduler_type cosine
--logging_steps 10
--save_steps 100
--eval_steps 100
--learning_rate 5e-5
--num_train_epochs 10.0
--dev_ratio 0.085
--evaluation_strategy steps
--load_best_model_at_end
--plot_loss
--fp16

**Comment by 70557dzqc** [comment]
没斜杠

**Comment by chenxw321** [comment]
加斜杠 也不行 同样的错误

**Comment by chenxw321** [comment]
配置环境的问题，不是Python3.10
