### ISSUE TITLE
/data/example_dataset /examples.json中input和instruction字段有什么区别？

### ISSUE THREAD

**Issue by xyfZzz** [hiyouga/ChatGLM-Efficient-Tuning#219]
请问/data/example_dataset /examples.json中input和instruction字段有什么区别？
什么时候填在input中，什么时候填在instruction中呢？

**Comment by hiyouga** [comment]
没区别。训练时候会拼到一起

**Comment by xyfZzz** [comment]
> 没区别。训练时候会拼到一起

那input和instruction的字段内容在拼接训练数据的时候，拼接在它们前面的用来区分role的tag（比如user和system）是一样的吗？

**Comment by hiyouga** [comment]
User: <instruction>\n<input> Assistant: <output>

**Comment by xyfZzz** [comment]
> User: [instruction]\n[input] Assistant: [output]

好的，感谢！
