### ISSUE TITLE
导出模型报错

### ISSUE THREAD

**Issue by ZTurboX** [hiyouga/ChatGLM-Efficient-Tuning#221]
export_model导出模型报错  'ChatGLMTokenizer' object has no attribute 'vocab_file'

**Comment by hiyouga** [comment]
从清华的 huggingface 更新一下模型目录里面的几个 json 和 py 文件

**Comment by zhangfan-algo** [comment]
我也报了同样的错 需要更新哪些文件呢

**Comment by hiyouga** [comment]
@zhangfan-algo json 和 py 后缀的文件
