### ISSUE TITLE
微调chatglm2报错

### ISSUE THREAD

**Issue by xyfZzz** [hiyouga/ChatGLM-Efficient-Tuning#222]
请大佬帮忙看下：

│ /app/xie/code/ChatGLM-Efficient-Tuning/src/train_sft.py:105 in <module>      │
│                                                                              │
│   102                                                                        │
│   103                                                                        │
│   104 if __name__ == "__main__":                                             │
│ ❱ 105 │   main()                                                             │
│   106                                                                        │
│                                                                              │
│ /app/xie/code/ChatGLM-Efficient-Tuning/src/train_sft.py:73 in main           │
│                                                                              │
│    70 │                                                                      │
│    71 │   # Training                                                         │
│    72 │   if training_args.do_train:                                         │
│ ❱  73 │   │   train_result = trainer.train()                                 │
│    74 │   │   trainer.log_metrics("train", train_result.metrics)             │
│    75 │   │   trainer.save_metrics("train", train_result.metrics)            │
│    76 │   │   trainer.save_state()                                           │
│                                                                              │ 
│ /app/apps/anaconda3/envs//lib/python3.9/site-packages/transformers/train │ 
│ er.py:1537 in train                                                          │
│                                                                              │
│   1534 │   │   inner_training_loop = find_executable_batch_size(             │
│   1535 │   │   │   self._inner_training_loop, self._train_batch_size, args.a │
│   1536 │   │   )                                                             │
│ ❱ 1537 │   │   return inner_training_loop(                                   │
│   1538 │   │   │   args=args,                                                │
│   1539 │   │   │   resume_from_checkpoint=resume_from_checkpoint,            │
│   1540 │   │   │   trial=trial,                                              │
│                                                                              │
│ /app/apps/anaconda3/envs//lib/python3.9/site-packages/transformers/train │
│ er.py:1860 in _inner_training_loop                                           │
│                                                                              │
│   1857 │   │   │   │   │   │   │   │   args.max_grad_norm,                   │ 
│   1858 │   │   │   │   │   │   │   )                                         │ 
│   1859 │   │   │   │   │   │   else:                                         │
│ ❱ 1860 │   │   │   │   │   │   │   self.accelerator.clip_grad_norm_(         │
│   1861 │   │   │   │   │   │   │   │   model.parameters(),                   │
│   1862 │   │   │   │   │   │   │   │   args.max_grad_norm,                   │
│   1863 │   │   │   │   │   │   │   )                                         │
│                                                                              │
│ /app/apps/anaconda3/envs//lib/python3.9/site-packages/accelerate/acceler │
│ ator.py:1908 in clip_grad_norm_                                              │
│                                                                              │
│   1905 │   │   │   # `accelerator.backward(loss)` is doing that automaticall │
│   1906 │   │   │   # We cannot return the gradient norm because DeepSpeed do │
│   1907 │   │   │   return None                                               │
│ ❱ 1908 │   │   self.unscale_gradients()                                      │
│   1909 │   │   return torch.nn.utils.clip_grad_norm_(parameters, max_norm, n │
│   1910 │                                                                     │
│   1911 │   def clip_grad_value_(self, parameters, clip_value):               │
│                                                                              │
│ /app/apps/anaconda3/envs//lib/python3.9/site-packages/accelerate/acceler │
│ ator.py:1871 in unscale_gradients                                            │
│                                                                              │
│   1868 │   │   │   for opt in optimizer:                                     │
│   1869 │   │   │   │   while isinstance(opt, AcceleratedOptimizer):          │
│   1870 │   │   │   │   │   opt = opt.optimizer                               │
│ ❱ 1871 │   │   │   │   self.scaler.unscale_(opt)                             │
│   1872 │                                                                     │
│   1873 │   def clip_grad_norm_(self, parameters, max_norm, norm_type=2):     │
│   1874 │   │   """                                                           │
│                                                                              │
│ /app/apps/anaconda3/envs//lib/python3.9/site-packages/torch/cuda/amp/gra │
│ d_scaler.py:275 in unscale_                                                  │
│                                                                              │
│   272 │   │   optimizer_state = self._per_optimizer_states[id(optimizer)]    │
│   273 │   │                                                                  │
│   274 │   │   if optimizer_state["stage"] is OptState.UNSCALED:              │
│ ❱ 275 │   │   │   raise RuntimeError("unscale_() has already been called on  │
│   276 │   │   elif optimizer_state["stage"] is OptState.STEPPED:             │
│   277 │   │   │   raise RuntimeError("unscale_() is being called after step( │
│   278                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: unscale_() has already been called on this optimizer since the 
last update(). 
 34%|███▎      | 114/339 [05:51<11:33,  3.08s/it]

**Comment by hiyouga** [comment]
更新 peft 库版本

**Comment by xyfZzz** [comment]
> 更新 peft 库版本

更新peft版本无法解决，根据https://github.com/hiyouga/ChatGLM-Efficient-Tuning/issues/175中的解决办法进行了解决
