### ISSUE TITLE
chatglm2-6b微调报错

### ISSUE THREAD

**Issue by feymanwang** [hiyouga/ChatGLM-Efficient-Tuning#224]
错误信息如下：
assert tokenizer.eos_token_id is not None, "Please update the *.json and *.py files of ChatGLM2-6B from HuggingFace."

这句话怎么理解呢，是要去HF上重新下载 json和py文件？

**Comment by dragononly** [comment]
同样错误

**Comment by hiyouga** [comment]
字面意思。

**Comment by yumulinfeng1** [comment]
> 字面意思。

去HG上重新下载json和py文件依然报错
   assert tokenizer.eos_token_id is not None, "Please update the *.json and *.py files of ChatGLM2-6B from HuggingFace."
AssertionError: Please update the *.json and *.py files of ChatGLM2-6B from HuggingFace.
