### ISSUE TITLE
请问单卡4090能否全参数finetuneChatGLM2的模型？

### ISSUE THREAD

**Issue by Lufffya** [hiyouga/ChatGLM-Efficient-Tuning#227]

**Comment by CCzzzzzzz** [comment]
单卡只能peft

**Comment by hiyouga** [comment]
不能

**Comment by zhohn0** [comment]
理论结合测试得到的结论是不能，
60亿规模参数，根据以下公式计算：
模型参数 + 梯度参数 + 优化器参数 = 6B * 1bytes + 6GB + 2*6GB = 24GB

**Comment by HaKLMTT** [comment]
> 理论结合测试得到的结论是不能， 60亿规模参数，根据以下公式计算： 模型参数 + 梯度参数 + 优化器参数 = 6B * 1bytes + 6GB + 2*6GB = 24GB

请问梯度参数和优化器参数占用空间，是如何估算的？
