### ISSUE TITLE
微调后使用export_model.py 导出ChatGLM2模型错误

### ISSUE THREAD

**Issue by exceedzhang** [hiyouga/ChatGLM-Efficient-Tuning#229]
python src/export_model.py --model_name_or_path /root/chatglm2-6b/      --checkpoint_dir cognition     --output_dir /root/auto-tmp/chatglm2-6b/ --use_v2

<img width="1182" alt="image" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/4583537/1338a99d-8b1e-40b2-b908-6f79c67186eb">

**Comment by exceedzhang** [comment]
pytorch版本使用最新2.1.0 cuda driver 11.8版本

**Comment by hiyouga** [comment]
存储满了？

**Comment by exceedzhang** [comment]
参数搞错了，模型已成功合并并保持！

**Comment by chenkejin** [comment]
最后参数最后用的什么
