### ISSUE TITLE
RM 训练完成后rm文件夹下没有权重文件

### ISSUE THREAD

**Issue by chenxw321** [hiyouga/ChatGLM-Efficient-Tuning#233]
![企业微信截图_103c1903-f58e-467c-a371-f875a2dc8304](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/125811027/170edcfa-7948-4ac7-a5f3-989534e4fb32)
在ppo训练时 要选择checkpoint 里边的，怎么确定是最优的呢？

**Comment by hiyouga** [comment]
脚本没有运行完吧？

**Comment by chenxw321** [comment]
脚本运行完了，我在检查一下

**Comment by chenxw321** [comment]
重新运行后，发现中间过程内存溢出，停止了，更改参数后，问题解决
