### ISSUE TITLE
微调时报错了，能帮我看下吗

### ISSUE THREAD

**Issue by jeffreychen567** [hiyouga/ChatGLM-Efficient-Tuning#24]
ImportError: cannot import name 'WEIGHTS_NAME' from 'peft.utils.other' (/root/miniconda3/lib/python3.10/site-packages/peft/utils/other.py)
./finetune.sh: line 7: --dataset: command not found

**Comment by hiyouga** [comment]
麻烦把 finetune.sh 完整内容发一下

**Comment by hiyouga** [comment]
PEFT 版本过旧，请使用以下命令升级。
```bash
pip uninstall peft
pip install git+https://hub.nuaa.cf/huggingface/peft.git
```
