### ISSUE TITLE
请问有没有chatglm2继续预训练的代码啊

### ISSUE THREAD

**Issue by ray075hl** [hiyouga/ChatGLM-Efficient-Tuning#245]
我看了一下glm的代码，好像不是完全自回归的方式，是多种mask的组合，而且specail token和chatglm2的也对不上啊，求大佬指导

**Comment by HaKLMTT** [comment]
> 我看了一下glm的代码，好像不是完全自回归的方式，是多种mask的组合，而且specail token和chatglm2的也对不上啊，求大佬指导

前几天问过，目前不支持chatgml2继续预训练

**Comment by ray075hl** [comment]
@HaKLMTT 收到，感谢回复

**Comment by hiyouga** [comment]
目前不支持，近期内不会实现

**Comment by ray075hl** [comment]
@hiyouga 好的，么么哒
