### ISSUE TITLE
glm2训练完测试发现重复生成的情况比较严重

### ISSUE THREAD

**Issue by xyfZzz** [hiyouga/ChatGLM-Efficient-Tuning#247]
glm2训练完测试发现重复生成的情况比较严重，请问有什么好的解决办法吗？

已知条件：
1、更新过glm2模型的py文件。
2、使用了1800条左右数据，epoch和学习率均为默认，使用web_demo.py进行测试。

**Comment by hiyouga** [comment]
可能和数据质量有关。

**Comment by 1042280163** [comment]
我也遇到这种问题了，chatglm2lora微调后，在生成比较长的文本时会发生一直重复生成的现象，而且指令微调没有涉及到的问题，微调前能正常生成，微调后也发生重复生成的现象了

**Comment by qinqinqaq** [comment]
我也遇到这种问题了

**Comment by Yang-HangWA** [comment]
mark一下，遇到不停输出同样回答+1

**Comment by LotuSrc** [comment]
mark

**Comment by koalasix-sky** [comment]
mark

**Comment by yancongwen** [comment]
mark

**Comment by caixiaomao** [comment]
同样的问题

**Comment by dfsong** [comment]
我这边也遇到了

**Comment by codemayq** [comment]
需要大家提供一下训练更详细的设置，比如当时完整的 训练命令和测试命令，关键是需要了解训练的方式（lora等），是否量化等
