### ISSUE TITLE
full tuning  显存不足

### ISSUE THREAD

**Issue by chenkejin** [hiyouga/ChatGLM-Efficient-Tuning#248]
4卡训练，在vicuna、baichuan都可以正常训练，但是chatglm2显存不足，max-length调到128以及batch size=1 还是不行

**Comment by hiyouga** [comment]
ChatGLM 对 ZeRO-3 的兼容性比较差。全量微调需要启用 ZeRO-2 并在 A100 80G * 3 上进行训练

**Comment by mao-ym** [comment]
> O-2 并在 A100 80G * 3 上进行训练

您好，我使用的您在example中的accelerate_config.yaml文件，我看里面设置的是用的ZeRO-2，GPU用的80G*4，训练参数如下
 accelerate launch --config_file accelerate_config.yaml ../src/train_sft.py \
     --do_train \
     --use_v2 \
     --finetuning_type full \
     --max_source_length 512 \
     --max_target_length 128 \
     --per_device_train_batch_size 1 \
     --gradient_accumulation_steps 8 \
      --lr_scheduler_type cosine \
     --logging_steps 10 \
     --save_steps 1000 \
     --learning_rate 5e-5 \
     --num_train_epochs 3.0 \
     --fp16 

这样还是会报OOM的错
