### ISSUE TITLE
chatglm和chatglm2微调时的区别

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [hiyouga/ChatGLM-Efficient-Tuning#249]
https://openi.pcl.ac.cn/kewei/ChatGLM-6B/src/branch/main/lora/main-secret-new.ipynb
上面这个notebook对于v1的微调有很好的效果
但是我将其用在v2上，效果欠佳

![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/84905965/787e0ac1-3b36-438e-8a1a-7bcc9e12c449)
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/84905965/fae269e8-c6a8-43be-bc40-efb5f75449c1)
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/84905965/341c18b1-22b6-4f23-9b38-790411662593)

很多参数变成了none
想请教一下，这些参数出现了怎样的变化？https://openi.pcl.ac.cn/kewei/ChatGLM-6B/src/branch/main/lora/main-secret-new.ipynb 这个notebook对v2需要进行怎样的适配？

**Comment by hiyouga** [comment]
我们对 v2 的特殊处理如下：https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/3a53dd404bec2831d93fd55f516f604f7993dfbb/src/utils/common.py#L228-L232

**Comment by Ethan-Chen-plus** [comment]
@hiyouga 非常感谢！想请问一下gmask = tokenizer.sp_tokenizer[tokenizer.gMASK_token]这个参数是已经停用了么？

**Comment by Ethan-Chen-plus** [comment]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/84905965/48ff99a1-d6a4-428f-8554-6ea5e848ef4d)
如果没有了gmask，代码中此处这个gmask应该 如何设置？
