### ISSUE TITLE
Using Accelerate train

### ISSUE THREAD

**Issue by www516717402** [hiyouga/ChatGLM-Efficient-Tuning#25]
Thank you for open this repo.
In example for DDP train:
```bash
accelerate config # configure the environment
accelerate launch src/finetune.py # arguments (same as above)
```
However. No accelerate library found in your repo.
``` python
+ from accelerate import Accelerator
+ accelerator = Accelerator()

+ model, optimizer, training_dataloader, scheduler = accelerator.prepare(
+     model, optimizer, training_dataloader, scheduler
+ )
...
```

**Comment by hiyouga** [comment]
These features are already integrated with the Trainer class. We do not need to specify them in the scripts.
https://huggingface.co/docs/transformers/main_classes/trainer#specific-gpus-selection

**Comment by www516717402** [comment]
Thank you for your reponse.
