### ISSUE TITLE
AttributeError: can't set attribute 'eos_token'  在跑评估代码出现了报错

### ISSUE THREAD

**Issue by zhangfan-algo** [hiyouga/ChatGLM-Efficient-Tuning#250]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/47747764/64e982c8-9bfa-4677-b949-90f2465e5b73)

**Comment by zhangfan-algo** [comment]
想问下 这个bug改怎么解决一下呢

**Comment by zhangfan-algo** [comment]
torchrun  --nproc_per_node ${num_gpu_per_node}  --master_port ${master_port} --master_addr ${master_addr} --node_rank ${node_rank} --rdzv_backend=c10d --rdzv_endpoint=$master_addr src/train_sft.py \
    --do_eval \
    --dataset alpaca_gpt4_en \
    --model_name_or_path /apps1/zhangfan/ChatGLM-Efficient-Tuning/fintune_model/chatglm2-0627 \
    --output_dir /apps1/zhangfan/ChatGLM-Efficient-Tuning/eval_result \
    --per_device_eval_batch_size 10 \
    --max_samples 100 \
    --predict_with_generate

**Comment by zhangfan-algo** [comment]
这是我的脚本

**Comment by zzzhaoguziji** [comment]
> 想问下 这个bug改怎么解决一下
是不是可以删了这个报错代码，
![微信截图_20230705113721](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/38344228/1a7cd66b-cb42-4a25-9e30-509d1723c956)

**Comment by hiyouga** [comment]
更新一下代码，版本太老了
