### ISSUE TITLE
[疑问]2-6B模型在LoRA微调模式下，基于self_cognition.json文件进行微调，模型测试时候没有任何反应的问题

### ISSUE THREAD

**Issue by SniperM99** [hiyouga/ChatGLM-Efficient-Tuning#253]
2-6B模型在LoRA微调模式下，基于self_cognition.json文件进行微调，模型测试时候没有任何反应的问题！
但是6-b模型采用以上相同方法，就没有发生任何问题！

作者是否对2-6b进行过小样本的微调测试？

**Comment by hiyouga** [comment]
用这个尝试了吗？https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/examples/alter_cog_chatglm2.sh

**Comment by SniperM99** [comment]
> 用这个尝试了吗？https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/examples/alter_cog_chatglm2.sh

测试通过，可以使用

需要注意的是：在微调后的模型调度上，没有输出模型之前，需要用一下命令记性调度
```
CUDA_VISIBLE_DEVICES=0 python src/cli_demo.py \
    --model_name_or_path /home/xxz/models/chatglm2-6b \
    --use_v2 \
    --checkpoint_dir path_to_sft_checkpoint 
```
