### ISSUE TITLE
大佬你好，请问通过lora训练方式得到的文件夹如何通过transformers的方式加载到模型中

### ISSUE THREAD

**Issue by forgot-glory** [hiyouga/ChatGLM-Efficient-Tuning#26]
得到的文件：
![image](https://user-images.githubusercontent.com/35793823/234249418-13db80b9-2bbd-429d-8d6c-67afebaf4206.png)
想要加载的位置（类似）：
config = AutoConfig.from_pretrained("chatglm-6b", trust_remote_code=True, pre_seq_len=128)
model = AutoModel.from_pretrained("chatglm-6b", config=config, trust_remote_code=True).half().cuda()

**Comment by hiyouga** [comment]
为了避免每次训练得到的微调模型都占用8GB以上的硬盘空间，我们只保存了 LoRA 权重，我们推荐使用项目中[自带的部署方式](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/README_zh.md#%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)来加载 transformers 模型。
如果想要保存 LoRA 微调后的模型，可以写个类似下面的脚本导出全部模型：
```python
import sys
sys.path.append("src")
from src import load_pretrained, ModelArguments

if __name__ == "__main__":
    model_args = ModelArguments(checkpoint_dir="path_to_lora_checkpoint")
    model, tokenizer = load_pretrained(model_args)
    model.base_model.model.save_pretrained("path_to_save_model")
```
然后你可以使用
```python
config = AutoConfig.from_pretrained("path_to_save_model", trust_remote_code=True, pre_seq_len=128)
model = AutoModel.from_pretrained("path_to_save_model", config=config, trust_remote_code=True).half().cuda()
```
加载微调后的模型。

**Comment by forgot-glory** [comment]
> 为了避免每次训练得到的微调模型都占用8GB以上的硬盘空间，我们只保存了 LoRA 权重，我们推荐使用项目中[自带的部署方式](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/README_zh.md#%E6%A8%A1%E5%9E%8B%E9%83%A8%E7%BD%B2)来加载 transformers 模型。 如果想要保存 LoRA 微调后的模型，可以写个类似下面的脚本导出全部模型：
> 
> ```python
> import sys
> sys.path.append("src")
> from src import load_pretrained, ModelArguments
> 
> if __name__ == "__main__":
>     model_args = ModelArguments(checkpoint_dir="path_to_lora_checkpoint")
>     model, tokenizer = load_pretrained(model_args)
>     model.base_model.model.save_pretrained("path_to_save_model")
> ```
> 
> 然后你可以使用
> 
> ```python
> config = AutoConfig.from_pretrained("path_to_save_model", trust_remote_code=True, pre_seq_len=128)
> model = AutoModel.from_pretrained("path_to_save_model", config=config, trust_remote_code=True).half().cuda()
> ```
> 
> 加载微调后的模型。

感谢大佬脚本的帮助！这使我成功地导出了模型与权重的合并文件。但在加载模型的时候，出现了错误：
ValueError: Unrecognized configuration class <class 'transformers_modules.lora_model.configuration_chatglm.ChatGLMConfig'> to build an AutoTokenizer. Model type should be one of AlbertConfig, AlignConfig, BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BlipConfig, Blip2Config, BloomConfig, BridgeTowerConfig, CamembertConfig, CanineConfig, ChineseCLIPConfig, ClapConfig, CLIPConfig, CLIPSegConfig, CodeGenConfig, ConvBertConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, DPRConfig, ElectraConfig, ErnieConfig, ErnieMConfig, EsmConfig, FlaubertConfig, FNetConfig, FSMTConfig, FunnelConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, GPTSanJapaneseConfig, GroupViTConfig, HubertConfig, IBertConfig, JukeboxConfig, LayoutLMConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LlamaConfig, LongformerConfig, LongT5Config, LukeConfig, LxmertConfig, M2M100Config, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MgpstrConfig, MobileBertConfig, MPNetConfig, MT5Config, MvpConfig, NezhaConfig, NllbMoeConfig, NystromformerConfig, OneFormerConfig, OpenAIGPTConfig, OPTConfig, OwlViTConfig, PegasusConfig, PegasusXConfig, PerceiverConfig, Pix2StructConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, RagConfig, RealmConfig, ReformerConfig, RemBertConfig, RetriBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, Speech2TextConfig, Speech2Text2Config, SpeechT5Config, SplinterConfig, SqueezeBertConfig, SwitchTransformersConfig, T5Config, TapasConfig, TransfoXLConfig, ViltConfig, VisualBertConfig, Wav2Vec2Config, Wav2Vec2ConformerConfig, WhisperConfig, XCLIPConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.

我加载模型的完整代码如下：
@st.cache_resource
def get_model():
    tokenizer = AutoTokenizer.from_pretrained("/root/lora_model", trust_remote_code=True)
    config = AutoConfig.from_pretrained("/root/lora_model", trust_remote_code=True)
    model = AutoModel.from_pretrained("/root/lora_model", config=config, trust_remote_code=True).half().cuda()
    model = model.eval()
    return tokenizer, model
其中/root/lora_model是使用脚本导出的文件夹。
非常希望您能给予帮助，谢谢！

**Comment by hiyouga** [comment]
@forgot-glory 忘记保存 Tokenizer 了
```python
import sys
sys.path.append("src")
from src import load_pretrained, ModelArguments

if __name__ == "__main__":
    model_args = ModelArguments(checkpoint_dir="path_to_lora_checkpoint")
    model, tokenizer = load_pretrained(model_args)
    model.base_model.model.save_pretrained("path_to_save_model")
    tokenizer.save_pretrained("path_to_save_model") # 保存 Tokenizer
```

**Comment by forgot-glory** [comment]
非常感谢您的回复，这对我帮助很大

**Comment by jimmy-kuo** [comment]
采用融合lora之后的模型，加载时报了如下错误，谁能帮忙看看原因呀：
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/5310450/f5bb5ad0-b4f7-4a96-8643-5e4ef49eeb3b)

**Comment by hiyouga** [comment]
@jimmy-kuo 这个应该是 warning 而不是 error 吧，可以不理会。

**Comment by zzzhaoguziji** [comment]
@hiyouga 大佬您好，我加载融合后保存的模型，也报了警告，但是这个警告是lora训练权重没有加载，导致模型效果很差，这该怎么办呢？

**Comment by hiyouga** [comment]
@zzzhaoguziji 请使用 https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/examples/export_lora_model.py

**Comment by yanshuaibupt** [comment]
load_pretrained代码已更改，现在需要传入两个参数：
model_args = ModelArguments(checkpoint_dir=path_to_checkpoint)
finetuning_args = FinetuningArguments()
model, tokenizer = load_pretrained(model_args, finetuning_args)

**Comment by Sberm** [comment]
现在似乎使用src/export_model.py就可以导出了?
