### ISSUE TITLE
Lora训练，训练期间评估阶段出现RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by mmbwf** [hiyouga/ChatGLM-Efficient-Tuning#261]
多卡训练lora，trainer训练期间loss正常下降，评估阶段出现RuntimeError: expected scalar type Half but found Float，
参考之前issue添加 with torch.autocast("cuda")，训练loss一直处于震荡状态。

**Comment by mmbwf** [comment]
参考 #231 已解决。

**Comment by mmbwf** [comment]
参考 #213 已解决。

**Comment by hiyouga** [comment]
是用加 .half() 的方法解决的吗？

**Comment by mmbwf** [comment]
> 是用加 .half() 的方法解决的吗？

是的，加.half()，不用--fp16。
