### ISSUE TITLE
attention_mask和position_id的一些问题

### ISSUE THREAD

**Issue by lhzwangwei** [hiyouga/ChatGLM-Efficient-Tuning#263]
你好，按照代码中的get_attention_masks_v2的做法，这不就完全是一个self-attention么 这么做有什么依据么 跟v1的attention差别好大啊

**Comment by hiyouga** [comment]
我是按照官方代码编写的，ChatGLM2-6B 在指令微调阶段采用了 Casual decoder-only 的方式[1]。

[1] https://huggingface.co/THUDM/chatglm2-6b/blob/0ecfe0b857efd00836a4851b3dd2ed04bd4b197f/tokenization_chatglm.py#L192

**Comment by lhzwangwei** [comment]
哦哦，好的，我看了看，这跟v1差别好大啊，v1我记得是专门写到chatglm.py了，v2这么简单就，这不就完全放弃了他的glm了么 大佬你觉得呢
