### ISSUE TITLE
想咨询一下微调过程中断后（主动中断），是否可以继续进度训练？

### ISSUE THREAD

**Issue by show88118** [hiyouga/ChatGLM-Efficient-Tuning#264]
去掉overwrite_cache这个参数？

**Comment by hiyouga** [comment]
--checkpoint_dir 指向断点权重文件夹

**Comment by show88118** [comment]
> --checkpoint_dir 指向断点权重文件夹

多谢大佬指点

**Comment by show88118** [comment]
> checkpoint_dir

打扰一下，配了--checkpoint_dir，还是报错
AssertionError: Provided path (docsetp) does not contain a LoRA weight.

**Comment by show88118** [comment]
> > checkpoint_dir
> 
> 打扰一下，配了--checkpoint_dir，还是报错 AssertionError: Provided path (docsetp) does not contain a LoRA weight.

checkpoint-1000  checkpoint-3000  checkpoint-5000  checkpoint-7000  checkpoint-9000
checkpoint-2000  checkpoint-4000  checkpoint-6000  checkpoint-8000  trainer_log.jsonl
目录下有这些文件了

**Comment by show88118** [comment]
> > > checkpoint_dir
> > 
> > 
> > 打扰一下，配了--checkpoint_dir，还是报错 AssertionError: Provided path (docsetp) does not contain a LoRA weight.
> 
> checkpoint-1000 checkpoint-3000 checkpoint-5000 checkpoint-7000 checkpoint-9000 checkpoint-2000 checkpoint-4000 checkpoint-6000 checkpoint-8000 trainer_log.jsonl 目录下有这些文件了

知道原因了，配错路径了
