### ISSUE TITLE
使用lora微调，增加--resume_lora_training、--checkpoint_dir后，感觉没有继续训练，epoch还是从头跑了

### ISSUE THREAD

**Issue by show88118** [hiyouga/ChatGLM-Efficient-Tuning#265]
07/07/2023 21:02:25 - INFO - utils.common - Fine-tuning method: LoRA./docsetp/checkpoint-8000/adapter_model.bin 07/07/2023 21:02:34 - INFO - utils.common - Loaded fine-tuned model from checkpoint(s): ./docsetp/checkpoint-8000

**Comment by hiyouga** [comment]
只能继承权重，不能继承训练进度，请手动减少 epoch 数量

**Comment by show88118** [comment]
> 只能继承权重，不能继承训练进度，请手动减少 epoch 数量

明白了，多谢回答

**Comment by YinSonglin1997** [comment]
借楼问一下是不是p_tuning微调中途断开后，也能通过--resume_p_tuning_training 继续训练？

**Comment by hiyouga** [comment]
@YinSonglin1997 重点是 --checkpoint_dir 参数，而不是那个参数
