### ISSUE TITLE
训练后loss先上下波动，然后突然变成0

### ISSUE THREAD

**Issue by mininggold007** [hiyouga/ChatGLM-Efficient-Tuning#267]
我用/examples/alter_cog_chatglm2.sh 这个模板，采用修改成了数据集合：alpaca_data_zh_51k.json，alpaca_gpt4_data_zh.json，comparison_gpt4_data_zh.json。

loss先在2左右上下波动，然后突然变成0，后面一直保持为0，应该是出问题了吧。

**Comment by hiyouga** [comment]
学习率太大了

**Comment by mininggold007** [comment]
谢谢
