### ISSUE TITLE
chatglm2多卡训练报错

### ISSUE THREAD

**Issue by LemonZyb** [hiyouga/ChatGLM-Efficient-Tuning#268]
请教一下设备不一的问题如何解决，这是我的训练脚本，谢谢解答
CUDA_VISIBLE_DEVICES=0,1 python src/train_sft.py --do_train --dataset chatglm2-train --dataset_dir chatglm2-train --finetuning_type lora --output_dir output --per_device_train_batch_size 1 --gradient_accumulation_steps 2 --lr_scheduler_type cosine --logging_steps 1 --save_steps 1000 --learning_rate 5e-5 --num_train_epochs 3.0 --fp16 --use_v2 --num_layer_trainable 3
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/40200016/3e9ffb56-2d14-4ab1-bf80-69a464a6ce9e)

**Comment by hiyouga** [comment]
请仔细阅读Readme.

**Comment by LemonZyb** [comment]
好嘞，我看下

**Comment by LemonZyb** [comment]
可以了多谢作者
