### ISSUE TITLE
多卡全量微调报错

### ISSUE THREAD

**Issue by lucheng07082221** [hiyouga/ChatGLM-Efficient-Tuning#275]
root@7d42a87a3b9a:/ChatGLM-Efficient-Tuning# accelerate launch src/train_sft.py     --do_train     --dataset alpaca_gpt4_zh     --finetuning_type full     --output_dir path_to_sft_checkpoint     --per_device_train_batch_size 4     --gradient_accumulation_steps 4     --lr_scheduler_type cosine     --logging_steps 10     --save_steps 1000     --learning_rate 5e-5     --num_train_epochs 3.0     --fp16 --use_v2

trainable params: 6243584000 || all params: 6243584000 || trainable%: 100.0000
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:13<00:00,  1.90s/it]
07/11/2023 14:22:28 - INFO - utils.common - Fine-tuning method: Full
trainable params: 6243584000 || all params: 6243584000 || trainable%: 100.0000
[14:26:03] WARNING  Sending process 17292 closing signal SIGTERM                                                                                                                                  api.py:698
           WARNING  Sending process 17294 closing signal SIGTERM                                                                                                                                  api.py:698
           ERROR    failed (exitcode: -7) local_rank: 0 (pid: 17291) of binary: /usr/bin/python3                                                                                                  api.py:672
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /usr/local/bin/accelerate:8 in <module>                                                          │
│                                                                                                  │
│   5 from accelerate.commands.accelerate_cli import main                                          │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py:45 in main          │
│                                                                                                  │
│   42 │   │   exit(1)                                                                             │
│   43 │                                                                                           │
│   44 │   # Run                                                                                   │
│ ❱ 45 │   args.func(args)                                                                         │
│   46                                                                                             │
│   47                                                                                             │
│   48 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py:903 in launch_command       │
│                                                                                                  │
│   900 │   │   if mp_from_config_flag:                                                            │
│   901 │   │   │   args.deepspeed_fields_from_accelerate_config.append("mixed_precision")         │
│   902 │   │   args.deepspeed_fields_from_accelerate_config = ",".join(args.deepspeed_fields_fr   │
│ ❱ 903 │   │   deepspeed_launcher(args)                                                           │
│   904 │   elif args.use_fsdp and not args.cpu:                                                   │
│   905 │   │   multi_gpu_launcher(args)                                                           │
│   906 │   elif args.use_megatron_lm and not args.cpu:                                            │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py:648 in deepspeed_launcher   │
│                                                                                                  │
│   645 │   │   )                                                                                  │
│   646 │   │   with patch_environment(**current_env):                                             │
│   647 │   │   │   try:                                                                           │
│ ❱ 648 │   │   │   │   distrib_run.run(args)                                                      │
│   649 │   │   │   except Exception:                                                              │
│   650 │   │   │   │   if is_rich_available() and debug:                                          │
│   651 │   │   │   │   │   console = get_console()                                                │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/distributed/run.py:785 in run                       │
│                                                                                                  │
│   782 │   │   )                                                                                  │
│   783 │                                                                                          │
│   784 │   config, cmd, cmd_args = config_from_args(args)                                         │
│ ❱ 785 │   elastic_launch(                                                                        │
│   786 │   │   config=config,                                                                     │
│   787 │   │   entrypoint=cmd,                                                                    │
│   788 │   )(*cmd_args)                                                                           │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py:134 in __call__         │
│                                                                                                  │
│   131 │   │   self._entrypoint = entrypoint                                                      │
│   132 │                                                                                          │
│   133 │   def __call__(self, *args):                                                             │
│ ❱ 134 │   │   return launch_agent(self._config, self._entrypoint, list(args))                    │
│   135                                                                                            │
│   136                                                                                            │
│   137 def _get_entrypoint_name(                                                                  │
│                                                                                                  │
│ /usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py:250 in launch_agent     │
│                                                                                                  │
│   247 │   │   │   # if the error files for the failed children exist                             │
│   248 │   │   │   # @record will copy the first error (root cause)                               │
│   249 │   │   │   # to the error file of the launcher process.                                   │
│ ❱ 250 │   │   │   raise ChildFailedError(                                                        │
│   251 │   │   │   │   name=entrypoint_name,                                                      │
│   252 │   │   │   │   failures=result.failures,                                                  │
│   253 │   │   │   )                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ChildFailedError: 
=====================================================
src/train_sft.py FAILED
-----------------------------------------------------
Failures:
[1]:
  time      : 2023-07-11_14:26:03
  host      : 7d42a87a3b9a
  rank      : 2 (local_rank: 2)
  exitcode  : -7 (pid: 17293)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 17293
[2]:
  time      : 2023-07-11_14:26:03
  host      : 7d42a87a3b9a
  rank      : 4 (local_rank: 4)
  exitcode  : -7 (pid: 17295)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 17295
[3]:
  time      : 2023-07-11_14:26:03
  host      : 7d42a87a3b9a
  rank      : 5 (local_rank: 5)
  exitcode  : -7 (pid: 17296)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 17296
[4]:
  time      : 2023-07-11_14:26:03
  host      : 7d42a87a3b9a
  rank      : 6 (local_rank: 6)
  exitcode  : -7 (pid: 17298)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 17298
[5]:
  time      : 2023-07-11_14:26:03
  host      : 7d42a87a3b9a
  rank      : 7 (local_rank: 7)
  exitcode  : -7 (pid: 17299)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 17299
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-11_14:26:03
  host      : 7d42a87a3b9a
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 17291)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 17291
=====================================================

这是我的配置如下：
compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: none
  zero3_init_flag: true
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_config:
  dynamo_backend: INDUCTOR
  dynamo_mode: default
  dynamo_use_dynamic: true
  dynamo_use_fullgraph: true
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
~                 

知道什么原因吗？

**Comment by hiyouga** [comment]
显存不足，全量需要 3 * A100 80G

**Comment by wxhheian** [comment]
你好，我和题主报同样的错误 全量微调 chatglm2
我是单机4卡  4×A100  应该不会是现存的问题
accelerate config
- `Accelerate` version: 0.21.0
- Platform: Linux-4.19.118-2.el7.centos.x86_64-x86_64-with-glibc2.31
- Python version: 3.10.1
- Numpy version: 1.24.3
- PyTorch version (GPU?): 1.13.1+cu116 (True)
- PyTorch XPU available: False
- PyTorch NPU available: False
- System RAM: 1007.07 GB
- GPU type: NVIDIA A800-SXM4-80GB
- `Accelerate` default config:
        - compute_environment: LOCAL_MACHINE
        - distributed_type: DEEPSPEED
        - mixed_precision: fp16
        - use_cpu: False
        - num_processes: 4
        - machine_rank: 0
        - num_machines: 1
        - rdzv_backend: static
        - same_network: True
        - main_training_function: main
        - deepspeed_config: {'gradient_accumulation_steps': 1, 'offload_optimizer_device': 'cpu', 'offload_param_device': 'cpu', 'zero3_init_flag': False, 'zero3_save_16bit_model': False, 'zero_stage': 3}
        - downcast_bf16: no
        - tpu_use_cluster: False
        - tpu_use_sudo: False
        - tpu_env: []
        
      @hiyouga  可以帮忙看下吗

**Comment by wxhheian** [comment]
你好，请问最后是如何解决的呢？

**Comment by hiyouga** [comment]
@wxhheian 用 deepspeed 运行，开启 ZeRO-2 优化

**Comment by wxhheian** [comment]
> @wxhheian 用 deepspeed 运行，开启 ZeRO-2 优化

我的命令是这样的

MASTER_PORT=$(shuf -n 1 -i 10000-65535)
/home/powerop/work/python3.10/bin/deepspeed --num_gpus=4 --master_port $MASTER_PORT ../src/train_bash.py \
    --deepspeed /home/powerop/work/wxh/git_projects/ChatGLM-Efficient-Tuning/examples/deepspeed.json \
    --stage sft \
    --do_train \
    --dataset alpaca_gpt4_zh \
    --dataset_dir ../data \
    --finetuning_type full \
    --output_dir path_to_sft_checkpoint \
    --overwrite_cache \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --plot_loss \
    --fp16
    

deepspeed.json 的配置是这样的
   {
    "train_micro_batch_size_per_gpu": "auto",
    "zero_allow_untested_optimizer": true,
    "fp16": {
      "enabled": "auto",
      "loss_scale": 0,
      "initial_scale_power": 16,
      "loss_scale_window": 1000,
      "hysteresis": 2,
      "min_loss_scale": 1
    },
    "zero_optimization": {
      "stage": 2,
      "allgather_partitions": true,
      "allgather_bucket_size": 5e8,
      "overlap_comm": false,
      "reduce_scatter": true,
      "reduce_bucket_size": 5e8,
      "contiguous_gradients" : true
    }
  }
还是报一样的错误，可以帮忙看下吗，是我的deepspeed.json写的有问题吗？

**Comment by wxhheian** [comment]
@hiyouga  可以看下吗

**Comment by hiyouga** [comment]
@wxhheian 考虑可能是 CPU 内存不足
