### ISSUE TITLE
How is the comparison dataset generated?

### ISSUE THREAD

**Issue by pkqs90** [hiyouga/ChatGLM-Efficient-Tuning#278]
The comparison dataset used for reward model training, I'm curious how the second answer (one that should be rejected) is generated. Is the result generated by GPT4 or some other LLM prompting it to give a worse answer?

comparison_gpt4_data_zh.json
comparison_gpt4_data_en.json

**Comment by hiyouga** [comment]
See https://github.com/Instruction-Tuning-with-GPT-4/GPT-4-LLM

**Comment by pkqs90** [comment]
> See https://github.com/Instruction-Tuning-with-GPT-4/GPT-4-LLM

Thank you!
