### ISSUE TITLE
您好，选择了huggingface的peft库而不是微软的deepspeed,这方面有做过一些技术比对吗？

### ISSUE THREAD

**Issue by cangyi071** [hiyouga/ChatGLM-Efficient-Tuning#28]
如题，想问下，在实现不同的训练算法的时候，如何考虑使用的框架的问题，是否在几种方案中选了一个。

**Comment by hiyouga** [comment]
如果和 deepspeed 对标的话，我想你指的应该是 accelerate？ peft 和 deepspeed 不是很有可比性。
对于分布式训练，考虑到 huggingface 的 trainer API 原生支持 accelerate，能够大大减少代码量，因而选择了 huggingface 的库。
我们目前没有做过不同框架的技术比较，期待用户的结果反馈。
