### ISSUE TITLE
加载chatGLM-6b模型，提示“Please specify `use_v2` argument while using ChatGLM2-6B.”

### ISSUE THREAD

**Issue by andyzhou1982** [hiyouga/ChatGLM-Efficient-Tuning#281]
/src/pet/core/model.py文件第71行tokenizer = AutoTokenizer.from_pretrained载入tokenizer 之后，打印出tokenizer.eos_token_id=2，并不是130005，导致133行的断言assert tokenizer.eos_token_id == 130005触发
![1689149876304](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/51428368/b37ea0e6-5b3a-4539-b24c-8fd0bfb40101)

**Comment by hiyouga** [comment]
你用的是啥模型？

**Comment by andyzhou1982** [comment]
chatGLM-6b不是，第一代的

**Comment by noperoc** [comment]
我把那行断言注释掉了，可以跑

**Comment by hiyouga** [comment]
ChatGLM 1代的 eos token id 应该是 130005 没错啊

**Comment by andyzhou1982** [comment]
![1689242370478](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/51428368/99071f9f-342b-47b4-9603-af24280a7852)估计是应该用config.eos_token_id

**Comment by hiyouga** [comment]
我这里看还是 130005,
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/16256802/686b2909-7eb0-41d2-9d45-81a9833550ef)

**Comment by andyzhou1982** [comment]
原因找到了，chatGLM-6b官方的模型有更改，我的是以前下载到本地的版本，4月11日之前的模型会有这个问题
![1689298149289](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/51428368/a04a3870-4788-4db8-8d2e-bec4f16388ef)
