### ISSUE TITLE
用DeepSpeed训练时，会保存一些.pt文件

### ISSUE THREAD

**Issue by BeerTai** [hiyouga/ChatGLM-Efficient-Tuning#288]
您好，我在用DeepSpeed进行多卡训练时，会保存一些zero_pp_rank_XX_mp_rank_XX_model_states.pt文件，文件夹有20多个G，导致存储空间不足。这应该如何处理？
而用accelerate进行多卡训练时，会报错：
···
File "/root/miniconda3/envs/llm/lib/python3.8/site-packages/peft/tuners/lora.py", line 565, in forward
    result = F.linear(x, transpose(self.weight, self.fan_in_fan_out), bias=self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling "cublasCreate(handle)"
···
训练脚本是：
···
accelerate launch src/train_sft.py \
    --do_train \
    --dataset adgen_train \
    --finetuning_type lora \
    --output_dir adgen_lora \
    --overwrite_cache \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 2000 \
    --learning_rate 1e-3 \
    --num_train_epochs 2.0 \
    --lora_rank 4 \
    --max_source_length 128 \
    --max_target_length 128 \
    --ddp_find_unused_parameters False \
    --source_prefix 你现在是一名销售员，根据以下商品标签生成一段有吸引力的商品广告词。 \
    --plot_loss \
    --fp16
···
单卡训练不报错。

**Comment by neptunear** [comment]
你DeepSpeed进行多卡训练的执行脚本看一下,

**Comment by neptunear** [comment]
什么配置的卡

**Comment by BeerTai** [comment]
> 你DeepSpeed进行多卡训练的执行脚本看一下,

脚本：
```
deepspeed --num_gpus=2 src/train_sft.py \
    --deepspeed  ds_config.json \
    --do_train \
    --dataset adgen_train \
    --finetuning_type lora \
    --output_dir adgen_lora \
    --overwrite_cache \
    --per_device_train_batch_size 8 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --logging_steps 100 \
    --save_steps 50 \
    --learning_rate 1e-3 \
    --num_train_epochs 2.0 \
    --lora_rank 32 \
    --ddp_find_unused_parameters False \
    --source_prefix 你现在是一名销售员，根据以下商品标签生成一段有吸引力的商品广告词。 \
    --plot_loss \
    --fp16
```
ds_config.json文件：
```
{
    "train_micro_batch_size_per_gpu": 8,
    "gradient_accumulation_steps": 1,
    "zero_allow_untested_optimizer": true,
    "fp16": {
      "enabled": true,
      "loss_scale": 0,
      "initial_scale_power": 16,
      "loss_scale_window": 1000,
      "hysteresis": 2,
      "min_loss_scale": 1
    },
    "zero_optimization": {
      "stage": 2,
      "allgather_partitions": true,
      "allgather_bucket_size": 5e8,
      "overlap_comm": false,
      "reduce_scatter": true,
      "reduce_bucket_size": 5e8,
      "contiguous_gradients" : true
    }
  }
```
配置是2张24g的3090

**Comment by neptunear** [comment]
是的, 用accelerate会爆显存, 用ds会有额外的模型存储, 前者只能换大显存的卡, 后者一个笨方法是在 ppo.py 里save_mode函数里加上把那个大模型文件夹删除的代码

> > 你DeepSpeed进行多卡训练的执行脚本看一下,
> 
> 脚本：
> 
> ```
> deepspeed --num_gpus=2 src/train_sft.py \
>     --deepspeed  ds_config.json \
>     --do_train \
>     --dataset adgen_train \
>     --finetuning_type lora \
>     --output_dir adgen_lora \
>     --overwrite_cache \
>     --per_device_train_batch_size 8 \
>     --gradient_accumulation_steps 1 \
>     --lr_scheduler_type cosine \
>     --logging_steps 100 \
>     --save_steps 50 \
>     --learning_rate 1e-3 \
>     --num_train_epochs 2.0 \
>     --lora_rank 32 \
>     --ddp_find_unused_parameters False \
>     --source_prefix 你现在是一名销售员，根据以下商品标签生成一段有吸引力的商品广告词。 \
>     --plot_loss \
>     --fp16
> ```
> 
> ds_config.json文件：
> 
> ```
> {
>     "train_micro_batch_size_per_gpu": 8,
>     "gradient_accumulation_steps": 1,
>     "zero_allow_untested_optimizer": true,
>     "fp16": {
>       "enabled": true,
>       "loss_scale": 0,
>       "initial_scale_power": 16,
>       "loss_scale_window": 1000,
>       "hysteresis": 2,
>       "min_loss_scale": 1
>     },
>     "zero_optimization": {
>       "stage": 2,
>       "allgather_partitions": true,
>       "allgather_bucket_size": 5e8,
>       "overlap_comm": false,
>       "reduce_scatter": true,
>       "reduce_bucket_size": 5e8,
>       "contiguous_gradients" : true
>     }
>   }
> ```
> 
> 配置是2张24g的3090

是的, 用accelerate会爆显存, 用ds会有额外的模型存储, 前者只能换大显存的卡, 后者一个笨方法是在 ppo.py 里save_mode函数里加上把那个大模型文件夹删除的代码
