### ISSUE TITLE
'ModelArguments' object has no attribute 'use_v2'

### ISSUE THREAD

**Issue by Glen-Chen-Blue** [hiyouga/ChatGLM-Efficient-Tuning#290]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/wmnlab/chat/ChatGLM-Efficient-Tuning/src/train_bash.py:21 in <module>                      │
│                                                                                                  │
│   18                                                                                             │
│   19                                                                                             │
│   20 if __name__ == "__main__":                                                                  │
│ ❱ 21 │   main()                                                                                  │
│   22                                                                                             │
│                                                                                                  │
│ /home/wmnlab/chat/ChatGLM-Efficient-Tuning/src/train_bash.py:8 in main                           │
│                                                                                                  │
│    5 │   model_args, data_args, training_args, finetuning_args, general_args = get_train_args    │
│    6 │                                                                                           │
│    7 │   if general_args.stage == "sft":                                                         │
│ ❱  8 │   │   run_sft(model_args, data_args, training_args, finetuning_args)                      │
│    9 │   elif general_args.stage == "rm":                                                        │
│   10 │   │   run_rm(model_args, data_args, training_args, finetuning_args)                       │
│   11 │   elif general_args.stage == "ppo":                                                       │
│                                                                                                  │
│ /home/wmnlab/chat/ChatGLM-Efficient-Tuning/src/glmtuner/tuner/sft/workflow.py:30 in run_sft      │
│                                                                                                  │
│   27 │   │   tokenizer=tokenizer,                                                                │
│   28 │   │   model=model,                                                                        │
│   29 │   │   ignore_pad_token_for_loss=(data_args.ignore_pad_token_for_loss and not training_    │
│ ❱ 30 │   │   use_v2=model_args.use_v2                                                            │
│   31 │   )                                                                                       │
│   32 │                                                                                           │
│   33 │   # Override the decoding parameters of Seq2SeqTrainer                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'ModelArguments' object has no attribute 'use_v2'

**Comment by canglincuizhu** [comment]
The code has been updated just now. And 'use_v2' was removed.

**Comment by hiyouga** [comment]
Please update your code.
