### ISSUE TITLE
When Lora trained glm2-6b, an error was reported when loading the model.

### ISSUE THREAD

**Issue by wgq910668** [hiyouga/ChatGLM-Efficient-Tuning#292]
hi, team，I have encountered some problems

These things report incorrect information：

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:23<00:00,  3.35s/it]
[INFO|modeling_utils.py:3295] 2023-07-16 09:06:26,809 >> All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

[INFO|modeling_utils.py:3303] 2023-07-16 09:06:26,809 >> All the weights of ChatGLMForConditionalGeneration were initialized from the model checkpoint at /data/models/chatglm2-6b.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ChatGLMForConditionalGeneration for predictions without further training.
[INFO|modeling_utils.py:2927] 2023-07-16 09:06:26,811 >> Generation config file not found, using a generation config created from the model config.
Traceback (most recent call last):
  File "/data/project/ChatGLM-Efficient-Tuning/examples/../src/train_bash.py", line 21, in <module>
    main()
  File "/data/project/ChatGLM-Efficient-Tuning/examples/../src/train_bash.py", line 8, in main
    run_sft(model_args, data_args, training_args, finetuning_args)
  File "/data/project/ChatGLM-Efficient-Tuning/src/glmtuner/tuner/sft/workflow.py", line 24, in run_sft
    model, tokenizer = load_model_and_tokenizer(model_args, finetuning_args, training_args.do_train, stage="sft")
  File "/data/project/ChatGLM-Efficient-Tuning/src/glmtuner/tuner/core/loader.py", line 137, in load_model_and_tokenizer
    raise ValueError("Please update the model files of ChatGLM2-6B.")
ValueError: Please update the model files of ChatGLM2-6B.

Training command:

CUDA_VISIBLE_DEVICES=0 python ../src/train_bash.py \
    --stage sft \
    --model_name_or_path "/data/chatglm2-6b" \
    --do_train \
    --dataset self_cognition \
    --dataset_dir ../data \
    --finetuning_type lora \
    --output_dir path_to_sft_checkpoint \
    --overwrite_cache \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --plot_loss \
    --fp16

By investigating the cause:
loader.py is error

128     if tokenizer.eos_token_id == 130005: # ChatGLM-6B
129         output_embedding_base_layer = model
130         output_embedding_layer_name = "lm_head"
131     elif tokenizer.eos_token_id == 2: # ChatGLM2-6B
132         assert hasattr(model, "transformer"), "Please update the model files of ChatGLM-6B."
133         model.lm_head = model.transformer.output_layer
134         output_embedding_base_layer = model.transformer
135         output_embedding_layer_name = "output_layer"
136     else:
137         raise ValueError("Please update the model files of ChatGLM2-6B.")

**Comment by hiyouga** [comment]
The local model files seem too old to tune with this framework, please update your model files from [HuggingFace](https://huggingface.co/THUDM/chatglm2-6b).

**Comment by neozheng520** [comment]
same error,all file has been updated from huggingface

**Comment by kaixinjiuhao123** [comment]
Me too, is there a good solution?

**Comment by ZSitong** [comment]
same error when i run "python src/train_web.py" , then i change to "CUDA_VISIBLE_DEVICES=0 python src/train_web.py" ,it's ok, looks like something wrong with the accelerate in multi GPUs?

**Comment by superhuahua** [comment]
same error, then i change to "CUDA_VISIBLE_DEVICES=0 python src/train_web.py", it's not ok. Is there any other way to solve it？

**Comment by unsw-luopan** [comment]
Same error, I can run chatglm2 using the code below:

modlel_path=path_to_my_model
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)
model = AutoModel.from_pretrained(model_path, trust_remote_code=True).half().cuda()
model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)

Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████| 7/7 [00:06<00:00,  1.12it/s]
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
你好！我是人工智能助手 ChatGLM2-6B，很高兴见到你，欢迎问我任何问题。

But when I run the script
CUDA_VISIBLE_DEVICES=0 python ../src/train_bash.py
--stage sft
--model_name_or_path path_to_my_model
--do_train
--dataset self_cognition
--dataset_dir ../data
--finetuning_type lora
--output_dir path_to_sft_checkpoint
--overwrite_cache
--per_device_train_batch_size 1
--gradient_accumulation_steps 1
--lr_scheduler_type cosine
--logging_steps 10
--save_steps 1000
--learning_rate 5e-5
--num_train_epochs 3.0
--plot_loss
--fp16

I got the same error like raise ValueError("Please update the model files of ChatGLM2-6B.")

**Comment by hiyouga** [comment]
Why not update your model???
https://huggingface.co/THUDM/chatglm2-6b/tree/main
