### ISSUE TITLE
能否给一个调用Freeze且量化INT8或INT4的命令样例？

### ISSUE THREAD

**Issue by landxman** [hiyouga/ChatGLM-Efficient-Tuning#295]
能否给一个调用Freeze且量化INT8或INT4的命令样例？
谢谢！

**Comment by hiyouga** [comment]
freeze 不支持 int 量化，量化只能用  p tuning 或 LoRA

**Comment by landxman** [comment]
如果freeze不支持int量化，这里的int8是如何来的？
<img width="582" alt="image" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/17037628/4ebf7298-d69d-419b-aad7-f084d8b62dda">

**Comment by hiyouga** [comment]
我之后验证一下

**Comment by couldn** [comment]
我也想知道这个

**Comment by hiyouga** [comment]
Freeze 方法不支持量化
