### ISSUE TITLE
P-tuning的数据格式是怎样？

### ISSUE THREAD

**Issue by landxman** [hiyouga/ChatGLM-Efficient-Tuning#296]
P-tuning要求的数据格式是"prompt/query/response/history"，还是"instruction/input/output"，或者是其他格式？

**Comment by hiyouga** [comment]
看 data 文件夹的 Readme

**Comment by landxman** [comment]
看过了，还是不知道。
什么条件下需要做字段的转换？
例如：
"columns": {
        "prompt": "the name of the column in the datasets containing the prompts. (default: instruction)",
        "query": "the name of the column in the datasets containing the queries. (default: input)",
        "response": "the name of the column in the datasets containing the responses. (default: output)",
        "history": "the name of the column in the datasets containing the history of chat. (default: None)"
    }

**Comment by hiyouga** [comment]
当你的字段名称和 Default 不同的时候

**Comment by hiyouga** [comment]
另外，你可以查阅本项目的 Github Wiki

**Comment by landxman** [comment]
看了本项目的 Github Wiki，也没有看出P-tuning数据的Default的字段是什么？

**Comment by xiabo0816** [comment]
数据的字段应该是都一样的，参考`self_cognition.json`:
```json
[
  {
    "instruction": "你身份是什么？",
    "input": "",
    "output": "我叫ChatGLM-6B，是一个由[NAME]于2023年独立训练和开发的人工智能助手。我的主要目标是协助用户解决问题和满足他们的需求。"
  }
]
```

**Comment by landxman** [comment]
群主测试p-tuning时，使用的是哪个数据集？
我用instruction/input/output，loss都是0，不知道是否正确。
我想测试一下群主的数据集，看看loss是否也是0？

**Comment by codemayq** [comment]
数据集和 使用 ptuning，还是lora无关哈，简单可以使用self_congnition 数据集
