### ISSUE TITLE
大神，能出个懒人包吗？

### ISSUE THREAD

**Issue by shmily91** [hiyouga/ChatGLM-Efficient-Tuning#3]
在b站看到你的这个项目，期待你出个懒人包喔，这样方便我们这些小白使用

**Comment by hiyouga** [comment]
你好，感谢你对我们项目的关注！

懒人包的制作已经加入了TODO LIST里，可能会在一个月内完成。

事实上本项目抽象掉的步骤只有配置Anaconda环境和显卡驱动这两步，很多云计算节点甚至已经预先完成了这两步，因此基本上是开箱即用的。由于微调需要20G以上的显存，因此不建议在个人电脑上而是在专业的云计算节点上进行微调。

如果在部署中遇到其他问题，也欢迎随时提issue。

**Comment by hiyouga** [comment]
#6 请根据`README_cn.md`中的指引训练和加载本地模型。
#7 建议不要自行指定`--model_name_or_path`参数，默认参数下会使用huggingface上的最新版本。
#9 设备的CUDA环境没有正确配置，建议在专业计算节点上训练模型，本地GPU环境通常难以支持微调。如果本地GPU性能足够，请参考https://zhuanlan.zhihu.com/p/361434464 等类似文章的教程进行CUDA环境配置，本项目暂时不予赘述。
