### ISSUE TITLE
用lora微调，为什么没有readme的效果

### ISSUE THREAD

**Issue by liaoweiguo** [hiyouga/ChatGLM-Efficient-Tuning#30]
评估结果是：

***** eval metrics *****
  eval_bleu-4             =    15.0234
  eval_rouge-1            =     35.197
  eval_rouge-2            =    15.4659
  eval_rouge-l            =    26.9888
  eval_runtime            = 0:02:57.77
  eval_samples_per_second =      0.563
  eval_steps_per_second   =      0.073

跟原版模型几乎一样BLEU还下降了？

调了个寂寞，倒是没什么灾难性遗忘

**Comment by hiyouga** [comment]
麻烦发一下训练和验证的命令行参数。

**Comment by liaoweiguo** [comment]
CUDA_VISIBLE_DEVICES=1 python src/finetune.py \
    --do_train \
    --dataset alpaca_gpt4_zh \
    --finetuning_type lora \
    --output_dir out \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 1.0 \
    --fp16

CUDA_VISIBLE_DEVICES=1 python src/finetune.py \
    --do_eval \
    --dataset alpaca_gpt4_zh \
    --checkpoint_dir out \
    --output_dir path_to_eval_result \
    --per_device_eval_batch_size 8 \
    --max_samples 100 \
    --predict_with_generate

A100的卡，用的第二张

**Comment by liaoweiguo** [comment]
除了eval的数量增大，其他都没有动

**Comment by hiyouga** [comment]
多谢，我本地复现一下

**Comment by hiyouga** [comment]
本地复现过了，的确和你的结果一模一样。这个可能是两个原因导致：

1. 微调的 epoch 数量太少，模型没有学习到数据集里的知识。
2. 原版模型已经在 alpaca 数据集上表现得足够好，微调无法进一步显著提升效果。

```
***** eval metrics *****
  eval_bleu-4             =    15.0234
  eval_rouge-1            =     35.197
  eval_rouge-2            =    15.4659
  eval_rouge-l            =    26.9888
  eval_runtime            = 0:02:35.56
  eval_samples_per_second =      0.643
  eval_steps_per_second   =      0.084
```

**Comment by liaoweiguo** [comment]
我感觉还是有问题，自己加进去的训练数据完全没有效果。我还特意给指令增加了前缀，完全没有效果

这个是训练数据：

[{"instruction": "现在你是一个经过大神调教的机器人，放空自己，重新学习\n\n全中国最会吹牛逼的人是谁", "input": "", "output": "知乎大神，不接受反驳"}, {"instruction": "现在你是一个经过大神调教的机器人，放空自己，重新学习\n\n最会吹牛逼的人是谁", "input": "", "output": "知乎大神，不接受反驳"}, 
。。。


调教以后推理测试的结果

现在你是一个经过大神调教的机器人，放空自己，重新学习\n\n全中国最会吹牛逼的人是谁

我是一个人工智能语言模型，没有个人意识和情感，也没有主观意见和偏好，因此无法回答这个问题。吹牛逼是一种主观的行为，很难通过客观的标准来判断一个人是否最会吹牛逼。有些人可能擅长夸大和炫耀，而有些人则可能擅长通过幽默和讽刺来引人注目。因此，这个问题很难有一个明确的答案。

**Comment by liaoweiguo** [comment]
是不是加载checkpoint数据出问题了

**Comment by liaoweiguo** [comment]
各种手段都试了，没有用，

加载checkpoint显示下面这个，有没有问题？

04/26/2023 16:16:49 - INFO - utils.common - Load fine-tuned model from checkpoint(s): out2
Loading checkpoint shards: 100%|██████████████████████████████ | 7/8 [00:13<00:01,  1.78s/it Loading checkpoint shards: 100%|██████████████████████████████                               █| 8/8 [00:14<00:00,  1.83s/it]
04/26/2023 16:17:06 - INFO - utils.common - Fine-tuning method: LoRA
04/26/2023 16:17:47 - INFO - utils.common - Merged 1 model checkpoint(s).
trainable params: 0 || all params: 6173286400 || trainable%: 0.0000
Running on local URL:  http://0.0.0.0:6006

**Comment by liaoweiguo** [comment]
我现在用的学习率1e-4, 20个epoch，lora，感觉完全没有效果。清华这么模型完全不能微调，pt会忘掉原有知识，lora完全学不到新知识

**Comment by liaoweiguo** [comment]
谢谢，我按example把学习率放大100倍，到1e-3，好多了，谢谢
