### ISSUE TITLE
请问用您的代码跑的chatglm2-6b的原始模型，为什么问相同的问题回复都是一样。而官方代码跑的没有这个问题？

### ISSUE THREAD

**Issue by YinSonglin1997** [hiyouga/ChatGLM-Efficient-Tuning#303]
![1689522525853](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/90330685/50005efc-8c45-4c7a-bc76-82a7391d44b5)

**Comment by JingBob** [comment]
是不是temperature设置太低或者top-p设置太高？

**Comment by YinSonglin1997** [comment]
> 是不是temperature设置太低或者top-p设置太高？

都是默认设置的，temperature=0.95，top-p=0.7

**Comment by codemayq** [comment]
你好，我跑官方代码也是都一样的回复，你可以确认一下。

**Comment by wertyac** [comment]
temp设置到1.6，我们测试过，top_p到0.9，模型可以回答出不同的问题，官方的。
