### ISSUE TITLE
請問要怎麼加入--lora_rank 8這個參數

### ISSUE THREAD

**Issue by TimLeeGee** [hiyouga/ChatGLM-Efficient-Tuning#31]
請問要怎麼加入--lora_rank 8這個參數
以下為例子

    CUDA_VISIBLE_DEVICES=0 python src/finetune.py \
        --do_train \
        --dataset alpaca_gpt4_zh \
        --finetuning_type lora \
        --output_dir path_to_checkpoint \
        --per_device_train_batch_size 4 \
        --gradient_accumulation_steps 4 \
        --lr_scheduler_type cosine \
        --logging_steps 10 \
        --save_steps 1000 \
        --learning_rate 5e-5 \
        --num_train_epochs 1.0 \
        --lora_rank 8 \
        --fp16
    
直接加在倒數第二行可以嗎?
我是個程式新手，請多包涵。謝謝。

**Comment by TimLeeGee** [comment]
> 請問要怎麼加入--lora_rank 8這個參數 以下為例子
> ``` 
CUDA_VISIBLE_DEVICES=0 python src/finetune.py --do_train --dataset alpaca_gpt4_zh --finetuning_type lora --output_dir path_to_checkpoint --per_device_train_batch_size 4 --gradient_accumulation_steps 4 --lr_scheduler_type cosine --logging_steps 10 --save_steps 1000 --learning_rate 5e-5 --num_train_epochs 1.0 --lora_rank 8 --fp16
> ```
> 直接加在倒數第二行可以嗎?
> 我是個程式新手，請多包涵。謝謝。
>

**Comment by hiyouga** [comment]
这个做法没问题，关于微调的参数直接加入到训练参数中即可。

**Comment by TimLeeGee** [comment]
> 这个做法没问题，关于微调的参数直接加入到训练参数中即可。

真的非常的謝謝，我是因為AI而開始研究程式的，有很多不懂，能有你幫忙真是太好了。

**Comment by hiyouga** [comment]
不客气，可以查看 examples 文件夹中的两个教程来学习。
