### ISSUE TITLE
PPO训练完成后，inference速度慢了10倍以上

### ISSUE THREAD

**Issue by xujunrt** [hiyouga/ChatGLM-Efficient-Tuning#311]
path=output/resume_ppo/
filename=checkpoint-100

accelerate launch --config_file accelerate_config_eval.yaml ../src/train_bash.py \
    --stage sft \
    --do_predict \
    --use_v2 \
    --dataset resume_test \
    --dataset_dir ../data \
    --checkpoint_dir ${path}${filename} \
    --output_dir ${path}${filename} \
    --overwrite_cache \
    --max_source_length 300 \
    --max_target_length 512 \
    --per_device_eval_batch_size 8 \
    --max_samples 100000 \
    --lora_rank 8 \
    --fp16 \
    --predict_with_generate

![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/23271863/433a5b69-1211-4c75-8114-43f344defc78)

**Comment by hiyouga** [comment]
用 export_model.py 合并模型以后再 inference
