### ISSUE TITLE
使用Deepspeed不能减少显存,求解!

### ISSUE THREAD

**Issue by koalasix-sky** [hiyouga/ChatGLM-Efficient-Tuning#319]
根据文档进行sft,发现使用deepspeed和不使用deepspeed训练消耗的显存相同,具体情况如下:
训练命令:
deepspeed --num_gpus=8 src/train_bash.py     --deepspeed  /home/relay/xiehaining/ChatGLM-Efficient-Tuning/ds_conifg.json     --do_train     --dataset workexp_data     --finetuning_type lora     --output_dir demo_sft     --overwrite_cache     --per_device_train_batch_size 1     --gradient_accumulation_steps 4     --lr_scheduler_type cosine     --logging_steps 100     --save_steps 50     --learning_rate 1e-3     --num_train_epochs 2.0     --lora_rank 8     --fp16

ds_config.json配置:
<details><summary>Details</summary>
<p>

{
  "train_micro_batch_size_per_gpu": 1,
  "gradient_accumulation_steps": 4,
  "zero_allow_untested_optimizer": true,
  "fp16": {
    "enabled": true,
    "loss_scale": 0,
    "initial_scale_power": 16,
    "loss_scale_window": 1000,
    "hysteresis": 2,
    "min_loss_scale": 1
  },
  "zero_optimization": {
    "stage": 2,
    "allgather_partitions": true,
    "allgather_bucket_size": 5e8,
    "overlap_comm": false,
    "reduce_scatter": true,
    "reduce_bucket_size": 5e8,
    "contiguous_gradients" : true
  }
}

</p>
</details>

**Comment by hiyouga** [comment]
DeepSpeed 用 LoRA 没什么效果，只有全量微调才能看出显存减少
