### ISSUE TITLE
我照着covid_doctor的案例使用了demo的数据进行监督微调到强化学习的训练处理，但是训练出来模型推理问答回复都很短，只有3到5个字，有知道是什么原因的吗

### ISSUE THREAD

**Issue by CJianZ** [hiyouga/ChatGLM-Efficient-Tuning#322]
参数基本都跟demo一致，就是更换了chatglm2-6b的主模型和ppo那一步调整了参数per_device_train_batch_size 为1 和 save_steps 调成了200
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/139970103/5fdc32a8-18e0-4af1-8b3d-ad623f9113fe)

特别惜字如金的感觉

**Comment by dfsong** [comment]
我训练下来也是同样的情况，回复都变短了

**Comment by CJianZ** [comment]
用chatglm-6b按demo训练好像会正常一些，没有chatglm2-6b训练那样的问题

**Comment by wertyac** [comment]
碰见同样的问题，chatglm2的回复短了很多，用的是lora的微调。而且发现出现重复现象。
