### ISSUE TITLE
多机分布式sft fulltuning

### ISSUE THREAD

**Issue by chestnutman998** [hiyouga/ChatGLM-Efficient-Tuning#323]
请教一下多机分布式sft fulltuning的脚本和配置文件，可以给一个详细的demo吗？谢谢

**Comment by hiyouga** [comment]
see https://zhuanlan.zhihu.com/p/624223085?utm_id=0

**Comment by chestnutman998** [comment]
Greetings and thanks for your email.This is an automatic mail reply. Your message has been delivered successfully.
