### ISSUE TITLE
可以在Mac上训练吗

### ISSUE THREAD

**Issue by archerbj** [hiyouga/ChatGLM-Efficient-Tuning#326]
请问可以在MAC上训练吗
M1 ， 32G

**Comment by hiyouga** [comment]
不支持

**Comment by godcrying** [comment]
应该可以，我用CPU跑起来了。把 --fp16 选项删掉，模型配置文件里的torch_type改为float32。参考[ChatGLM2-6B/issues/211](https://github.com/THUDM/ChatGLM2-6B/issues/211)。。然而速度慢的令人发指
