### ISSUE TITLE
Warning with transformer.rotary_pos_emb.inv_freq'

### ISSUE THREAD

**Issue by Ricardokevins** [hiyouga/ChatGLM-Efficient-Tuning#327]
当我使用最新的代码，DeepSpeed-Zero2微调 ChatGLM2 6B时后
加载权重推理时出现如下警告：
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint  and are newly initialized: ['transformer.rotary_pos_emb.inv_freq']

这个警告是否表明部分参数没有保存和加载好，可能带来潜在的性能损失？

**Comment by hiyouga** [comment]
可以手动把这个拷贝到新的 state dict 里面

**Comment by Ricardokevins** [comment]
> 可以手动把这个拷贝到新的 state dict 里面

这个是什么意思，是需要我先load SFT后的模型，然后从原始的模型参数中去加载这个权重吗

**Comment by Ricardokevins** [comment]
> 可以手动把这个拷贝到新的 state dict 里面

确认了一下发现这个参数确实没保存，在sft后的pytorch_model.bin.index.json里没有这个参数

**Comment by hiyouga** [comment]
在新版代码中修复了这个问题，请更新代码

**Comment by Ricardokevins** [comment]
> 在新版代码中修复了这个问题，请更新代码



> 在新版代码中修复了这个问题，请更新代码

问题还是存在
我注意到了更新的代码并修改如下：
```
def get_state_dict(model: torch.nn.Module, trainable_only: Optional[bool] = True) -> Dict[str, torch.Tensor]:
    state_dict = model.state_dict()
    filtered_state_dict = {}
    print("trainable_only:", trainable_only)
    name = []
    for k, v in model.named_parameters():
        if (not trainable_only) or v.requires_grad:
            filtered_state_dict[k] = state_dict[k].cpu().clone().detach()
            name.append(k)
    print(name)
    exit()
```

**Comment by Ricardokevins** [comment]
这里依旧没有保存rotary_pos_emb参数

**Comment by hiyouga** [comment]
感谢指出，我再检查一下

**Comment by hiyouga** [comment]
我检查了一下，这个参数即使不保存，也始终会和 ChatGLM 原始模型保持相同的值，因此可以忽视这个警告。

**Comment by Ricardokevins** [comment]
> 我检查了一下，这个参数即使不保存，也始终会和 ChatGLM 原始模型保持相同的值，因此可以忽视这个警告。

yes，因为没有可训练的东西来着，我看了源码就是直接初始化的
