### ISSUE TITLE
api和train_web加载同一个微调后,同问题推理结果不同

### ISSUE THREAD

**Issue by jtao024** [hiyouga/ChatGLM-Efficient-Tuning#328]
以下是启动api的配置,之前是使用use_v2,更新代码后根据要求删除了该参数
```
CUDA_VISIBLE_DEVICES=1 nohup  python src/api_demo.py \
    --checkpoint_dir /home/THUDM/ChatGLM-Efficient-Tuning/path_to_sft_checkpoint \
    --finetuning_type lora \
    --model_name_or_path /home/THUDM/chatglm2-6b &
```
因为微调后固定提示词的问题会有固定回答格式,之前版本代码使用'use_v2'配置的没有问题.但是这次API返回的与预期结构不同
使用train_web.py后,在页面中配置同样的模型和微调文件,回答的格式就是预期的结构
所以麻烦问一下,是否api启动部分缺少了什么配置?谢谢啦

**Comment by codemayq** [comment]
你好，是否可以再更新一下最新的版本，再重试一下。web版本也更新了多次。
