### ISSUE TITLE
一机多卡训练不成功cuda:0 and cuda:1! 

### ISSUE THREAD

**Issue by amwork2020** [hiyouga/ChatGLM-Efficient-Tuning#329]
CUDA_VISIBLE_DEVICES=0,1 python ../src/train_bash.py \
    --stage sft \
    --model_name_or_path THUDM/chatglm2-6b \
    --do_train \
    --dataset self_cognition \
    --dataset_dir ../data \
    --finetuning_type lora \
    --output_dir path_to_sft_checkpoint \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 2 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --warmup_steps 0 \
    --learning_rate 1e-3 \
    --num_train_epochs 20.0 \
    --fp16
报如下错误
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for 
argument index in method wrapper_CUDA__index_select)

**Comment by hiyouga** [comment]
请看 readme 和 wiki

**Comment by amwork2020** [comment]
> 请看 readme 和 wiki

ok了，谢谢

**Comment by RuiShaoo** [comment]
请问如何解决？

**Comment by RuiShaoo** [comment]
请问如何使用 Accelerate 或 DeepSpeed 启动脚本。
