### ISSUE TITLE
ptuning  占用我40多个G显存？

### ISSUE THREAD

**Issue by cxj01** [hiyouga/ChatGLM-Efficient-Tuning#337]
ptuning前
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/37614132/bf2890c9-550f-4955-93aa-086d09d2c4ef)
ptuning 后
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/37614132/c65d043c-5da0-468e-bf55-67e8da7d1032)

**Comment by hiyouga** [comment]
和 batchsize 等设置有关，还有 GPU cache
