### ISSUE TITLE
关于微调chatglm2时参数怎么填？

### ISSUE THREAD

**Issue by phelixzhen** [hiyouga/ChatGLM-Efficient-Tuning#340]
想微调chatglm2模型，model_revision一项不知道怎么填，好像\src\glmtuner\hparams\model_args.py文件中只有一个main啊？

**Comment by hiyouga** [comment]
保持默认

**Comment by hiyouga** [comment]
只要保证 --model_name_or_path 是 ChatGLM2 模型就行

**Comment by phelixzhen** [comment]
好的，感谢
