### ISSUE TITLE
一级多卡24G 3090上lora 训练包cuda错误

### ISSUE THREAD

**Issue by amwork2020** [hiyouga/ChatGLM-Efficient-Tuning#343]
24G 3090
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

**Comment by hiyouga** [comment]
单卡能跑吗？多卡这种情况可能是内存或者显存溢出

**Comment by amwork2020** [comment]
> 单卡能跑吗？多卡这种情况可能是内存或者显存溢出

单卡能跑

**Comment by liuyijiang1994** [comment]
同样的情况

**Comment by 1042280163** [comment]
我也是同样的状况，24g3090  单卡能跑，但是多卡就报这个错

**Comment by liuyijiang1994** [comment]
> 我也是同样的状况，24g3090 单卡能跑，但是多卡就报这个错

最后用examples下面的accelerate配置可以了，看了下用了ds。
不知道到底是什么原因

**Comment by amwork2020** [comment]
> 

您执行的命令是啥，我执行accelerate launch --config_file accelerate_config.yaml ../src/train_bash.py  还是报错呀？

**Comment by liuyijiang1994** [comment]
> 

还是报cuda错误吗？ 需要把examples/accelerate_config.yaml里面的参数调整为hf一致
