### ISSUE TITLE
RLFH执行时报错'NoneType' object has no attribute '_is_accelerate_prepared'

### ISSUE THREAD

**Issue by Pobby321** [hiyouga/ChatGLM-Efficient-Tuning#345]
输入
CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --stage ppo \
    --do_train \
    --dataset 0725 \
    --dataset_dir data \
    --finetuning_type lora \
	--model_name_or_path /data/user/hug/GLM2-6B \
    --checkpoint_dir /data/user/ChatGLM-Efficient-Tuning-main/output/0720 \
    --reward_model ./output/0725_rm \
    --output_dir ./output/ppo/ \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 4 \
    --max_source_length 36 \
    --max_target_length 4096 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 100 \
    --learning_rate 1e-5 \
    --num_train_epochs 5.0 \
    --resume_lora_training False \
    --plot_loss

输出报错
│ /data/user/ChatGLM2-Efficient-Tuning/src/train_bash.py:12 in main                                │
│                                                                                                  │
│    9 │   elif general_args.stage == "rm":                                                        │
│   10 │   │   run_rm(model_args, data_args, training_args, finetuning_args)                       │
│   11 │   elif general_args.stage == "ppo":                                                       │
│ ❱ 12 │   │   run_ppo(model_args, data_args, training_args, finetuning_args)                      │
│   13                                                                                             │
│   14                                                                                             │
│   15 def _mp_fn(index):                                                                          │
│                                                                                                  │
│ /data/user/ChatGLM2-Efficient-Tuning/src/glmtuner/tuner/ppo/workflow.py:52 in run_ppo            │
│                                                                                                  │
│   49 │   )                                                                                       │
│   50 │   print(model)                                                                            │
│   51 │   # Initialize our Trainer                                                                │
│ ❱ 52 │   ppo_trainer = PPOTrainerForChatGLM(                                                     │
│   53 │   │   training_args=training_args,                                                        │
│   54 │   │   finetuning_args=finetuning_args,                                                    │
│   55 │   │   callbacks=callbacks,                                                                │
│                                                                                                  │
│ /data/user/ChatGLM2-Efficient-Tuning/src/glmtuner/tuner/ppo/trainer.py:36 in __init__            │
│                                                                                                  │
│    33 │   │   callbacks: List[LogCallback],                                                      │
│    34 │   │   **kwargs                                                                           │
│    35 │   ):                                                                                     │
│ ❱  36 │   │   PPOTrainer.__init__(self, **kwargs)                                                │
│    37 │   │   self.args = training_args                                                          │
│    38 │   │   self.finetuning_args = finetuning_args                                             │
│    39 │   │   self.log_callback = callbacks[0]                                                   │
│                                                                                                  │
│ /home/user/miniconda3/envs/firefly/lib/python3.9/site-packages/trl/trainer/ppo_trainer.py:311 in │
│ __init__                                                                                         │
│                                                                                                  │
│    308 │   │   │   if self.accelerator.state.deepspeed_plugin.zero_stage == 3:                   │
│    309 │   │   │   │   self.model.train()                                                        │
│    310 │   │   else:                                                                             │
│ ❱  311 │   │   │   self.ref_model = self.accelerator.prepare(self.ref_model)                     │
│    312 │   │                                                                                     │
│    313 │   │   # In a distributed setup, only logging needs to be performed on the main process  │
│    314 │   │   # check: https://pytorch.org/docs/stable/generated/torch.nn.parallel.Distributed  │
│                                                                                                  │
│ /home/user/miniconda3/envs/firefly/lib/python3.9/site-packages/accelerate/accelerator.py:1201 in │
│ prepare                                                                                          │
│                                                                                                  │
│   1198 │   │   │   result = self._prepare_fsdp(*result)                                          │
│   1199 │   │                                                                                     │
│   1200 │   │   for item in result:                                                               │
│ ❱ 1201 │   │   │   setattr(item, "_is_accelerate_prepared", True)                                │
│   1202 │   │                                                                                     │
│   1203 │   │   return result if len(result) > 1 else result[0]                                   │
│   1204                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute '_is_accelerate_prepared'

**Comment by hiyouga** [comment]
升级一下 Accelerate 库试试
