### ISSUE TITLE
PPO loss和reward曲线

### ISSUE THREAD

**Issue by Ricardokevins** [hiyouga/ChatGLM-Efficient-Tuning#347]
您好，我尝试使用了RLHF流程，但是对loss和reward的含义不大清楚，从图形来看似乎训练并不是稳定，想问问这个是正常的吗
<img width="567" alt="image" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/43642508/c8d7d2b7-9e5f-4210-8261-bc3e2b3a7914">
<img width="484" alt="image" src="https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/43642508/6a73a448-c27b-4580-a2da-b9019b05440e">

**Comment by chestnutman998** [comment]
https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/examples/covid_doctor.md

**Comment by Ricardokevins** [comment]
这会儿有个问题就是，整个流程只支持Lora啊，不支持全量微调，就很吃亏，因为性能损失的比较多。我就算魔改了load模型的位置，后面好像也有很多不适配的地方

**Comment by Ricardokevins** [comment]
@chestnutman998 @hiyouga

**Comment by Ricardokevins** [comment]
> https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/examples/covid_doctor.md

还有一个问题就是，这个代码版本和当时的代码有修复什么bug吗，还是说您只是单纯的在一个示例数据集上进行了实验

**Comment by chestnutman998** [comment]
Greetings and thanks for your email.This is an automatic mail reply. Your message has been delivered successfully.
