### ISSUE TITLE
webui计算类型能不能fp16 bf16都不启用

### ISSUE THREAD

**Issue by yuxin-hong-91** [hiyouga/ChatGLM-Efficient-Tuning#348]
计算类型
是否启用 FP16 或 BF16 混合精度训练。
fp16
bf16

现在必须选一个，p-tuning不支持FP16，选BF16时报错：RuntimeError: expected scalar type BFloat16 but found Half

**Comment by hiyouga** [comment]
已修复

**Comment by yuxin-hong-91** [comment]
效率哇 nbnb
