### ISSUE TITLE
请问支持边训练边验证嘛

### ISSUE THREAD

**Issue by DoubleYing** [hiyouga/ChatGLM-Efficient-Tuning#349]
CUDA_VISIBLE_DEVICES=0 python src/train_sft.py \
    --do_train \
    --do_eval \
    --dev_ratio 0.2 \
    --dataset dataset_0724 \
    --finetuning_type lora \
    --output_dir schedule_sft_checkpoint_add_0724_v4 \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 10.0 \
    --fp16 \
    --use_v2 \
    --model_name_or_path chatglm2-6b \
    --plot_loss \
    --overwrite_cache
按这个脚本，可以把数据集分成训练集和验证集，但是只能看到训练loss的输出，验证loss 是会在什么时候输出呢？训练结束之后嘛？还是可以支持边训练边验证？

**Comment by hiyouga** [comment]
请参考 examples

**Comment by codemayq** [comment]
参数dev_ratio就是设置了 边训练边验证的数据集大小
过程中会输出  ***** Running Evaluation ***** 日志
如{'eval_loss': 3.069248914718628, 'eval_runtime': 11.7536, 'eval_samples_per_second': 16.25, 'eval_steps_per_second': 4.084, 'epoch': 6.19}                                                                                                                                                                                                   

最后输出的training_eval_loss.png 就记录全过程。
