### ISSUE TITLE
为什么我在不联网的情况下不能lora呢？

### ISSUE THREAD

**Issue by WangShunzhiDQ** [hiyouga/ChatGLM-Efficient-Tuning#35]
config文件里的chatglm-6b模型的路径我没改，在联网的机器可以正常运行，可切换到离线状态就不能跑了，为什么？我需要如何修改代码才可以在离线状态下lora训练chatglm模型呢？请大神指点！！！

**Comment by hiyouga** [comment]
本框架为了和最新模型版本同步，在模型加载时使用了联网下载的方式，如果想要在离线主机上部署，可以参考 https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/examples/alter_self_cognition.md 中的步骤，将模型下载到本地并通过 `--model_name_or_path` 参数指向本地文件夹地址。

**Comment by WangShunzhiDQ** [comment]
我确实是这么传的，但本地路径的传递好像不对啊。报错如下
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: 'C:\\Users\\rjsadmin\\.cache\\huggingface\\modules\\transformers_modules\\C:'

**Comment by hiyouga** [comment]
windows路径使用方式和Linux不太一样，建议查一下资料，这个应该不是框架的问题。

**Comment by WangShunzhiDQ** [comment]
好吧，谢谢。如果您有windows的路径使用方式，麻烦再回复我一下！感谢。。。我现在要去hub.py里写死变量参数了，不让它下载。。。

**Comment by hiyouga** [comment]
用不着修改hub.py，如果他检测到了本地的模型，就不会下载，否则肯定是路径识别不到。

**Comment by WangShunzhiDQ** [comment]
我一直没找到如何让它检测到我本地有模型的办法。。。

**Comment by hiyouga** [comment]
你的问题和这个很相似，路径拼写有误
https://github.com/THUDM/ChatGLM-6B/issues/340

**Comment by WangShunzhiDQ** [comment]
可以了，保留原来的“\”这种斜杠就可以了
