### ISSUE TITLE
transformers版本是4.29.1 每次训练的时候 就报这个错  下述是脚本 是少了什么么 

### ISSUE THREAD

**Issue by bubblebyfly** [hiyouga/ChatGLM-Efficient-Tuning#351]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/140377071/2bc01b8b-96af-470b-9133-ba6592831bb4)

CUDA_VISIBLE_DEVICES=0 python src/train_bash.py \
    --stage sft \
    --model_name_or_path ./base_model \
    --do_train \
    --dataset falab_cognition \
    --finetuning_type lora \
    --output_dir output/cognition \
    --overwrite_cache \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 2 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --warmup_steps 0 \
    --learning_rate 1e-3 \
    --num_train_epochs 10.0 \
    --fp16

**Comment by hiyouga** [comment]
see https://github.com/THUDM/ChatGLM-6B/issues/1038

**Comment by codemayq** [comment]
see [https://github.com/THUDM/ChatGLM-6B/issues/310](https://github.com/THUDM/ChatGLM-6B/issues/310)

看着是 --model_name_or_path ./base_model 的问题，试试把 相对路径改成绝对路径，同时更新一下模型目录
