### ISSUE TITLE
训练数据集带上 history 数据，解析异常

### ISSUE THREAD

**Issue by zhuam** [hiyouga/ChatGLM-Efficient-Tuning#352]
rt

![11690372375_ pic](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/241174/1d7c6fef-88e7-4a4f-b4f4-b9eb7f3c1a79)

样例数据如下：

`
{
    "instruction": "传统媒体传播了什么虚假视频？",
    "input": "",
    "output": "宽体和窄体都分不清的虚假视频。",
    "history": [
      [
        "发生日期?",
        "2021-1-10"
      ],
      [
        "发生时间?",
        "12:24:31"
      ],
      [
        "主角是哪些?",
        "传统媒体"
      ],
      [
        "发生的地点?",
        ""
      ],
      [
        "描述的是什么事件?",
        "虚假消息, 坠机"
      ]
    ]
  }
`

**Comment by hiyouga** [comment]
需要修改 dataset_info 并添加 columns 定义

**Comment by mawenju203** [comment]
问一下，dataset_info 并添加 columns 定义，完成后， 数据里可以存在有些包含history有些不包含history的情况吗？如下所示
```
{
    "instruction": "2021-1-10, 12:24:31, 传统媒体, 虚假消息, 坠机",
    "input": "",
    "output": "传统媒体传播虚假视频，宽体和窄体都分不清，是真傻还是故意的？"
  },
  {
    "instruction": "传统媒体传播了什么虚假视频？",
    "input": "",
    "output": "宽体和窄体都分不清的虚假视频。",
    **"history"**: [
      [
        "发生日期?",
        "2021-1-10"
      ],
      [
        "发生时间?",
        "12:24:31"
      ],
      [
        "主角是哪些?",
        "传统媒体"
      ],
      [
        "发生的地点?",
        ""
      ],
      [
        "描述的是什么事件?",
        "虚假消息, 坠机"
      ]
    ]
  }
```

**Comment by zhuam** [comment]
@hiyouga 👍 tks
