### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers_modules.'  遇到这个bug

### ISSUE THREAD

**Issue by bubblebyfly** [hiyouga/ChatGLM-Efficient-Tuning#355]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/140377071/47dba87d-9215-478d-b1e1-d7a6715372e4)

**Comment by hiyouga** [comment]
see https://github.com/THUDM/ChatGLM-6B/issues/310

**Comment by codemayq** [comment]
see https://github.com/hiyouga/ChatGLM-Efficient-Tuning/issues/351
