### ISSUE TITLE
训练成功 启动测试的时候报错了 

### ISSUE THREAD

**Issue by bubblebyfly** [hiyouga/ChatGLM-Efficient-Tuning#356]
Provided path (D:\ChatGLM2\ChatGLM2\ChatGLM-Efficient-Tuning-main\output\cognition) does not contain a LoRA weight.
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/140377071/0b1ce20c-604d-46e8-9469-6ee2188963a0)
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/140377071/4393e27c-9ef6-4fbe-9734-07255304acfe)

**Comment by kbwzy** [comment]
同样问题，webui_demo.py可以打开，但是cli_demo.py不行

**Comment by iori0758** [comment]
checkpoint_dir目录不是你训练out的目录吧，检查下是否有adapter_model.bin文件的

**Comment by liangwei2020** [comment]
请问有解决办法吗？

**Comment by codemayq** [comment]
请更新到最新版本哈
