### ISSUE TITLE
怎么不支持边训练边验证保存最佳模型再做测试？

### ISSUE THREAD

**Issue by xujunrt** [hiyouga/ChatGLM-Efficient-Tuning#36]
现在训练和验证分开的，不利于保存最佳模型，是否能改进一下

**Comment by hiyouga** [comment]
ChatGLM 在训练和验证时采用了不同的 padding 策略，所以较难以统一训练和验证步骤。可以采用保存多个 checkpoint 的方法，在训练结束后使用验证集挑选最佳模型。

**Comment by hiyouga** [comment]
最新版代码已经支持此功能，请参考 examples/train_sft_with_dev_set.sh。
