### ISSUE TITLE
在服务器上执行 src/train_web.py 报错

### ISSUE THREAD

**Issue by FreeYiran** [hiyouga/ChatGLM-Efficient-Tuning#361]
在服务器上执行src/train_web.py，修改了launch()参数为True，报错信息：

Running on local URL:  http://0.0.0.0:7860

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app.

**Comment by hiyouga** [comment]
share=False

**Comment by mawenju203** [comment]
需要你的网络可以提供公网服务；如果是局域网等等，share=False即可

**Comment by FreeYiran** [comment]
Share=False的话，local url如何在本地浏览器访问呢？

**Comment by hiyouga** [comment]
本地用 localhost 即可
