### ISSUE TITLE
训练不小心中断后，如何设置进行断点续训？

### ISSUE THREAD

**Issue by FreeYiran** [hiyouga/ChatGLM-Efficient-Tuning#362]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/91936532/ae2b1d0e-b6ce-4ca2-91e7-ac6437f8f7ed)

**Comment by hiyouga** [comment]
--checkpoint_dir

**Comment by hiyouga** [comment]
是的

**Comment by FreeYiran** [comment]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/91936532/c779cd6d-273a-4247-b6a4-7f07c8de6c36)
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/91936532/6d46ca72-0b07-43e1-ab8c-2de7fb480a67)
您好，还是出现报错

**Comment by FreeYiran** [comment]
是不是要将check_point_dir 指定到训练中断前的最后一个保存check_point的文件夹呢？
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/91936532/1f4d17fa-c35c-4c11-8116-4c673ec89e8c)

**Comment by FreeYiran** [comment]
已经解决好了，谢谢您的解答！！

**Comment by FreeYiran** [comment]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/91936532/c0a5ed6d-7d1f-4f60-8c41-3983be3d9354)
这还是在chongxi重新训练吗？我记得之前是50%多了

**Comment by hiyouga** [comment]
进度条和数据集不会继承，需要手动减少 epoch

**Comment by FreeYiran** [comment]
好的，谢谢！
