### ISSUE TITLE
如何设置输入长度

### ISSUE THREAD

**Issue by HuShenS** [hiyouga/ChatGLM-Efficient-Tuning#363]
求救！！我在使用LoRA微调ChatGLM V2时已经设置了： --max_source_length 8192 \ --max_target_length 512，
但是在加载权重推理时，我传输了："max_length": 8192，还是报错：(如何设置最大输入文本长度)
Input length of input_ids is 4955, but `max_length` is set to 2048. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.

**Comment by hiyouga** [comment]
这个不是报错是 warning吧

**Comment by HuShenS** [comment]
对对对，是warning，大佬 这个文本长度过长 超出2048，会使模型的输出混乱吗？因为我需要处理的都是长文本，字符长度为4096、8192等，有什么方法可以设置一下输入长度参数吗

**Comment by hiyouga** [comment]
不会有问题

**Comment by HuShenS** [comment]
大佬，还有个小问题，可以有办法 返回 输出模型回答 的置信度或者confidence吗？

**Comment by hiyouga** [comment]
没有
