### ISSUE TITLE
请问用example/里的quantized_finetune_with_local_model微调后怎么正确加载output并启动demo

### ISSUE THREAD

**Issue by R0nnyz** [hiyouga/ChatGLM-Efficient-Tuning#364]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/122671545/96727824-fdbb-4db0-95b3-060dad0199b7)
我使用这个代码成功启动了web demo，但为什么进行的微调完全没效果。是output没有正确加载吗？我的数据集格式是instruction，input，output。三百条数据左右，和训练前的结果几乎没区别。

**Comment by hiyouga** [comment]
数据量太少
