### ISSUE TITLE
建议对 data/*.json 文件使用 lfs 管理

### ISSUE THREAD

**Issue by Haskely** [hiyouga/ChatGLM-Efficient-Tuning#366]
建议对 data/*.json 文件使用 git-lfs 管理，否则 clone 下要好几十兆，网络不好的环境会很慢

**Comment by hiyouga** [comment]
很好的建议，之后我优化一下

**Comment by Haskely** [comment]
其实也有其他方案，比如都交给 datasets 库来管（看代码已经兼容了，缺点是有些需要登账号），看作者大大权衡。

**Comment by hiyouga** [comment]
已经使用 lfs
