### ISSUE TITLE
关于sft之后，奖励模型和rlhf

### ISSUE THREAD

**Issue by lzh1998-jansen** [hiyouga/ChatGLM-Efficient-Tuning#372]
1.奖励模型和rlhf的数据集，参考提供的样例来制作吗
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/61367424/7991eaa9-bf96-4165-8d6f-88bb984ebca6)
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/61367424/f787e95f-5a04-494d-9f01-d0d751cc8475)
2.我没看出来这俩数据集跟finetune数据集的区别在哪里，针对自己的数据集，如何制作奖励模型和强化学习所需的数据集

**Comment by codemayq** [comment]
问题1：是的，参考样例制作
问题2：rm奖励模型的output 是list， 训练目标是让 第0句比第1句分数更高，而finetune的output是string，目标就是生成这句话。ppo阶段的数据集和 finetune数据集是已有的。 

如何制作rm奖励模型的数据集
1. 先完成finetue阶段，得到SFT模型。
2. 从finetune数据集中采样部分问题，每个都让SFT模型生成2个以上的回答
3. 对于步骤2的结果使用人工标注或者其他方式对回答的质量做一个排序，得到rm数据集。

**Comment by lzh1998-jansen** [comment]
> 问题1：是的，参考样例制作 问题2：rm奖励模型的output 是list， 训练目标是让 第0句比第1句分数更高，而finetune的output是string，目标就是生成这句话。ppo阶段的数据集和 finetune数据集是已有的。
> 
> 如何制作rm奖励模型的数据集
> 
> 1. 先完成finetue阶段，得到SFT模型。
> 2. 从finetune数据集中采样部分问题，每个都让SFT模型生成2个以上的回答
> 3. 对于步骤2的结果使用人工标注或者其他方式对回答的质量做一个排序，得到rm数据集。

感谢您的回复，多谢了

**Comment by landxman** [comment]
"从finetune数据集中采样部分问题，每个都让SFT模型生成2个以上的回答"
建议采样比例是多少？
