### ISSUE TITLE
请问用Lora微调2万条医疗问答，为什么Loss只能降低到2.7，效果不佳

### ISSUE THREAD

**Issue by tongjialiang** [hiyouga/ChatGLM-Efficient-Tuning#375]
训练集是2万条医疗问答对，质量较高，用chatgpt润色过。
学习率5e-5,1e-5,1e-6,5e-6都试过了，
epoch=300
但是loss降不下来，loss 2.7以后就震荡了，下不去。
为了测试效果，我植入一些宇宙不存在的问答对，例如 “question:请问ABCDK乐园在哪里？”“answer:在MNOP路上”，
但微调后的模型没有按我的测试数据来回答，而是幻想了一个答案“在上海滴水湖”

**Comment by tongjialiang** [comment]
我的数据集大概是这样的：
{"question": "什么是循证护理？在护理过程中，循证护理为什么很重要？\n", "answer": "\n1）循证护理是指护理人员在护理过程中遵循最佳实践和应用最新的科学研究结果来做出护理决策的方法。2）循证护理是一种基于证据的实践，可以提高病患的护理质量，减少病患的并发症和降低医疗成本。3）通过使用EBP中的评判性思维、评判性推理、反思和判断，护理人员可以更好地完成循证护理的过程，使得护理服务更加安全和高效。循证护理是实现优质护理服务的重要手段，有助于提高病患的生活质量和保障病患安全。\n"}, 
{"question": "如何预防老年人跌倒？跌倒对老年人有什么不良影响？\n", "answer": "\n1）老年人跌倒是一种常见的意外事故，预防老年人跌倒的方法主要包括以下几个方面：1.1）保持室内外照明充足，清除地面杂物，避免滑倒；1.2）使用护理辅具，例如手杖、拐杖等，帮助老人行走；1.3）开展体育锻炼，增强身体素质，包括平衡能力；1.4）社区和家庭应该安装必要的安全设施，例如扶手、防滑垫。\n\n2）跌倒对老年人的不良影响非常严重，包括：2.1）身体受伤，可能需要住院治疗，甚至导致残疾；2.2）失去独立生活的能力，需要寻求外界帮助；2.3）失去自信心，可能导致心理上的恐惧和抑郁；2.4）增加了家庭和医疗资源的负担，可能导致经济上的损失。因此，预防老年人跌倒非常重要，可以减少老年人的身体和心理损失，提高老年人生活质量。\n"}

**Comment by codemayq** [comment]
epoch 是300？

**Comment by tongjialiang** [comment]
> epoch 是300？

是的，300个大概训练了2-3天，4090的显卡

**Comment by Alwin4Zhang** [comment]
> > epoch 是300？
> 
> 是的，300个大概训练了2-3天，4090的显卡

换baichuan13b-base，可能就好很多

**Comment by mawenju203** [comment]
学习率调大一点
