### ISSUE TITLE
lora后模型的泛化能力如何增强呢？

### ISSUE THREAD

**Issue by mawenju203** [hiyouga/ChatGLM-Efficient-Tuning#377]
1. 使用数据增强技术，将一个问题增强为多种不同的表达形式？
问题：增强比例多少合适呢？chatglm数据是否做了数据增强，比例大约是多少呢？

loss 下降到了0.012了；为什么泛化能力还是有差异，
![Uploading image.png…]()
粗红线是正确的结果， 细红线是错误的结果；

现在完成的数据增强内容（六种）
![Uploading 9f6174c48ad5f59de850fb4ddaa4a6b.jpg…]()

**Comment by mawenju203** [comment]
6种数据增强手段：
![9f6174c48ad5f59de850fb4ddaa4a6b](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/30227934/36667033-9c18-4090-a8fc-6503268fffe6)
现在的泛化能力：
粗红线是正确的，细红线是表示有问题的数据
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/30227934/85c6f3b2-57ac-450a-a88b-9143d05c3535)

**Comment by hiyouga** [comment]
假数据
