### ISSUE TITLE
为什么glm2训练需要较大的学习率才有效

### ISSUE THREAD

**Issue by JingBob** [hiyouga/ChatGLM-Efficient-Tuning#379]
使用glm2做sft时，需要将学习率从5e-5调到1e-3才有较好效果，这个有什么讲究吗？LLM的学习率应该怎么调，有没什么经验？

**Comment by codemayq** [comment]
1. 可能你的数据集太小，导致学不到东西，可以增大数据量
2. epoch适当调大一些试一试，训练更充分

增大学习率，相当于以更大的强度去使用新样本的梯度更新模型参数，可以更快学习到新知识，但是整体效果不一定是最优的，可能会遗忘老知识。

默认的5e-5 是一个相对还正常的经验值，1e-3相当于提高了20倍。

**Comment by zhanghaoie** [comment]
全参微调的话需要多大的学习率合适？

**Comment by xlhuang132** [comment]
> 全参微调的话需要多大的学习率合适？

你好，请问这个有结论吗？

**Comment by JingBob** [comment]
全参微调没试过，你可以自己用经验的5e-5开始试
