### ISSUE TITLE
在chatglm-6b-int4模型上微调会出现以下错误，想问下作者，是否不支持直接在int4模型上微调？

### ISSUE THREAD

**Issue by Two222** [hiyouga/ChatGLM-Efficient-Tuning#38]
Error:
RuntimeError: mat1 and mat2 shapes cannot be multiplied (812x4096 and 2048x12288)

大家有遇到这样的问题吗？

**Comment by hiyouga** [comment]
是的，我们没有实现对int4模型的直接微调，目前只支持原版ChatGLM 6B模型

**Comment by Two222** [comment]
感谢感谢，有什么途径可以直接认识联系您呢？

**Comment by hiyouga** [comment]
不客气，可以加我们的微信交流群

**Comment by Two222** [comment]
在哪里可以看到呢？

**Comment by hiyouga** [comment]
readme文件里
