### ISSUE TITLE
关于PPO中ref_model的问题

### ISSUE THREAD

**Issue by JoyYChen** [hiyouga/ChatGLM-Efficient-Tuning#380]
在trl里边，首先是判断self.model是不是加载了peft，如果是，则不对self.model进行deepcopy。
self.is_peft_model = getattr(self.model, "is_peft_model", False)
在这种时候，ref_logprobs是用self.model来得到的。
根据大佬提供的命令设置，在运行RLHF的时候，设置：
--resume_lora_training为False，上述的if_peft_model为True。
是否我的理解有误，我输出if_peft_model确实是True。

**Comment by JoyYChen** [comment]
不好意思，这个问题我不确定ChatGLM是否也会，但是在LLaMA框架中是有的。

**Comment by hiyouga** [comment]
没太听懂你的问题，if_peft_model=True 是我们想要的结果

**Comment by JoyYChen** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我是陈源，已收到你的来信，我会尽快阅读，如需回复会尽快处理，如果是署名文件，请备注相关姓名，谢谢。

**Comment by JoyYChen** [comment]
如果if_peft_model=True 的话，在trl的ppo_trainer中，ref_model是为None，也就是计算kl散度的ref_logprob和logprob不是同源吗？

**Comment by hiyouga** [comment]
相同还有什么意义呢

**Comment by JoyYChen** [comment]
对啊，因为if_peft_model=True的时候，它们是相同的，trl不支持添加了adapter的model作为ref_model

**Comment by JoyYChen** [comment]
在trl的ppo_trainer中，如果没有给定ref_model，会对提供的model进行复制得到ref_model
而如果model添加了adapter，则ref_model是None，这种时候，计算KL散度的两个logprob是同源的
在代码中，我发现了上述说的这个问题，请大佬确认一下

**Comment by JoyYChen** [comment]
trl貌似是不支持对没有对adapter进行merge的model同时作为ref_model
