### ISSUE TITLE
请问下在4-bit量化模式Lora微调最小的显存要求 

### ISSUE THREAD

**Issue by NJU201220184** [hiyouga/ChatGLM-Efficient-Tuning#394]
根据readme中的表格，最小运行显存为8G。
我的服务器配置为4块 NVIDIA GeForce RTX 2080，显存为11264MiB，运行指令为：
accelerate launch src/train_bash.py \
    --stage sft \
    --model_name_or_path /home/ChatGLM2/chatglm2-6b \
    --do_train \
    --dataset lima \
    --dataset_dir ./data \
    --finetuning_type lora \
    --output_dir /home/ChatGLM2/chatglm2-6b-lora \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 100 \
    --save_steps 5000 \
    --learning_rate 1e-6 \
    --num_train_epochs 3.0 \
    --quantization_bit 4
报错如下：torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 214.00 MiB (GPU 0; 10.75 GiB total capacity; 10.47 GiB already allocated; 109.50 MiB free; 10.47 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
（根据报错可以看到已经接近11G，远超您写的8G）
请问还有可能继续减小显存吗？

**Comment by codemayq** [comment]
你好，使用 accelerate 很多人反馈会加大一些内存，你可以不使用accelerate 再试一下。我这边单卡实验了你的参数，显存可以压在8GB以下。
