### ISSUE TITLE
跑sft阶段出现这个问题，环境应该是ok的

### ISSUE THREAD

**Issue by wangweihua11** [hiyouga/ChatGLM-Efficient-Tuning#397]
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/141142352/38c1cb67-2454-4fa3-ab15-e8f93a199816)
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/141142352/b43401be-d0ce-485c-aa96-a40c3c0d4ea5)

**Comment by hiyouga** [comment]
命令有误

**Comment by wangweihua11** [comment]
> 命令有误

哪个命令有误，不是很明白？
