### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by suckseed5** [hiyouga/ChatGLM-Efficient-Tuning#405]
有没有人遇到这个问题，同样的数据在A100-40G（cuda-11.4）上，一跑就报错：
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/76991214/c2b92426-b250-42f2-a5f7-96371f64f56c)

**Comment by codemayq** [comment]
请问有跑过其他程序吗，这个看着像是 CUDA本身的配置问题，可以先参考这个 做一些问题排查
https://saturncloud.io/blog/what-is-cuda-illegal-memory-access-error-and-how-to-fix-it-with-sufficient-memory/
