### ISSUE TITLE
第三步出现错误：RuntimeError: probability tensor contains either inf, nan or element < 0

### ISSUE THREAD

**Issue by Lauorie** [hiyouga/ChatGLM-Efficient-Tuning#42]
File "/output/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 114, in <module>
    main()
  File "/output/ChatGLM-Efficient-Tuning/src/train_ppo.py", line 82, in main
    responses_with_queries = ppo_trainer.generate(queries, length_sampler=output_length_sampler, **gen_kwargs)
  File "/output/ChatGLM-Efficient-Tuning/src/utils/ppo.py", line 162, in generate
    response = self.accelerator.unwrap_model(self.model).generate(
  File "/usr/local/envs/chatglm_etuning/lib/python3.10/site-packages/trl/models/modeling_value_head.py", line 195, in generate
    return self.pretrained_model.generate(*args, **kwargs)
  File "/usr/local/envs/chatglm_etuning/lib/python3.10/site-packages/peft/peft_model.py", line 731, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/usr/local/envs/chatglm_etuning/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/generation/utils.py", line 1485, in generate
    return self.sample(
  File "/usr/local/envs/chatglm_etuning/lib/python3.10/site-packages/transformers/generation/utils.py", line 2560, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

**Comment by fulQuan** [comment]
同遇到这个问题；另外，刚开始训练时，log中loss有报nan，learning rate 调到1e-6也不行。

**Comment by hiyouga** [comment]
在 generation 时候设置 `do_sample=False` 也许能解决这个问题，但可能会降低 RL 学习能力。

**Comment by hiyouga** [comment]
该问题在最新版本中代码中已经得到修复，请使用 `git pull` 更新仓库，无需修改别的代码。

**Comment by KLGR123** [comment]
然而没有修复 我仍旧存在这个问题 在evaluate阶段
@hiyouga

**Comment by hiyouga** [comment]
@KLGR123 已记录，在之后的更新中修复。

**Comment by KLGR123** [comment]
> @KLGR123 已记录，在之后的更新中修复。

具体来说，就是不改`do_sample`，会报错 probability tensor contains either inf, nan or element < 0
改的话，时间会很长
我的环境也是 3090 24GB，训练阶段没有任何报错，wandb下log一切正常
eval阶段也都是按照要求一步一步来的
感谢！

**Comment by wanglaichao** [comment]
> @KLGR123 已记录，在之后的更新中修复。

你好问下，什么时候会修复呢，一直这个错误，环境是A100 torch=2.0.1修改了do_sample也报这个错误

**Comment by wanglaichao** [comment]
> @wanglaichao 我应该已经修复了呢，使用最新的代码还会出现这个报错吗？

是的呢，今天刚搭的新环境，重新拉了模型。
我们是基于6b模型用官方例子跑完，运行就报这个错误。训练过程一切正常。

**Comment by hiyouga** [comment]
@wanglaichao 请问你的官方例子具体是哪个？然后提供一下运行的完整命令行参数？

**Comment by wanglaichao** [comment]
> json



> @wanglaichao 请问你的官方例子具体是哪个？然后提供一下运行的完整命令行参数？

6b模型之前的模型，跑起来是正常的，模型升级后就不行了，我猜测是模型哪里出问题了，感谢回答

**Comment by hiyouga** [comment]
@wanglaichao 你运行的所有脚本似乎都和本项目中的代码无关，有关官方代码的问题请在官方 GitHub Repo 下提问。

**Comment by wanglaichao** [comment]
>
> @wanglaichao 你运行的所有脚本似乎都和本项目中的代码无关，有关官方代码的问题请在官方 GitHub Repo 下提问。这里只回答有关本项目框架的问题。

好的，谢谢了

**Comment by wccccp** [comment]
> > @wanglaichao 请问你的官方例子具体是哪个？然后提供一下运行的完整命令行参数？
> 
> 我们用的chatglm-6b测试的微调ptuning测试数据就是Git主业提供的数据，下面是链接 https://cloud.tsinghua.edu.cn/f/b3f119a008264b1cabd1/?dl=1 运行脚本也是官网提供的命令如下： PRE_SEQ_LEN=128 LR=2e-2
> 
> CUDA_VISIBLE_DEVICES=0 python main.py --do_train --train_file AdvertiseGen/train.json --validation_file AdvertiseGen/dev.json --prompt_column content --response_column summary --overwrite_cache --model_name_or_path THUDM/chatglm-6b --output_dir output/adgen-chatglm-6b-pt-$PRE_SEQ_LEN-$LR --overwrite_output_dir --max_source_length 64 --max_target_length 64 --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --gradient_accumulation_steps 16 --predict_with_generate --max_steps 3000 --logging_steps 10 --save_steps 1000 --learning_rate $LR --pre_seq_len $PRE_SEQ_LEN --quantization_bit 4 环境是单卡 A100 torch==2.0.1 Python==Python 3.10.9 执行脚本： path="/data1/ChatGLM-6B/ptuning/output_chat_nofb16/adgen-chatglm-6b-pt-128-1e-2/checkpoint-1000" tokenizer = AutoTokenizer.from_pretrained(path, trust_remote_code=True) model = AutoModel.from_pretrained(path, trust_remote_code=True) model = model.half().cuda() model = model.eval() while True: try: qs = input("请输入你的问题。\n") if qs: response, history = model.chat(tokenizer, qs, [], temperature=0.1) print(response)
> 
> ```
> except Exception as E:
>     traceback.print_exc()
> ```
> 
> 错误如下： Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /data1/ChatGLM-6B/ptuning/output_chat_nofb16/adgen-chatglm-6b-pt-128-1e-2/checkpoint-1000 and are newly initialized: ['transformer.layers.23.mlp.dense_h_to_4h.weight', 'transformer.layers.18.attention.query_key_value.bias', 'transformer.layers.10.post_attention_layernorm.weight', 'transformer.layers.26.pos。。。 你好 请输入你的问题。 The dtype of attention mask (torch.int64) is not bool nTraceback (most recent call last): File "/data1/ChatGLM-6B/ptuning/run_ptuning_brand.py", line 28, in response, history = model.chat(tokenizer, qs, [], temperature=0.1) File "/home/tuangouadmin/anaconda3/envs/chatglm-6b/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/home/tuangouadmin/.cache/huggingface/modules/transformers_modules/checkpoint-1000/modeling_chatglm.py", line 1285, in chat outputs = self.generate(**inputs, **gen_kwargs) File "/home/tuangouadmin/anaconda3/envs/chatglm-6b/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/home/tuangouadmin/anaconda3/envs/chatglm-6b/lib/python3.10/site-packages/transformers/generation/utils.py", line 1452, in generate return self.sample( File "/home/tuangouadmin/anaconda3/envs/chatglm-6b/lib/python3.10/site-packages/transformers/generation/utils.py", line 2504, in sample next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1) RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

解决了吗？

**Comment by Modas-Li** [comment]
> > @wanglaichao 我应该已经修复了呢，使用最新的代码还会出现这个报错吗？
> 
> 是的呢，今天刚搭的新环境，重新拉了模型。 我们是基于6b模型用官方例子跑完，运行就报这个错误。训练过程一切正常。

大佬解决了吗，我也是推理报错
