### ISSUE TITLE
我在尝试lora时报错

### ISSUE THREAD

**Issue by WangShunzhiDQ** [hiyouga/ChatGLM-Efficient-Tuning#43]
我的服务器有4个32G的GPU显卡，lora时报错如下：
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument index in method wrapper__index_select)
我需要改哪里的代码才能指定一个卡呢？

**Comment by WangShunzhiDQ** [comment]
我是windows系统，我是在pycharm里的Terminal中执行的如下命令：python ../src/finetune.py --do_train  --model_name_or_path  C:\Users\rjsadmin\.cache\huggingface\modules\transformers_modules\chatglm-6b\35ca52301fbedee885b0838da5d15b7b47faa37c --dataset self_cognition --dataset_dir ../data --finetuning_type lora --output_dir ../cognition --overwrite_cache --per_device_train_batch_size 2 --gradient_accumulation_steps 2 --lr_scheduler_type cosine --logging_steps 10 --save_steps 1000 --warmup_steps 0 --learning_rate 1e-3 --num_train_epochs 10.0 --fp16
没有找到指定哪个GPU的参数，请指点一下，谢谢

**Comment by hiyouga** [comment]
请参考 https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/examples/finetune.sh

其中第一行 `CUDA_VISIBLE_DEVICES=0` 即可指定使用的 GPU 序号。

**Comment by WangShunzhiDQ** [comment]
您这个是.sh文件，git执行命令，可以给一个python直接执行的命令吗？

**Comment by hiyouga** [comment]
> 您这个是.sh文件，git执行命令，可以给一个python直接执行的命令吗？

```python
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0"
```

加在 `finetune.py` 文件的第一行。

**Comment by WangShunzhiDQ** [comment]
感谢！可以了

**Comment by HYheyue** [comment]
> > 您这个是.sh文件，git执行命令，可以给一个python直接执行的命令吗？
> 
> ```python
> import os
> os.environ["CUDA_VISIBLE_DEVICES"]="0"
> ```
> 
> 加在 `finetune.py` 文件的第一行。

我已经配置了accelerate config还是出现了同样的问题，请问是什么原因啊？

**Comment by hiyouga** [comment]
@HYheyue 配置 config 时 GPU 数量可能和机器的 GPU 数量不一致。
