### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by WangRongsheng** [hiyouga/ChatGLM-Efficient-Tuning#45]
报错'TypeError: argument of type 'NoneType' is not iterable'

**Comment by WangRongsheng** [comment]
`CUDA_VISIBLE_DEVICES=0 python src/finetune.py --do_train --dataset merged-cMedQA --finetuning_type lora --output_dir ./med-lora --per_device_train_batch_size 8 --gradient_accumulation_steps 8 --lr_scheduler_type cosine --logging_steps 10 --save_steps 1000 --learning_rate 5e-5 --num_train_epochs 10.0 --fp16`

**Comment by WangRongsheng** [comment]
应该是某个参数设置为none报错？

**Comment by WangRongsheng** [comment]
请使用高版本的`transformers`

**Comment by hiyouga** [comment]
请使用 `pip install transformers>=4.27.4` 将 transformers 库升级到 4.27.4 版本以上。
