### ISSUE TITLE
请问--checkpoint_dir是只支持一个epoch的断点么？每1000次保存的没法继续吗

### ISSUE THREAD

**Issue by LainNetWork** [hiyouga/ChatGLM-Efficient-Tuning#5]
![image](https://user-images.githubusercontent.com/20994069/232253038-86fa03e0-3efa-4cd2-a1c8-6556382e9ef1.png)
![image](https://user-images.githubusercontent.com/20994069/232253062-cb0a9954-e967-498e-9a03-5220597b87cf.png)
如图，我打算加载1000次的断点，但这里报错找不到文件，我看了一下文件名，这个finetuning_args.bin在1000step自动保存的文件夹下面是没有的

**Comment by hiyouga** [comment]
已解决，请使用`git pull`更新最新版代码，可能需要重新训练模型。
