### ISSUE TITLE
全参数微调

### ISSUE THREAD

**Issue by nghuyong** [hiyouga/ChatGLM-Efficient-Tuning#52]
请教一下，有全参数微调的版本吗

BELLE中的实验表明全参数微调的效果会更好 https://github.com/LianjiaTech/BELLE

**Comment by hiyouga** [comment]
提供了对全参数微调的支持，请在微调时指定 `--finetuning_type full` 参数，我们推荐使用 accelerate 或 deepspeed 进行全参数微调。

**Comment by hiyouga** [comment]
@nghuyong 需要4 * A100 GPU

**Comment by wxhheian** [comment]
> @nghuyong 需要4 * A100 GPU
请问 
4 * A100 GPU   每张A100 是多大显存的？

**Comment by wxhheian** [comment]
> @nghuyong 需要4 * A100 GPU

以及具体的 accelerate config 可以贴一下吗

**Comment by ArtificialZeng** [comment]
> @nghuyong 需要4 * A100 GPU

最低要求显存是多少，

**Comment by nghuyong** [comment]
提供一个参考点
8 * A100(40G) + deepspeed 可以全参数微调
per_device_train_batch_size = 4, max_seq_len = 256

**Comment by ArtificialZeng** [comment]
> 提供一个参考点 8 * A100(40G) + deepspeed 可以全参数微调 per_device_train_batch_size = 4, max_seq_len = 256

这么低的 max_seq_len呀，生成的回答很短吗
