### ISSUE TITLE
about train speed.

### ISSUE THREAD

**Issue by www516717402** [hiyouga/ChatGLM-Efficient-Tuning#53]
Set same parmeters with different dataset.
1. small dataset get 1.5s/iter
2. large dataset get 5.6s/iter
Why get this appearence,

**Comment by hiyouga** [comment]
训练速度可能会受到输入样本长度的影响，具体可参考 [transformer 训练复杂度与序列长度的关系](https://kexue.fm/archives/8610#%E8%AF%84%E4%BC%B0%E8%AE%A1%E7%AE%97%E9%87%8F)。
