### ISSUE TITLE
训练语料长度超出2048token

### ISSUE THREAD

**Issue by clintlong** [hiyouga/ChatGLM-Efficient-Tuning#54]
训练语料长度超出时候，只有warnning，但是训练的时候会报错，我要改成超长语料剔除的话，在哪里修改代码？

**Comment by hiyouga** [comment]
我们提供了 `--max_source_length` 和 `--max_target_length` 参数来限制训练语料长度，理论上不应该有报错，麻烦您提供一下完整的报错信息和训练命令行参数。

**Comment by lin-xiaosheng** [comment]
> 我们提供了 `--max_source_length` 和 `--max_target_length` 参数来限制训练语料长度，理论上不应该有报错，麻烦您提供一下完整的报错信息和训练命令行参数。

大大，麻烦问一下项目中默认的`--max_source_length和`--max_target_length是多少呢，我将两者都调到了2048后训练效果迅速下降，训练后的模型基本没有训练的痕迹

**Comment by tu2022** [comment]
想问一下，如果max_source_lenghth 长度需要1024需要多少显存？我用了四张v100，32g的卡还是显示显存不足，我在accelerate设置num_processes为8，想用8张卡，但是直接报错,不知道为什么

**Comment by hiyouga** [comment]
@lin-xiaosheng 默认两者都是 512，不建议将两者超过 1024，因为 ChatGLM-6B 的最大长度是 2048。

**Comment by paralym** [comment]
> > 我们提供了 `--max_source_length` 和 `--max_target_length` 参数来限制训练语料长度，理论上不应该有报错，麻烦您提供一下完整的报错信息和训练命令行参数。
> 
> 大大，麻烦问一下项目中默认的`--max_source_length和`--max_target_length是多少呢，我将两者都调到了2048后训练效果迅速下降，训练后的模型基本没有训练的痕迹

我也都设置到了2048，好像也没有训练痕迹
