### ISSUE TITLE
使用ads_generation的例子进行单卡微调无法复现结果

### ISSUE THREAD

**Issue by fangd123** [hiyouga/ChatGLM-Efficient-Tuning#59]
你好，我使用ads_generation的例子步骤，进行模型微调，使用单卡2080Ti（22G），最后大概在7000步的时候，loss值出现了跳动，然后就直接归零了，请问这可能是什么原因

![W B Chart 2023_5_6 15_49_55](https://user-images.githubusercontent.com/3364985/236618521-b7c6555f-3c9e-4145-bb8c-db6acde400fd.png)

**Comment by hiyouga** [comment]
请问你在训练中使用了量化吗？提供一下完整的命令行参数。

**Comment by fangd123** [comment]
完整的命令行参数：
```bash
E:\aigc\ChatGLM-Efficient-Tuning\src\finetune.py 
--do_train 
--dataset adgen_train 
--finetuning_type lora 
--output_dir adgen_lora 
--overwrite_cache 
--per_device_train_batch_size 4 
--lr_scheduler_type cosine 
--logging_steps 10 
--save_steps 2000 
--learning_rate 1e-3 
--num_train_epochs 2.0 
--lora_rank 32 
--ddp_find_unused_parameters False 
--source_prefix 你现在是一名销售员，根据以下商品标签生成一段有吸引力的商品广告词。 
--plot_loss 
--max_source_length 128 
--max_target_length 128 
--fp16
```

**Comment by hiyouga** [comment]
去掉 `ddp_find_unused_parameters`、`max_source_length` 和 `max_target_length` 参数试试？

**Comment by fangd123** [comment]
这次没有出现loss为0的情况了，但是loss升上去了之后就一直在上面维持着
![W B Chart 2023_5_10 23_07_24](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/3364985/1ff1225a-033e-4cd2-9025-2a5fe7dde706)

**Comment by T-Atlas** [comment]
> 这次没有出现loss为0的情况了，但是loss升上去了之后就一直在上面维持着。
> 
> 搜了一下ddp_find_unused_parameters这个参数，只在分布式计算中用到，我这样的单卡会有影响嘛 ![W B Chart 2023_5_10 23_07_24](https://user-images.githubusercontent.com/3364985/237434891-1ff1225a-033e-4cd2-9025-2a5fe7dde706.png)

想请问一下为什么会出现这种loss到后期突然上升的情况，我之前使用prefix tuning在自己数据集上也会遇到这种类似情况
