### ISSUE TITLE
训练中的 prompt query 怎么在推理时拼接

### ISSUE THREAD

**Issue by liaoweiguo** [hiyouga/ChatGLM-Efficient-Tuning#64]
"columns": {
        "prompt": "the name of the column in the datasets containing the prompts. (default: instruction)",
        "query": "the name of the column in the datasets containing the queries. (default: input)",
        "response": "the name of the column in the datasets containing the responses. (default: output)",
        "history": "the name of the column in the datasets containing the history of chat. (default: None)"
    }

**Comment by hiyouga** [comment]
如果是指运行 infer.py 的时候，可以手动拼接 prompt 和 query。

**Comment by liaoweiguo** [comment]
是不是在stream_chat中，直接 input=f"{prompt} {query}" ?

**Comment by hiyouga** [comment]
我没太懂你的意思，我们的微调框架不涉及 stream_chat 函数，推理时候可以自由输入内容。
