### ISSUE TITLE
使用8bit量化LoRA训练时，出现了如下错误，是否有人遇到过？

### ISSUE THREAD

**Issue by jimmy-kuo** [hiyouga/ChatGLM-Efficient-Tuning#65]
File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torch/nn/functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: expected scalar type Half but found Float

训练参数如下：
python3.8 src/finetune.py \
    --do_train \
    --dataset alpaca_gpt4_zh \
    --finetuning_type lora \
    --output_dir path_to_checkpoint \
    --per_device_train_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 5e-5 \
    --num_train_epochs 1.0 \
    --quantization_bit=8

**Comment by hiyouga** [comment]
请查阅 [GitHub Wiki](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/wiki/%E5%B8%B8%E8%A7%81%E6%8A%A5%E9%94%99%E4%BF%A1%E6%81%AF%E6%B1%87%E6%80%BB)。

**Comment by jimmy-kuo** [comment]
重新调整训练参数后：
训练参数如下：
python3.8 src/finetune.py
--do_train
--dataset alpaca_gpt4_zh
--finetuning_type lora
--output_dir path_to_checkpoint
--per_device_train_batch_size 4
--gradient_accumulation_steps 4
--lr_scheduler_type cosine
--logging_steps 10
--save_steps 1000
--learning_rate 5e-5
--num_train_epochs 1.0
--quantization_bit=8
--fp16
训练过程中报如下错误：
/opt/conda/envs/python3.8/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py:298: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization
  warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization")
Traceback (most recent call last):
  File "src/finetune.py", line 88, in <module>
    main()
  File "src/finetune.py", line 60, in main
    train_result = trainer.train()
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/transformers/trainer.py", line 1662, in train
    return inner_training_loop(
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/transformers/trainer.py", line 1962, in _inner_training_loop
    self.scaler.unscale_(self.optimizer)
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 282, in unscale_
    optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False)
  File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 210, in _unscale_grads_
    raise ValueError("Attempting to unscale FP16 gradients.")
ValueError: Attempting to unscale FP16 gradients.

**Comment by joey7777777** [comment]
> 重新调整训练参数后： 训练参数如下： python3.8 src/finetune.py --do_train --dataset alpaca_gpt4_zh --finetuning_type lora --output_dir path_to_checkpoint --per_device_train_batch_size 4 --gradient_accumulation_steps 4 --lr_scheduler_type cosine --logging_steps 10 --save_steps 1000 --learning_rate 5e-5 --num_train_epochs 1.0 --quantization_bit=8 --fp16 训练过程中报如下错误： /opt/conda/envs/python3.8/lib/python3.8/site-packages/bitsandbytes/autograd/_functions.py:298: UserWarning: MatMul8bitLt: inputs will be cast from torch.float32 to float16 during quantization warnings.warn(f"MatMul8bitLt: inputs will be cast from {A.dtype} to float16 during quantization") Traceback (most recent call last): File "src/finetune.py", line 88, in main() File "src/finetune.py", line 60, in main train_result = trainer.train() File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/transformers/trainer.py", line 1662, in train return inner_training_loop( File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/transformers/trainer.py", line 1962, in _inner_training_loop self.scaler.unscale_(self.optimizer) File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 282, in unscale_ optimizer_state["found_inf_per_device"] = self._unscale_grads_(optimizer, inv_scale, found_inf, False) File "/opt/conda/envs/python3.8/lib/python3.8/site-packages/torch/cuda/amp/grad_scaler.py", line 210, in _unscale_grads_ raise ValueError("Attempting to unscale FP16 gradients.") ValueError: Attempting to unscale FP16 gradients.

请问你解决了吗，我也出现了这个问题，torch==2.0.1,transfomers==4.30.2,peft==0.3.0
