### ISSUE TITLE
RM数据准备的技巧

### ISSUE THREAD

**Issue by SmileSmith** [hiyouga/ChatGLM-Efficient-Tuning#66]
感谢作者的分享。第一次跑这个项目，有两个问题想请教下

1、如果我在SFT阶段混入部分垂直领域数据，那么在RM结算是不是也需要做类似的操作将垂直领域的数据也加入comparison？
2、项目中`comparison_gpt4_data_zh` 和 `comparison_gpt4_data_en` 是怎么生成的？

comparison看上去有固定的格式，例如:

```
以下是描述任务的说明。编写适当地完成请求的响应。\n\n
```

```
下面是描述任务的指令，与提供进一步上下文的输入配对。编写适当地完成请求的响应。\n\n
```

**Comment by hiyouga** [comment]
1. RM 训练时候不一定需要垂直领域数据，在 SFT 阶段进行垂直领域训练足以。
2. comparison 数据和其他数据的唯一区别在于 output 是一个长度为 2 的 list。
