### ISSUE TITLE
About using acelerate when uses lora tuning with 4-v100 on  one machine

### ISSUE THREAD

**Issue by 1719930244** [hiyouga/ChatGLM-Efficient-Tuning#68]
使用lora-tuning + accelerate launch 报错：
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.

Parameter at index 55 with name base_model.model.transformer.layers.27.attention.query_key_value.lora_B.default.weight has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.

My qustion: 对于marked as ready twice应该如何更改，用了peft库后应该在哪加use _set_static_graph()【没找到位置】

**Comment by hiyouga** [comment]
请查阅 [GitHub Wiki](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/wiki/%E5%B8%B8%E8%A7%81%E6%8A%A5%E9%94%99%E4%BF%A1%E6%81%AF%E6%B1%87%E6%80%BB#runtimeerror-expected-to-mark-a-variable-ready-only-once)。

**Comment by 1719930244** [comment]
抱歉没看仔细！ 非常感谢！
