### ISSUE TITLE
what's the different about quantize lora?

### ISSUE THREAD

**Issue by jiayi37u** [hiyouga/ChatGLM-Efficient-Tuning#69]
code from chatglm
```
if model_args.quantization_bit is not None:
    print(f"Quantized to {model_args.quantization_bit} bit")
    model = model.quantize(model_args.quantization_bit)
if model_args.pre_seq_len is not None:
    # P-tuning v2
    model = model.half()
    model.transformer.prefix_encoder.float()
else:
    # Finetune
    model = model.float()
``` 

code from your repo, lines 205 to 237 from common.py

```
if not is_cublasLt_compatible(cc):
    raise ValueError("The current GPU(s) is incompatible with quantization.")
```
This judgment code returns false, but it doesn't matter if I comment it out

but raise other error`expected scalar type Half but found Float`

Lora的量化和ptuning v2的有什么区别？为什么不能直接通过`model.quantize(8)`实现，如果有区别，if判断有作用，某些gpu无法实现量化，也请给出解决方案。

**Comment by hiyouga** [comment]
LoRA 训练和基于 OpenBMB 的量化不适配，因此只能使用 bitsandbytes 提供的量化方案，因此不能使用 `model.quantize(8)` 而使用 `load_in_8bit=True`。当使用后者时，要判断 GPU 是否适配，也就是这里 if 判断的主要作用。

**Comment by hiyouga** [comment]
@jiayi37u 似乎有些 GPU 可以在不通过 checking 的前提下正常运行，如果注释掉也能运行，那可以通过添加 `--fp16` 参数来正常训练。
