### ISSUE TITLE
ValueError: ChatGLMForConditionalGeneration does not support gradient checkpointing.

### ISSUE THREAD

**Issue by shmily91** [hiyouga/ChatGLM-Efficient-Tuning#7]
大神怎么解决？

**Comment by shmily91** [comment]
python finetune_chatglm.py --do_train --dataset alpaca_gpt4_zh --finetuning_type lora --output_dir output --per_device_train_batch_size 4 --gradient_accumulation_steps 4 --lr_scheduler_type cosine --logging_steps 10 --save_steps 1000 --max_train_samples 10000 --learning_rate 5e-5 --num_train_epochs 1.0 --fp16 --model_name_or_path ../chatglm-6b

**Comment by hiyouga** [comment]
请不要频繁创建issue，该问题的回答请参照#3 中的回复
