### ISSUE TITLE
请问，我想使用原模型（未经微调过的模型）进行eval，该如何加载？我使用

### ISSUE THREAD

**Issue by cc2017111** [hiyouga/ChatGLM-Efficient-Tuning#70]
CUDA_VISIBLE_DEVICES=0 python src/finetune.py \
    --do_eval \
    --dataset abstract2use_dev \
    --checkpoint_dir /media/being/_dev_dva/efficient_chatGLM/ChatGLM-Efficient-Tuning/model/chatGLM_6B \
    --output_dir abstract2use_eval_result_zero \
    --per_device_eval_batch_size 8 \
    --max_samples 50 \
    --predict_with_generate

我使用这个脚本无法加载，报错：ValueError: The fine-tuning arguments are not found in the provided dictionary.

**Comment by hiyouga** [comment]
去掉 `checkpoint_dir` 参数。
