### ISSUE TITLE
lora微调后的模型在jetson平台推理超时

### ISSUE THREAD

**Issue by liaoweiguo** [hiyouga/ChatGLM-Efficient-Tuning#77]
1. 原始模型没问题，速度还行
2. 微调后模型推理超时
3. 微调后模型在Intel + A100上OK

**Comment by hiyouga** [comment]
我不了解 jetson 平台，按照 readme 中的命令行参数进行推理会超时吗？

**Comment by liaoweiguo** [comment]
NV的嵌入式模型（自动驾驶常用）
是的，同样的模型，同样的代码在intel上OK，包括4090和A100都很好。
没有调的也可以

**Comment by hiyouga** [comment]
如果按照#26 的方式将 LoRA 权重合并到原始模型中呢？

**Comment by liaoweiguo** [comment]
试一下，训练模型在数据中心，拖下来要时间

**Comment by liaoweiguo** [comment]
> 如果按照#26 的方式将 LoRA 权重合并到原始模型中呢？

可以了
