### ISSUE TITLE
请问作者是用什么机器跑的呢，V100 or A100 显存需要多大呢～ V100能跑起来吗

### ISSUE THREAD

**Issue by hangzeli08** [hiyouga/ChatGLM-Efficient-Tuning#8]

**Comment by hiyouga** [comment]
我在A100和V100单GPU和多GPU上都做了测试。

请参考：https://github.com/hiyouga/ChatGLM-Efficient-Tuning/blob/main/README_zh.md#%E7%A1%AC%E4%BB%B6%E9%9C%80%E6%B1%82
