### ISSUE TITLE
请问如何使用 int8 推理

### ISSUE THREAD

**Issue by liuzhx2016** [hiyouga/ChatGLM-Efficient-Tuning#80]
请问代码中 infer.py 是可以使用 int8 进行推理吗？为什么我查看GPU 感觉还是在用 fp16 进行推理的。还有一个疑问，能否使用 chatGLM-6B-int8 或者 int4 进行微调呢？谢谢

**Comment by hiyouga** [comment]
对 infer.py 指定 `--quantization_bit` 参数是可以量化模型的，推理时支持 int4 和 int8 的量化。
不建议使用 ChatGLM-6B-int8 或 int4 进行微调，因为它可能导致不可预料的问题。

**Comment by liuzhx2016** [comment]
我对 infer.py 指定 --quantization_bit 8 进行int8量化后，为什么占用的显存是12G 左右，和 fp16 推理消耗的显存是一样的呢？有些不太理解，能否指点一下，谢谢

**Comment by hiyouga** [comment]
直接查看 GPU 显存不一定很准确，因为有 cache。如果使用 int4 量化应该能进一步降低。

**Comment by zzzhaoguziji** [comment]
> 我对 infer.py 指定 --quantization_bit 8 进行int8量化后，为什么占用的显存是12G 左右，和 fp16 推理消耗的显存是一样的呢？有些不太理解，能否指点一下，谢谢

您好，您解决了吗，我也遇到这个问题，量化后和没量化显存几乎一样

**Comment by zzzhaoguziji** [comment]
大神，您好，我将模型lora训练后的模型融合再量化，显存回到7G左右，
config = AutoConfig.from_pretrained("path_to_save_model", trust_remote_code=True, pre_seq_len=128)
model = AutoModel.from_pretrained("path_to_save_model", config=config, trust_remote_code=True).quantize(8).half().cuda()
tokenizer = AutoTokenizer.from_pretrained("path_to_save_model", trust_remote_code=True)

**Comment by zzzhaoguziji** [comment]
> 我对 infer.py 指定 --quantization_bit 8 进行int8量化后，为什么占用的显存是12G 左右，和 fp16 推理消耗的显存是一样的呢？有些不太理解，能否指点一下，谢谢

你需要修改下代码，load参数的时候先不要放入cuda，等模型量化后在.cuda()，这样就只用7G显存了

**Comment by hiyouga** [comment]
@zzzhaoguziji 麻烦请教是如何修改的，我这边也同步更新一下。

**Comment by zzzhaoguziji** [comment]
> model= AutoModel.from_pretrained(
    "./chatglm", trust_remote_code=True).half()

peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False, r=8, lora_alpha=32, lora_dropout=0.1,
    target_modules=['query_key_value',],
)
model = get_peft_model(glm, peft_config)
peft_path = "checkpoint-120/chatglm-lora.pt"
model.load_state_dict(torch.load(peft_path), strict=False)
model.quantize(8)
model.cuda()
model.eval()
我现在是这样做的，如果加载load chatglm参数的时候就.cuda(),显存占用为13g，在.quantize(8)后再.cuda()就是7G

**Comment by zzzhaoguziji** [comment]
> 也可以这么做，自己在外面量化，在.cuda，这样的话就是7个G显存了
model, tokenizer = load_pretrained(model_args)
    print('开始量化')
    model.quantize(8)
    model.cuda()

**Comment by hiyouga** [comment]
@zzzhaoguziji 明白了，感谢
