### ISSUE TITLE
环境问题：报sklearn错误

### ISSUE THREAD

**Issue by xuehui0725** [hiyouga/ChatGLM-Efficient-Tuning#82]
请问下，Python 3.8+对应使用的scikit-learn是什么版本呢？python3.8.6，按照requirement.txt装了对应版本的包，运行时出现：
![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/15153097/65da90e6-1a6e-4673-8476-59b6fcbbb125)

**Comment by xuehui0725** [comment]
4.27.4，按requirement.txt中的版本升级了

**Comment by hiyouga** [comment]
升级一下 sklearn 库呢？
