### ISSUE TITLE
预测/微调读取的样本数与实际不一致？

### ISSUE THREAD

**Issue by CCzzzzzzz** [hiyouga/ChatGLM-Efficient-Tuning#84]
***** Running Prediction *****
[INFO|trainer.py:3070] 2023-05-13 17:24:08,530 >>   Num examples = 923

实际上我的test的数据有“Test set size: 953”，953条，为何只读取了923条？

**Comment by hiyouga** [comment]
可能是数据中有些样本包含了空的 instruction 或 output，在预处理时被忽略了。

**Comment by CCzzzzzzz** [comment]
> 可能是数据中有些样本包含了空的 instruction 或 output，在预处理时被忽略了。

谢谢！你说得对。我在数据预处理的时候将没有标注的output处理为空。
