### ISSUE TITLE
修改认知的例子对原始模型污染很严重

### ISSUE THREAD

**Issue by podanshu** [hiyouga/ChatGLM-Efficient-Tuning#85]
测试了一下，例子中的对自我认知的修改，所用参数均和例子中的一样，发现运行后，几乎所有问题都带有self_cognition里的内容，请问这样的情况怎么解决呢，需要怎么调整参数

**Comment by hiyouga** [comment]
该例子仅提供了一个微调的示例，因为数据集样本数很少，模型容易过拟合到该数据集上，且学习率过大和 epoch 数过多会导致模型原本知识被破坏。在实际环境中可以考虑以下几点解决知识遗忘问题：
1. 使用样本数更多且更全面的数据集
2. 适当减小学习率和 epoch 数
3. 使用 RLHF 训练

**Comment by podanshu** [comment]
1、我的理解是学习率越小不是越容易过拟合么？
2、你的意思是，我需要把这20条的数据合并到其他数据集里，这样才行么？我试过多个数据集，如：--dataset alpaca_zh,self_cognition，但这样完全没有任何效果；
3、epoch并没有设置多大，一般都是5或者10。

**Comment by hiyouga** [comment]
的确在[一般认知](https://arxiv.org/pdf/1708.07120.pdf)中是学习率越大越不容易过拟合，但它的前提是有足够大的训练集。在本样例中，训练集的样本极少，过大的学习率会导致原模型的参数偏移过大，发生灾难性遗忘的问题。

**Comment by podanshu** [comment]
请问哪例子里是RLHF的使用方法

**Comment by hiyouga** [comment]
1. RLHF 使用方法请查看 readme 文件和 examples 文件夹。
2. 1e-3 已经属于较大的学习率了，一般采用 1e-5~1e-3 的学习率比较合适。
3. 直接放到一万条数据集可能会导致模型学习不到知识，可以考虑多次重复在小数据集上的训练。

**Comment by podanshu** [comment]
抱歉，将这20条数据放在了几百条的数据集里训练，超参为：  
    --do_train \
    --dataset self_cognition \
    --finetuning_type lora \
    --output_dir  my-6b\
    --overwrite_cache False \
    --per_device_train_batch_size 6 \
    --gradient_accumulation_steps 6 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 2e-5 \
    --num_train_epochs 3.0 \
    --fp16 \

训练完成后，无任何效果，看不到训练痕迹，按照列子使用train_ppo.py，结果报错：

![image](https://github.com/hiyouga/ChatGLM-Efficient-Tuning/assets/133554028/c7fc1127-58a3-4bec-8e43-69bb9e1fb4f1)

使用方法为：
accelerate launch src/train_ppo.py \
    --do_train \
    --dataset self_cognition \
    --finetuning_type lora \
    --output_dir  my-6b\
    --overwrite_cache False \
    --per_device_train_batch_size 6 \
    --gradient_accumulation_steps 6 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 1000 \
    --learning_rate 2e-5 \
    --num_train_epochs 3.0 \
    --fp16 \
    --ddp_find_unused_parameters False

**Comment by hiyouga** [comment]
1. 对于 2e-5 的学习率来说，3 个 epoch 太少了，需要增加 epoch。
2. 报错信息截图不完整，看不出问题在哪里。

**Comment by podanshu** [comment]
需要先训练奖励模型，然后再RLHF？

**Comment by hiyouga** [comment]
1. PPO 模型训练推荐使用 1e-6 的学习率，并且限制在 2000 steps 以内。
2. RLHF 是基于监督微调模型和奖励模型两个底座来训练的。
3. 在训练的 output_dir 不变时，若设置 overwrite_output_dir 则会覆盖之前的训练结果。如果想在之前的权重上接着训练，请指定 checkpoint_dir 并设置另外的 output_dir，我们不推荐使用同一个 output_dir。
