### ISSUE TITLE
有支持DeepSpeed加速训练的计划吗？

### ISSUE THREAD

**Issue by yt7589** [hiyouga/ChatGLM-Efficient-Tuning#88]
DeepSpeed有一个好处，就是当GPU显存不足时，可以通过offload技术，将权重等移到CPU内存中，可以使用低端显卡来进行训练。所以特别希望能提供DeepSpeed支持！
另外，同样是清华大学出的技术，BMTrain训练据他们自己讲比DeepSpeed更高效，BMInf推理也更高效，也可以考虑支持这个系列的技术。

**Comment by GUORUIWANG** [comment]
请问rlhf训练的时候支持deepspeed运行吗

**Comment by hiyouga** [comment]
> 请问rlhf训练的时候支持deepspeed运行吗

PPO 训练请使用 accelerate 而非 deepspeed。
