### ISSUE TITLE
RLHF的效果是否有提升

### ISSUE THREAD

**Issue by reborm** [hiyouga/ChatGLM-Efficient-Tuning#91]
您好，请问您离线测试过RLHF的效果吗？我用我自己的数据集进行测试，感觉reward+RLHF效果跟直接finetune差的挺远的

**Comment by hiyouga** [comment]
RLHF 应当结合 SFT 使用，单独使用 RLHF 很难有效果提升。

**Comment by reborm** [comment]
> RLHF 应当结合 SFT 使用，单独使用 RLHF 很难有效果提升。

您的意思是先使用SFT进行fine-tune，然后模型load finetune的结果再进行reward+RLHF吗

**Comment by hiyouga** [comment]
在 [InstructGPT](https://arxiv.org/abs/2203.02155) 原论文中，作者首先进行 SFT，然后在 SFT 模型的基础上进行 RLHF，我们在 Readme 和 examples 中给出了 PPO 训练的例子。
