### ISSUE TITLE
额外定义Accelerator

### ISSUE THREAD

**Issue by gugugu-469** [hiyouga/ChatGLM-Efficient-Tuning#92]
1.我可以在函数中额外定义`Accelerator()`吗，因为我想要在您代码的基础上添加额外的功能，目前的需求是只在主进程中执行一些函数，想问下是否可以自定义`Accelerator()`，目前通过`if args.local_process_index == 0:`暂时解决此功能。
2.可以显示定义`Accelerator()`并`prepare()`来构建模型和数据吗，这会使得代码阅读更加清晰，并帮助代码修改。

**Comment by hiyouga** [comment]
我们使用的 Trainer API 内部包含了 Accelerator 机制，因此没有必要额外定义 Accelerator。
如果想只在主进程执行某些函数，请使用 `trainer.is_world_process_zero()` 进行判断。
