### ISSUE TITLE
生成文本长度无法修改。

### ISSUE THREAD

**Issue by cc2017111** [hiyouga/ChatGLM-Efficient-Tuning#94]
accelerate launch src/finetune.py \
    --do_train \
    --dataset dpabs2claims_train \
    --finetuning_type lora \
    --lora_rank 16 \
    --max_source_length 2048 \
    --max_target_length 2048 \
    --output_dir patent_dpabs2claims_lora_2048_1 \
    --per_device_train_batch_size 2 \
    --gradient_accumulation_steps 8 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --save_steps 100 \
    --learning_rate 5e-5 \
    --num_train_epochs 1.0 \
    --ddp_find_unused_parameters False \
    --plot_loss \
    --fp16

我使用如上脚本进行训练，生成序列长度固定为308，出现硬截断，这是什么情况？
[array([    5,     9,     7, 64276, 64984, 66897,     6, 64111,    12,
       65549, 63866, 76071,    27, 65549, 63866, 64358, 70826,     6,
       65282, 64338, 66187, 65549, 63866, 76071, 73128, 63885, 66723,
       64338, 66187, 73128, 69122, 64358, 66108,    27, 65549, 63866,
       64866, 70826,     6, 65282, 64338, 66187, 64984, 66897, 63825,
       65607, 63824, 65786, 63851, 64984, 66897, 63825, 66391, 64638,
       63826, 65786, 63831, 64984, 66897, 92370, 64638, 64102, 65549,
       63866,     6, 63885, 66723, 64338, 66187, 91891, 66897, 63825,
       65607, 63824, 85372, 66391, 64638, 63826, 85372, 65628, 64638,
       64102, 65549, 63866, 69122, 64866, 66108,    27, 65549, 63866,
       70606,     6, 66723, 64358, 66108, 63826, 64866, 66108, 64102,
       65549, 63866, 64337, 65549, 63866, 76071, 71793, 63823,    10,
           7, 64298, 67949, 63996,     9, 81777, 91891, 66897,     6,
       64133,     6, 64358, 66108, 63826, 64866, 66108, 64102, 65549,
       63866, 63834, 64866, 66108,     6, 81777, 64358, 66108, 63826,
       64866, 66108, 64102, 65549, 63866, 63834, 64358, 66108, 63823,
          13,     7, 64298, 67949, 63996,     9, 81777, 91891, 66897,
           6, 64133,     6, 64358, 66108, 63826, 64866, 66108, 64102,
       65549, 63866, 63834, 64866, 66108,     6, 81777, 64358, 66108,
       63826, 64866, 66108, 64102, 65549, 63866, 63834, 64358, 66108,
           6, 81777, 64358, 66108, 63826, 64866, 66108, 64102, 65549,
       63866, 63834, 64866, 66108,     6, 81777, 64358, 66108, 63826,
       64866, 66108, 64102, 65549, 63866, 63834, 64358, 66108,     6,
       81777, 64358, 66108, 63826, 64866, 66108, 64102, 65549, 63866,
       63834, 64866, 66108,     6, 81777, 64358, 66108, 63826, 64866,
       66108, 64102, 65549, 63866, 63834, 64358, 66108,     6, 81777,
       64358, 66108, 63826, 64866, 66108, 64102, 65549, 63866, 63834,
       64866, 66108, 63823,    16,     7, 64298, 67949, 63996,     9,
       81777, 91891, 66897,     6, 64133,     6, 64358, 66108, 63826,
       64866, 66108, 64102, 65549, 63866, 63834, 64866, 66108,     6,
       81777, 64358, 66108, 63826, 64866, 66108, 64102, 65549, 63866,
       63834, 64358, 66108,     6, 81777, 64358, 66108, 63826, 64866,
       66108, 64102, 65549, 63866, 63834, 64866, 66108,     6, 81777,
       64358, 66108, 63826, 64866, 66108, 64102, 65549, 63866, 63834,
       64358, 66108]),
我的训练数据集长度都很长平均label长度1500。

**Comment by hiyouga** [comment]
更新后的代码已解决该问题。
