### ISSUE TITLE
关于绘制loss函数曲线的问题

### ISSUE THREAD

**Issue by CCzzzzzzz** [hiyouga/ChatGLM-Efficient-Tuning#99]
将参数plot_loss设置为True后，保存的结果在哪我没有找到。是否与此报错有关？
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g
. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incor
rect results. For more information, please see http://www.intel.com/software/products/support/.

**Comment by hiyouga** [comment]
结果默认会保存在 output_dir 中。
关于此报错请参考 https://zhuanlan.zhihu.com/p/371649016。

**Comment by CCzzzzzzz** [comment]
> 



> 结果默认会保存在 output_dir 中。 关于此报错请参考 [https://zhuanlan.zhihu.com/p/371649016。](https://zhuanlan.zhihu.com/p/371649016%E3%80%82)

该链接已失效

**Comment by hiyouga** [comment]
> > 
> 
> > 结果默认会保存在 output_dir 中。 关于此报错请参考 [https://zhuanlan.zhihu.com/p/371649016。](https://zhuanlan.zhihu.com/p/371649016%E3%80%82)
> 
> 该链接已失效

[response_tensors](https://zhuanlan.zhihu.com/p/371649016)
